### ISSUE TITLE
Ricochet Exchange REX Markets Keys

### ISSUE THREAD

**Issue by mikeghen** [superfluid-finance/protocol-monorepo#1027]
Describe the SuperApp:

Ricochet Exchange

Network will be deployed?:
Polygon

Deployer address:
0x3226C9EaC0379F04Ba2b1E1e1fcD52ac26309aeA

Factory address:
NA

Link of repo of the contract to be deployed:
https://github.com/Ricochet-Exchange/ricochet-protocol

Contact info for developer:
@mikeghen

Notes:
Please give me a batch of 10 keys

**Comment by d10r** [comment]
Keys:
1: 0x3d128e65d40b814228a3d0b8c8c5a2703eef68aafc7f6b6adf8e0624b9fd3441 ([gov action](https://polygonscan.com/tx/0xe06a66525ec0acee00bbf2fa86459af5da8de1a89d9afe185d6ac343a98c7c10))
2: 0xec1f5730cd4bf40b596f0a779a5ba724c27bd8b1e22a29d60e49a861ae33a3c9 ([gov action](https://polygonscan.com/tx/0x9889866e26baa614e080bf38fd7b49a479f06b09f9719b833f0d41ac474b14b0))
3: 0xd114a10e73538187abaf3a498a3f4ad168718961458991d22141cccb4e645120 ([gov action](https://polygonscan.com/tx/0x756e36e774cfc3b1bd00f95b40f5d66981bc672d3e49a4583577df53deeb460a))

All 3 keys are valid for deployer 0x3226C9EaC0379F04Ba2b1E1e1fcD52ac26309aeA and expire on 2022-11-08
