### ISSUE TITLE
[ETHEREUM-CONTRACTS] Configurable global CFA hooks.

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#1096]
## Notes

- the hook address (ICFAGlobalHook) is an immutable field in the CFA logic contract.
- if the hook is set, it is invoked for each create/update/delete flows.
- the hook actions are try/catched, so no danger of blocking CFA operations globally.

**Comment by 0xdavinchee** [comment]
gonna close this cause this feature is merged
