### ISSUE TITLE
[ETHEREUM-CONTRACTS] Unchecked for-loop increment  

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1101]
A super low-hanging fruit gas optimization (originally pointed out by yAcademy) is using unchecked on the increment value and should be applied to places where we have for loops. As long as the initial value begins at zero and is only incremented by one each time, it is impossible to overflow.

This makes a lot of sense to apply because a lot of the places where we have these for loops are called a lot.

**Comment by 0xdavinchee** [comment]
Adds a tiny bit more code and saves a trivial amount of gas per iteration (30-40 gas units), but this code is hit a lot so overall gas savings over lifetime usage may be significant.

**Comment by hellwolf** [comment]
Any code samples? I thought it would make code a bit more ugly and tedious to write.

**Comment by 0xdavinchee** [comment]
[`SuperfluidToken.realtimeBalanceOf`](https://github.com/superfluid-finance/protocol-monorepo/blob/dev/packages/ethereum-contracts/contracts/superfluid/SuperfluidToken.sol#L72):

See the two instances of: `// @note CHANGE ON THIS LINE`

```
function realtimeBalanceOf(
   address account,
   uint256 timestamp
)
   public view override
   returns (
       int256 availableBalance,
       uint256 deposit,
       uint256 owedDeposit)
{
    availableBalance = _sharedSettledBalances[account];
    ISuperAgreement[] memory activeAgreements = getAccountActiveAgreements(account);
    for (uint256 i = 0; i < activeAgreements.length;) { // @note CHANGE ON THIS LINE
        (
            int256 agreementDynamicBalance,
            uint256 agreementDeposit,
            uint256 agreementOwedDeposit) = activeAgreements[i]
                .realtimeBalanceOf(
                     this,
                     account,
                     timestamp
                 );
        deposit = deposit + agreementDeposit;
        owedDeposit = owedDeposit + agreementOwedDeposit;
        // 1. Available Balance = Dynamic Balance - Max(0, Deposit - OwedDeposit)
        // 2. Deposit should not be shared between agreements
        availableBalance = availableBalance
            + agreementDynamicBalance
            - (
                agreementDeposit > agreementOwedDeposit ?
                (agreementDeposit - agreementOwedDeposit) : 0
            ).toInt256();
        unchecked { ++i; }  // @note CHANGE ON THIS LINE
    }
}
```

**Comment by hellwolf** [comment]
okay, ugly.

Alternative is to use solidity feature of user defined type for incremental, with very limited interface what it can be used for:

- unwrap back to uint256.
- unsafeInc() function for unchecked inc.

These are all type safe way for new types, and type information are eliminated during runtime hence "zero-cost abstraction"


Try something like:

```
for (Counter i; i.unwrap() < activeAgreements.length; i.unsafeInc())
```

**Comment by 0xdavinchee** [comment]
okay - may be a good place to start introducing user defined types

**Comment by hellwolf** [comment]
Actually it doesn't have in-place way of updating the struct value, so no way to introduce for in-place "side-effect" :D 

That'd mean pure version of returning a new value. But then again, not sure if would be optimized by the compiler and make it zero-cost too.

Check it out. But do remember to turn optimizer on, no point to compare without using optimizer.  The future should still be biased towards more pure code and let optimizers do more work.

**Comment by hellwolf** [comment]
```

struct Counter { uint val; }
function unsafeInc(Counter memory c) pure returns (Counter memory) {
    unchecked { ++c.val; }
    return c;
}
```

**Comment by hellwolf** [comment]
Ah, actually it is doable, try it out. It should be elegant type-safe way of doing it.

**Comment by 0xdavinchee** [comment]
The savings here are so trivial (~100 per inc) I don't think this is worth bothering with, I doubt we rarely increment more than double digits.

Also, I'm not 100% sure if this is the best place to utilize user defined types. This would be a library to reduce code duplication and maintainability overhead, so we could just create a lib for uint256. Using user defined types makes the code too verbose if the type is coming from the library.
