### ISSUE TITLE
[SUBGRAPH] add gasUsed property

### ISSUE THREAD

**Issue by benjlevesque** [superfluid-finance/protocol-monorepo#1103]
# Problem

The subgraph contains information about `gasPrice`, but not about `gasUsed`, which makes it harder to compute the price of the transaction. 

#  Possible Solution
This [wasn't possible](https://github.com/graphprotocol/graph-node/issues/2619) until recently, but is now available on `event.receipt.gasUsed` [docs](https://thegraph.com/docs/en/developing/creating-a-subgraph/#transaction-receipts-in-event-handlers).

**Comment by 0xdavinchee** [comment]
@benjlevesque I tried this out following the steps listed in [here](https://thegraph.com/docs/en/developing/creating-a-subgraph/#transaction-receipts-in-event-handlers) and bumped the versions of graph-cli and graph-ts to the latest versions and even tried installing the alpha versions mentioned [here](https://github.com/graphprotocol/docs/pull/102#issuecomment-1129730794). You can checkout the linked PR to see that the past two builds failed because of an indexing error. The error probably doesn't display there, but I've tested it locally and I get:
```
graph-node_1  | Oct 17 12:50:34.388 ERRO Subgraph error 1/10, code: SubgraphSyncingFailure, error: Tried to read AssemblyScript value that is 'null'. Suggestion: look into the function that the error happened and add 'log' calls till you find where a 'null' value is being used as non-nullable. It's likely that you're calling a 'graph-ts' function (or operator) with a 'null' value when it doesn't support it.	wasm backtrace:	    0: 0x3759 - <unknown>!src/mappings/host/handleAgreementClassUpdated	 in handler `handleAgreementClassRegistered` at block #4 (4c1316bccd765376b914a522af47ff136a54a32298caba7b6d197aff69d929d2), block_hash: 0x4c1316bccd765376b914a522af47ff136a54a32298caba7b6d197aff69d929d2, block_number: 4, sgd: 1, subgraph_id: QmRKKKFKan7RuxSvCP5wAgFcTfkhN3GQWd8Ac2HZrD5dbP, component: SubgraphInstanceManager
```

**Comment by benjlevesque** [comment]
sorry @0xdavinchee I didn't manage to run the superfluid subgraph (on goerli), so I can't reproduce your issue :/

did you try testing for null before accessing the  `receipt`? maybe with a log you will see what's happening...

```ts
   if (receipt) {
        ev.gasUsed = receipt.gasUsed;
    } else {
        log.warning("receipt is null", []);
    }
```

**Comment by 0xdavinchee** [comment]
> sorry @0xdavinchee I didn't manage to run the superfluid subgraph (on goerli), so I can't reproduce your issue :/
> 
> did you try testing for null before accessing the  `receipt`? maybe with a log you will see what's happening...
> 
> ```ts
>    if (receipt) {
>         ev.gasUsed = receipt.gasUsed;
>     } else {
>         log.warning("receipt is null", []);
>     }
> ```

Yeah, I think this actually throws when you try to access a property that's null
