### ISSUE TITLE
Unlock Integration SuperApp

### ISSUE THREAD

**Issue by ngmachado** [superfluid-finance/protocol-monorepo#1111]
**Describe the SuperApp:**

Using Superfluid, Unlock plans to allow creators to monetize on a recurring basis, through payment streams. Users will be granted a Key if they start a stream of a certain quantity to the creator, and the Key will be revoked if the stream is interrupted.
_A clear and concise description of the SuperApp_

**Network will be deployed?:**

Polygon

**Deployer address:**

0xa67E5e25DBEa60E843dDe146f4518f69e23bbe78

**Factory address:**

0x10C0d608226398361c9cC77E420e48e6EfE2f1d3

**Link of repo of the contract to be deployed:**

https://github.com/ngmachado/ul-integration

**Contact info for developer:**

https://twitter.com/Logicb0x

**Notes:**

This app uses Factory Clone pattern. Needs a factory registration.

**Comment by d10r** [comment]
gov action prepared in https://github.com/superfluid-finance/protocol-monorepo/actions/runs/3199395914

**Comment by hellwolf** [comment]
![image](https://user-images.githubusercontent.com/186660/194514799-526a23b9-e599-46f8-8f7a-e59a5f9a47bc.png)
