### ISSUE TITLE
[ETHEREUM-CONTRACTS] Brittle build process in non-virgin environment - need better "clean" script?

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#1151]
My starting point: run the TOGA test, because I want to modify the contract.  
This is taking place in my main copy of the monorepo, not a fresh clone.

Attempt 1:
```
yarn dev
$ yarn dev
yarn run v1.22.19
$ tasks/dev.sh
$ nodemon -e sol,js,ts -x 'yarn test:contracts:hardhat 2>&1'
[nodemon] 2.0.19
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: sol,js,ts
[nodemon] starting `yarn test:contracts:hardhat 2>&1`
$ yarn run-hardhat test testsuites/all-contracts.ts
$ IS_HARDHAT=true hardhat test testsuites/all-contracts.ts
An unexpected error occurred:

Error: Cannot find module '../typechain-types'
```

Ok, I know. I manually deleted `typechain-types` because it made a `yarn build` fail before.  
I expected it to be rebuilt by `yarn build`, but that seems to not be the case:

```
Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.
$ yarn run-hardhat compile
$ IS_HARDHAT=true hardhat compile
Nothing to compile
No need to generate any newer typings.
```

So, Hardhat seems to think there's nothing to be done, likely because artifacts are up to date.  
For truffle stuff, `yarn build` does preliminary cleanup, but not for hardhat stuff. See npm scripts:
```
        "build:contracts": "rm -f build/contracts/*;yarn build:contracts-truffle",
        "build:contracts-truffle": "yarn run-truffle compile",
        "build:contracts-hardhat": "yarn run-hardhat compile",
```
This is confusing. "build:contracts" is neither a generalized script (building for both truffle and hardhat) nor just an alias for truffle (one has preliminary cleanup, the other doesn't). Maybe we want to keep "build:contracts" as alias (legacy reasons?), but cleanup policy should be consistent.

What's also not being cleaned up: *d.ts files in `scripts` directory. Can also make a re-run of `yarn build` fail.  
If the expectation is for `yarn build` to work on non-virgin checkouts too, we probably need to update the root `clean` script to include everything needed, especially everything generated by the typescript build steps (typechain-types, *.d.ts files, ?)

There seem to be other remnants I'm not aware of. Build still failing for me after deleting `artifacts` and `typechain-types` with:
```
$ yarn run-hardhat compile
yarn run v1.22.19
$ IS_HARDHAT=true hardhat compile
Generating typings for: 140 artifacts in dir: typechain-types for target: ethers-v5
Successfully generated 328 typings!
Compiled 104 Solidity files successfully
Error HH700: Artifact for contract "@openzeppelin/contracts/utils/Create2.sol:Create2" not found.
```

This was probably what led me to manually delete `typechain-types` in the first place.

After some grepping it turns out to be caused by remnants in `cache/solidity-files-cache.json`. After deleting that, I can finally build and test.

**Comment by 0xdavinchee** [comment]
resolved in https://github.com/superfluid-finance/protocol-monorepo/pull/1167
