### ISSUE TITLE
CFAv1Library - Args order not intuitive 

### ISSUE THREAD

**Issue by ngmachado** [superfluid-finance/protocol-monorepo#1153]
All functions on SF follow `supertoken, sender, receiver` but the lib change this order. Would be a good clean API to follow always the same API. 

https://github.com/superfluid-finance/protocol-monorepo/blob/900d7ba174bc649a1573b5c9b87f688f621fb874/packages/ethereum-contracts/contracts/apps/CFAv1Library.sol#L56

**Comment by hellwolf** [comment]
We are aware, and it will be addressed in #1178
