### ISSUE TITLE
[Deployer Whitelisting Request] Ricochet Merch Launchpad Contracts

### ISSUE THREAD

**Issue by mikeghen** [superfluid-finance/protocol-monorepo#1157]
**Describe the SuperApp:**

REX Merch Launchpads are used to auction off REX Merch tokens similarly to how the REX Launchpad is used to auction off RIC tokens. 

**Network will be deployed?:** Polygon

**Deployer address:** 0x3226C9EaC0379F04Ba2b1E1e1fcD52ac26309aeA

**Factory address:** NA

**Link of repo of the contract to be deployed:** https://github.com/Ricochet-Exchange/ricochet-protocol/tree/v2/contracts/launchpad

**Contact info for developer:** @mikeghen

**Notes:** This contract was previously deployed and is being redeployed with new tokens for the initialization.

**Comment by mikeghen** [comment]
@0xdavinchee @d10r, hey guys, let me know if you have some time to make a key for me to use for the next few months while I deploy some launchpads.

**Comment by d10r** [comment]
@hellwolf pls sign

The registration key is "k1".
Once signed by gov, the deployer account can deploy SuperApps for 6 months (it's not one-time use anymore).

**Comment by mikeghen** [comment]
@d10r, @hellwolf, I just tried the key `k1` I think it still needs to be approved.

**Comment by hellwolf** [comment]
@mikeghen just in

![image](https://user-images.githubusercontent.com/186660/201959594-c8aa5bb7-fb22-48b3-82be-a1e654047038.png)

**Comment by mikeghen** [comment]
awesome! thanks @hellwolf 🚰
