### ISSUE TITLE
[Deployer Whitelisting Request]: Geo Web Beneficiary

### ISSUE THREAD

**Issue by codynhat** [superfluid-finance/protocol-monorepo#1177]
**Describe the SuperApp:**

The BeneficiarySuperApp is a simple super app that does two things:
1. Tracks the timestamps of when flows to it are terminated
2. Allows a designated "owner" to transfer a certain ERC-20 token from it

This super app collects funds from all network fee payments in the Geo Web. The owner will be a multisig to start that is the controller of these funds.

**Network will be deployed?:** Optimism

**Deployer address:** 0x4dc45eAc9eE25Af88958c94461fd46175C47744a

**Factory address:** N/A

**Link of repo of the contract to be deployed:** https://github.com/Geo-Web-Project/core-contracts/blob/main/contracts/beneficiary/BeneficiarySuperApp.sol

**Contact info for developer:** @codynhat, codynhat#7156 in Discord

**Comment by codynhat** [comment]
Updated to include the deployer address.

**Comment by d10r** [comment]
the registration key is "k1".

@hellwolf please sign the gov action

**Comment by hellwolf** [comment]
![image](https://user-images.githubusercontent.com/186660/203943588-a2b6c91b-40f2-4850-b426-08592c8b5756.png)

good to go!
