### ISSUE TITLE
[ETHEREUM-CONTRACTS] Investigate Uniswap Permit2

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#1180]
## Notes

- https://uniswap.org/blog/permit2-and-universal-router

**Comment by hellwolf** [comment]
Can delegatable supersede permit2:

- would anyone to implement an alternative ERC20.approve hub?

**Comment by d10r** [comment]
follow-up: https://github.com/superfluid-finance/protocol-monorepo/issues/1482

**Comment by hellwolf** [comment]
superceded by #1482
