### ISSUE TITLE
Investigate Delegatable

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#1181]

**Comment by 0xdavinchee** [comment]
Output:
- [ ] How does it work?
- [ ] Why is it relevant?
- [ ] How can we integrate it at Superfluid?
   - [ ] What does this entail in terms of a spec, ticket size, etc.?
- [ ] What other possibilities are there in general?

**Comment by 0xdavinchee** [comment]
did a presentation w/ some slides here: https://docs.google.com/presentation/d/1QpW8XOWPaOv7sx6gP2A6YxBIWmcC4RseyplCavStvHA/edit#slide=id.p

I think we can close this once I do a short write up
