### ISSUE TITLE
[ETHEREUM-CONTRACTS] Clear up Biconomy new/old forwarder status

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#1186]
Following up from: https://github.com/superfluid-finance/protocol-monorepo/issues/1083

## Note

There is still some confusion around which biconomy forwarders are actually actively being used from biconomy system; it appears that the so called "old" forwarders are the ones having ongoing transactions (on matic).

**Comment by saflamini** [comment]
@hellwolf I was able to get this working today, will follow up with documentation

**Comment by hellwolf** [comment]
Nice @saflamini. Looking forward to.
