### ISSUE TITLE
[ETHEREUM-CONTRACTS] goerli phantom stream

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#1187]
On goerli, we repeatedly get reports of an insolvent account: 0xa8551f0a686eb1eeae9a743548dc252565d0bef1

Negative accounts for token ETHx (0x5943f705abb6834cad767e6e4bb258bc48d9c947) for longer than 600 seconds outside patrician period
[
  '  acc 0xa8551f0a686eb1eeae9a743548dc252565d0bef1, availableBalance -0.22422703785984474, pppPeriod pirate, critical for 106.77472222222222 hours | [Close1](https://ipfs.io/ipfs/QmRo8TSehXq5Q7Lj4HWAEzrFbcW2hyAHg4Vh7Xszm1Nwp3/stream-closer.html?chainId=5&token=0x5943f705abb6834cad767e6e4bb258bc48d9c947&sender=0xa8551f0a686eb1eeae9a743548dc252565d0bef1&receiver=0x658e1b019f2f30c8089a9ae3ae5820f335bd9ce4), [Close2](https://ipfs.io/ipfs/QmRo8TSehXq5Q7Lj4HWAEzrFbcW2hyAHg4Vh7Xszm1Nwp3/stream-closer.html?chainId=5&token=0x5943f705abb6834cad767e6e4bb258bc48d9c947&sender=0xa8551f0a686eb1eeae9a743548dc252565d0bef1&receiver=0x91f96284285b1c64b42bf6495fd20d4e0c76b7ff)'
]

Problem: when trying to close that stream, it "doesn't exist".
![image](https://user-images.githubusercontent.com/5479136/203524476-20263d8e-2572-469a-bedd-39cde5711e75.png)

Our current explanation is that it's a remnant of a very early protocol deployment and later non-backwards-compatible upgrade.
We don't see such issues on other networks.

In order to get rid of the alerts, [I'm currently sending 0.0025 ETHx/h to the problem account](https://app.superfluid.finance/stream/goerli/0x30b125d5fc58c1b8e3ccb2f1c71a1cc847f024ee-0xa8551f0a686eb1eeae9a743548dc252565d0bef1-0x5943f705abb6834cad767e6e4bb258bc48d9c947-1.0).
As long as it's not too difficult to get GörliETH, we can leave it as that.

This issue is just to have the status quo documented in case we want to take further action at some point in the future.

**Comment by hellwolf** [comment]
It was due to an ancient protocol bug during development, and the goerli network is left with this artifact forever. We have workaround it so that it doesn't trigger our tooling errors.
