### ISSUE TITLE
 Framework.ts  depended @nomiclabs   is it necessary??

### ISSUE THREAD

**Issue by zinderud** [superfluid-finance/protocol-monorepo#1191]
I  build for application  my  app error

`Error: node_modules/@superfluid-finance/sdk-core/dist/module/Framework.d.ts:1:38 - error TS2307: Cannot find module '@nomiclabs/hardhat-ethers/types' or its corresponding type declarations.

1 import { HardhatEthersHelpers } from "@nomiclabs/hardhat-ethers/types";`

It has a dependency with nomiclabs for the javascript sdk. The dependency for the test environment is reasonable, but is this dependency needed in production? thanks.

**Comment by hellwolf** [comment]
@0xdavinchee @kasparkallas thoughts?

**Comment by 0xdavinchee** [comment]
@kasparkallas created an issue to this: https://github.com/superfluid-finance/protocol-monorepo/issues/1174

**Comment by zinderud** [comment]
I am sorry . I haven't seen it opened before

**Comment by hellwolf** [comment]
> I am sorry . I haven't seen it opened before

not at all, thanks for flagging it.
