### ISSUE TITLE
[ETHEREUM-CONTRACTS]  Wiki has many TODOs

### ISSUE THREAD

**Issue by ngmachado** [superfluid-finance/protocol-monorepo#1192]
### 9. Informational - Documentation wiki has many TODOs

The Superfluid wiki at https://github.com/superfluid-finance/protocol-monorepo/wiki contains documentation about the system. It is incomplete and has many missing paragraphs or pages. This should be fixed to make sure developers use and interface with the protocol properly.

ref: https://github.com/superfluid-finance/platform-monorepo/issues/76

**Comment by hellwolf** [comment]
It's being cleaned up, and to be completed in the GDA wrapup phase: https://github.com/superfluid-finance/superfluid-stories/issues/266


![image](https://github.com/superfluid-finance/protocol-monorepo/assets/186660/718f1b3d-0ba9-4d2c-9d91-c8c9c15cb7db)
