### ISSUE TITLE
[Deployer Whitelisting Request] Vesting and Scheduler apps

### ISSUE THREAD

**Issue by ngmachado** [superfluid-finance/protocol-monorepo#1200]
**Describe the SuperApp:**

Vesting and Scheduler apps

_A clear and concise description of the SuperApp_

Is just SuperApp to allow batching from our dashboard.

**Network will be deployed?:**

Polygon, BSC.

**Deployer address:**

0xa67E5e25DBEa60E843dDe146f4518f69e23bbe78

**Factory address:**
No Factory.

**Link of repo of the contract to be deployed:**

https://github.com/superfluid-finance/platform-monorepo/tree/master/packages/evm-contracts/scheduler

**Contact info for developer:**

Superfluid Team, @ngmachado @vmichalik @d10r @kasparkallas 

**Notes:**

**Comment by d10r** [comment]
gov actions ready to be signed @hellwolf 

the registration key is "k1"

**Comment by hellwolf** [comment]
![image](https://user-images.githubusercontent.com/186660/207010017-c99de76e-7ca5-46b4-984d-24d81391cb69.png)

Approved!

**Comment by hellwolf** [comment]
![image](https://user-images.githubusercontent.com/186660/207063096-3d9a033a-f33f-432d-b655-f08dd164fd81.png)

BSC
