### ISSUE TITLE
[Deployer Whitelisting Request] Subscription-NFTs

### ISSUE THREAD

**Issue by rashtrakoff** [superfluid-finance/protocol-monorepo#1232]
**Describe the SuperApp:**

This superapp acts as an existential NFT contract i.e., if someone is streaming to the superapp contract, the `balanceOf` function in this superapp returns 1 else, 0. This can be used in a variety of applications but I mainly built this for subscriptions based token-gating use-cases. For example, if I want to only give access to a blog if a user subscribes to me, I can create a superapp and the subscribers can stream to this superapp. TBH the name hasn't been decided but the contract is called `StreamManager` deployed by `StreamManagerFactory`.

**Network will be deployed?:**

Polygon mainnet

**Deployer address:**

`0xDc163db611298E940B524D233687f3b62b7AE29f`

**Factory address:**

`0x222fa45e148Bb5E23f5E10b6bc27a47Ca55f4EcB`

**Link of repo of the contract to be deployed:**

https://github.com/rashtrakoff/Subscription-NFTs

**Contact info for developer:**

Discord: rashtrakoff#2547

**Notes:**

These contracts are only meant for testing though I don't expect major changes in the future given that they are quite simple, to begin with.

**Comment by saflamini** [comment]
Hey @rashtrakoff - cool stuff here.

One thing - can you consider using trycatch in the termination callback? if either update or delete flow calls revert, the super app could get jailed

**Comment by rashtrakoff** [comment]
Sure thing! Let me redeploy the implementation contract and get back to you.

**Comment by rashtrakoff** [comment]
@saflamini The implementation contract with `try/catch` implemented has been deployed. For reference, [this](https://polygonscan.com/address/0x2b576c5f94cde58172ebcaa52e0f365084ff27fb) is the new implementation contract's address and [this](https://github.com/rashtrakoff/Subscription-NFTs/blob/main/src/StreamManager.sol) is the corresponding Github URL of the contract code. Hope this helps!

**Comment by rashtrakoff** [comment]
> Hey @rashtrakoff - cool stuff here.
> 
> One thing - can you consider using trycatch in the termination callback? if either update or delete flow calls revert, the super app could get jailed

I don't think update calls reverting (`afterAgreementUpdated`) jails the app right? AFAIK, reverts in `afterAgreementTerminated` jail the superapp. Could you confirm this please 😅.

**Comment by d10r** [comment]
gov action ready to be signed @hellwolf

**Comment by rashtrakoff** [comment]
Hey @hellwolf , sorry to rush you but any updates on this?

**Comment by hellwolf** [comment]
![image](https://user-images.githubusercontent.com/186660/208061783-edd4d661-5297-404c-897f-4d79700daaec.png)

@rashtrakoff good luck!
