### ISSUE TITLE
[Deployer Whitelisting Request] NiftyTaps

### ISSUE THREAD

**Issue by rashtrakoff** [superfluid-finance/protocol-monorepo#1239]
**Describe the SuperApp:**

NiftyTap allows anyone to distribute, to the holders of an NFT collection, any number of Superfluid token streams. Imagine the creators of an NFT art collection who want to airdrop streams of tokens to their holders or a clever promoter who wants to promote his product by incentivising holders of an NFT collection. Maybe advertise to Lens profile holders or ENS domain holders? There are many more possibilities not even thought of yet!

Anyone who wants to distribute some token using Superfluid constant flows can create a Tap using my smart contract. A tap is responsible for allowing a particular NFT collection's holders with claimable Superfluid streams. These streams are perpetual as long as the tap balance is maintained by the creator (of the tap). A holder can choose to claim any number of streams max up to the number of NFT token IDs they hold. Furthermore, if the holder transfers the NFT corresponding to which he claimed a stream, the new holder is eligible to claim a stream from a tap and the previous holder's streams will be adjusted accordingly.

**Network will be deployed?:**

Polygon Mainnet

**Deployer address:**

`0xDc163db611298E940B524D233687f3b62b7AE29f`

**Factory address:**

`0x27Dcb9caED2Cd91430292916144de0D30D4A01E3`

**Link of repo of the contract to be deployed:**

https://github.com/rashtrakoff/NiftyTaps

**Contact info for developer:**

Discord: rashtrakoff#2547

**Notes:**

These contracts are only for testing or tutorial purposes and are not audited. Sufficient testing has been done but a lot still remains.

**Comment by d10r** [comment]
@hellwolf gov action ready to be signed

**Comment by hellwolf** [comment]
![image](https://user-images.githubusercontent.com/186660/209934181-75c5a0d1-3a86-4a73-af92-21fc3671a7cc.png)

here you go!
