### ISSUE TITLE
[Deployer Whitelisting Request] 

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#1246]
**Describe the SuperApp:**

Automation contracts

**Network will be deployed?:**

eth-mainnet

**Deployer address:**

0xCcA090FD60d405a10b786559933daEEc4e2053Af

**Link of repo of the contract to be deployed:**

https://github.com/superfluid-finance/protocol-monorepo/tree/dev/packages/automation-contracts

**Contact info for developer:**

handover account

**Notes:**

should not expire

**Comment by d10r** [comment]
@hellwolf gov action ready to be signed
expiration date set ~200 years into the future

**Comment by vmichalik** [comment]
@d10r complete?

**Comment by d10r** [comment]
completed
