### ISSUE TITLE
[BOUNTY] Super Token Deployer Interface

### ISSUE THREAD

**Issue by joeljesu** [superfluid-finance/protocol-monorepo#1250]
_To get started working on this bounty, follow these quick steps: https://docs.superfluid.finance/superfluid/resources/bounty-program_ 

## Synopsis
Create a simple UI that lets you deploy a wrapper Super Token for an existing ERC20 token.

## Context
Many people want to easily create wrappers for their Super Tokens but have to go through our docs and often make mistakes.

## Description
See the Super Token deployment process from our docs [HERE](https://docs.superfluid.finance/superfluid/developers/super-tokens/deployment). We want to abstract this into a super simple live UI.

The user flow should be as easy as:
1. Connect wallet
2. Input ERC20 token address 
3. Select appropriate network (should support all networks listed on the docs page)
     - This could just be abstracted such that you auto-detect the network the token address is from!
4. Submit transaction to create wrapper Super Token
5. UI returns the address of the token after deployment and a blockchain explorer link to the deployed token

## Checklist
- [ ] Deployed UI
- [ ] Works for all networks
- [ ] UI successfully works in deploying wrapper super tokens for all networks
- [ ] UI displays the address of the token after deployment
- [ ] Uses createERC20Wrapper parameter logic shown in the docs (things like the token getting auto-named from token symbol to token symbol + "x")

## Bounty reward
- $500 (USDC on Polygon)
- A stream of 10 SUNNYx per month on Polygon from @sunnyjaycer 🌞

All our bounty payouts require a successful light KYC screening. See [Completion info](https://docs.superfluid.finance/superfluid/resources/bounty-program#upon-completion)

**Comment by kobuta23** [comment]
Should we expand this to Pure superTokens as well?

**Comment by 0xSero** [comment]
I'd like to tackle this

**Comment by joeljesu** [comment]
We could @kobuta23, that appears to be a step up in complexity from what I've seen though, so would be worth a separate issue imo

**Comment by joeljesu** [comment]
Completed work: https://github.com/Seroxdesign/deploy-supertoken
