### ISSUE TITLE
[ETHEREUM-CONTRACTS] ERC-777 burn won't work for pure SuperTokens

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#1258]
always invokes downgrade().
should instead just burn if underlying is zero

**Comment by hellwolf** [comment]
Is it still the case?

**Comment by hellwolf** [comment]
This is still a problem.

The expected behaviour should be that when it is a super token without underlying token, the burn function should not call downgrade().

**Comment by 0xdavinchee** [comment]
closing this issue now as the opened PR illustrated that it's more of a semantic bug as discussed in slack [here](https://superfluidhq.slack.com/archives/C04V40RFJQ7/p1695908509404129).
