### ISSUE TITLE
[Deployer Whitelisting Request] BTFDCA

### ISSUE THREAD

**Issue by omnifient** [superfluid-finance/protocol-monorepo#1260]
**Describe the SuperApp:**

BTFDCA is a product where investors can buy crypto assets through (dollar) cost averaging (DCA). Investors stream money through Superfluid CFAs, and get their assets back through a Superfluid IDA.

**Network will be deployed?:**
Polygon Mainnet (for starters)

**Deployer address:**
0x3ee7171FcBEe0FF94889F08b46f1Ca933c142b6E

**Factory address:**
0x058D9860a1a6a745Bd5995C514Ef53E4656946F1

**Link of repo of the contract to be deployed:**
https://github.com/BTFDCA/btfdca-contracts

**Contact info for developer:**
omnifient#7921

**Comment by d10r** [comment]
Thx for the request. Can you please give me access to the linked repo so I can have a quick look?

**Comment by omnifient** [comment]
sent a repo access invite to @d10r and @hellwolf

**Comment by d10r** [comment]
waiting for gov action to be signed...

**Comment by hellwolf** [comment]
![image](https://user-images.githubusercontent.com/186660/214800342-0368dee6-e010-45b7-a6ae-6ea8447b1915.png)


Done. Good luck @omnifient !

**Comment by omnifient** [comment]
thanks!
