### ISSUE TITLE
[Deployer Whitelisting Request]  - Superfluid / PlanetIX

### ISSUE THREAD

**Issue by ngmachado** [superfluid-finance/protocol-monorepo#1268]
**Describe the SuperApp:**

Superfluid integration with PlanetIX

_A clear and concise description of the SuperApp_

SuperApp stream payment processor

**Network will be deployed?:**

Polygon

**Deployer address:**

0xd94E880075AFa8395Fd61Bf47595c878A84e8aDd

**Link of repo of the contract to be deployed:**

https://github.com/ngmachado/superfluid-planetix

**Comment by d10r** [comment]
ready to be signed

**Comment by hellwolf** [comment]
![image](https://user-images.githubusercontent.com/186660/215151146-fc3b47ee-5cf8-4f43-b52e-26655127cef8.png)

Let's go!
