### ISSUE TITLE
[Deployer Whitelisting Request] REX UniswapV3 Market

### ISSUE THREAD

**Issue by mikeghen** [superfluid-finance/protocol-monorepo#1269]
**Describe the SuperApp:**

Ricochet Exchange market contract with UniswapV3 integrations.

**Network will be deployed?:**

- Polygon
- Optimism

**Deployer address:**

0x3226C9EaC0379F04Ba2b1E1e1fcD52ac26309aeA

**Factory address:**

NA

**Link of repo of the contract to be deployed:**

https://github.com/Ricochet-Exchange/ricochet-protocol/blob/v2/contracts/REXUniswapV3Market.sol

**Contact info for developer:**

@mikeghen

**Notes:**

The native token supertoken on the testnets (e.g. MATICx, ETHx) do not behave the same way as their mainnet counterparts. Specifically, the `getUnderlyingToken` method returns `address(0)` rather than the wrapped version on the native token (e.g. WMATIC, WETH).  When `getUnderlyingToken` returns `address(0)` that means its a _native_ supertoken. Right now there's no easy way on testnet to test the network's native token supertoken logic. 

I ran into this trying to test USDCx>>MATICx. To get it to work on testnet I would have to either:
1. Deploy a supertoken that is going to return a value for getUnderlyingToken
2. Add custom logic to futher differential between native token supertoken and just a native supertoken (maybe?)
3. Just don't have a native token market 

Could you pick a WMATIC and WETH testnet contract and deploy MATICx and WETHx to make mainnet and testnet native token supertokens behave the same? I think it would be helpful for everyone doing development on testnet to have these tokens behave the same across networks. I would suggest using whatever WMATIC Uniswap, Comp, or Aave use on the test networks.

**Comment by mikeghen** [comment]
I think my key from before still works, is it OK to use that one again?

**Comment by d10r** [comment]
> I think my key from before still works, is it OK to use that one again?

yes

**Comment by d10r** [comment]
@mikeghen As for the native token wrappers:
We abandoned the attempt to support both the native token and its ERC20 wrapper.
I'd recommend to not use this feature in new code, instead for going from ERC20 wrapper to Supertoken, always batch an unwrap of the ERC20 and a wrap to SuperToken. That way it works on all networks.

**Comment by d10r** [comment]
I guess we can close this. Please reopen if not.

**Comment by mikeghen** [comment]
@d10r is there any expiration on the k1 key? I was just trying to deploy on Polygon in simulation today and its now reverting on me at:
```
            host.registerAppWithKey(_configWord, _registrationKey);
```
inside of the constructor (which hasn't changed):
```
    constructor(
        address _owner,
        ISuperfluid _host,
        IConstantFlowAgreementV1 _cfa,
        IInstantDistributionAgreementV1 _ida,
        string memory _registrationKey,
        IREXReferral _rexReferral,
        address payable _ops,
        address _taskCreator
    ) OpsTaskCreator(_ops, _taskCreator) {
        
        host = _host;
        cfa = _cfa;
        ida = _ida;
        referrals = _rexReferral;

        transferOwnership(_owner);

        uint256 _configWord = SuperAppDefinitions.APP_LEVEL_FINAL;

        if (bytes(_registrationKey).length > 0) {
            host.registerAppWithKey(_configWord, _registrationKey);  // Line that errors
        } else {
            host.registerApp(_configWord);
        }
    }

```
Also, here's the error I get estimating gas, the error reported REXUniswapV3Market.sol:149 is the `host.registerAppWithKey` method call:
```
  Contract deployment: <UnrecognizedContract>
  Transaction:         0xf3a79d09ae1133aa6c20411ed0d5d79595129c431eb8cdbb05e99d8e72864a95
  From:                0x3226c9eac0379f04ba2b1e1e1fcd52ac26309aea
  Value:               0 ETH
  Gas used:            606190 of 10000000
  Block #39437120:     0xbe467ce4cc3569386f3aff41e20d429b62b780d11e4804ed852c104866923218

  console.log:
    Registering with key: k1

  Error: VM Exception while processing transaction: reverted with an unrecognized custom error (return data: 0x19ab84d1)
      at <UnrecognizedContract>.<unknown> (0x3e14dc1b13c488a8d5d310918780c983bd5982e7)
      at <UnrecognizedContract>.<unknown> (0x3e14dc1b13c488a8d5d310918780c983bd5982e7)
      at <UnrecognizedContract>.constructor (unknown)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async HardhatNode._mineBlockWithPendingTxs (/Users/mghen/Documents/Projects/blocksec/ricochet-protocol/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1819:23)
      at async HardhatNode.mineBlock (/Users/mghen/Documents/Projects/blocksec/ricochet-protocol/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:508:16)
      at async EthModule._sendTransactionAndReturnHash (/Users/mghen/Documents/Projects/blocksec/ricochet-protocol/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1522:18)
      at async HardhatNetworkProvider._sendWithLogging (/Users/mghen/Documents/Projects/blocksec/ricochet-protocol/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:144:22)
      at async HardhatNetworkProvider.request (/Users/mghen/Documents/Projects/blocksec/ricochet-protocol/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:121:18)
      at async JsonRpcHandler._handleRequest (/Users/mghen/Documents/Projects/blocksec/ricochet-protocol/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:191:20)
```

**Comment by d10r** [comment]
@mikeghen the key for 0x3226c9eac0379f04ba2b1e1e1fcd52ac26309aea seems to indeed have expired a few days ago.
![image](https://user-images.githubusercontent.com/5479136/219971446-3eac48f2-eb59-42bd-b25a-2d15a235cedb.png)

![image](https://user-images.githubusercontent.com/5479136/219971470-b9fa4489-12f0-4083-9d14-8c389949c481.png)

(can be queried in the gov contract: https://polygonscan.com/address/0x3ad3f7a0965ce6f9358ad5cce86bc2b05f1ee087#readProxyContract)

I created a gov action to renew it, now with a 10 year expiration window.

**Comment by mikeghen** [comment]
@d10r I'm still running into an issue deploying and was wondering if maybe there's an additional action required, I saw on the governance contract that the k1 key is verified, is this something else? 
<img width="1120" alt="Screen Shot 2023-03-01 at 1 36 26 PM" src="https://user-images.githubusercontent.com/5077880/222233381-63bfa715-777c-4cce-adff-1c0b43d18b6e.png">
