### ISSUE TITLE
[ETHEREUM-CONTRACTS] Add option to pass in type of SuperToken in `FoundrySuperfluidTester` constructor

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1272]
## Problem
Recently GoodDollar wanted to create a `PureSuperToken` for their project and wanted to test that their own custom `PureSuperToken` implementation was working as expected using our test suite. From what I understood, this process was a bit complicated. 

## Solution
I think we could iteratively move towards a simpler way of doing this if we allow users to input a ISuperToken and the SuperToken type (Wrapper, Pure, NativeAsset) in the constructor of `FoundrySuperfluidTester`.

1. Add the params then fix our existing tests. 
New experience for someone like GoodDollar: They'd have to go into the specific test files and deploy the SuperToken they want to test and pass this into the `FoundrySuperfluidTester` as well as the type of SuperToken.
We can allow users to pass in an `ISuperToken` with `address(0)` to indicate they want to use the `SuperTokenFactory` deployed SuperToken.

2. Package this for people who want to create custom super tokens so they can be confident their implementation works with the different pieces of the framework. "Baseline tests"

3. (Discussed before already) Add a set of baseline (property/invariant) tests for SuperApps similar to what we've done above.

**Comment by hellwolf** [comment]
wa bout this one?

**Comment by 0xdavinchee** [comment]
this can be closed given the new tester-we are doing it in a different way
