### ISSUE TITLE
[Deployer Whitelisting Request] Ricochet Exchange on Optimism

### ISSUE THREAD

**Issue by mikeghen** [superfluid-finance/protocol-monorepo#1286]
**Describe the SuperApp:**

Ricochet Exchange

**Network will be deployed?:**

Optimism

**Deployer address:**

0x3226C9EaC0379F04Ba2b1E1e1fcD52ac26309aeA

**Factory address:**

NA

**Link of repo of the contract to be deployed:**

https://github.com/Ricochet-Exchange/ricochet-protocol

**Contact info for developer:**

@mikeghen

**Notes:**

I need a key to get contracts onto my Tenderly fork of Optimism. Let me know if there's any problem getting me a key for Optimism for simulation purposes. The contracts are mostly done except the gelato integration.

**Comment by d10r** [comment]
ready to be signed by gov

**Comment by mikeghen** [comment]
@hellwolf @d10r thanks again for taking a look at this 👍

**Comment by mikeghen** [comment]
@hellwolf @d10r, let me know if there's anything you need from me to issue the registration key

**Comment by hellwolf** [comment]
![image](https://user-images.githubusercontent.com/186660/220785182-0f2c5665-977f-496f-a507-12e5be049580.png)

Sorry @mikeghen for the delay, now it's done.

**Comment by hellwolf** [comment]
![image](https://user-images.githubusercontent.com/186660/220785612-677c006b-1c36-40d5-b596-31ef01a72476.png)

@mikeghen here you go!

**Comment by mikeghen** [comment]
Awesome! thanks @hellwolf @d10r
