### ISSUE TITLE
Release ethereum-contracts 1.5.2

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#1287]
This release 1.5.1 is a necessary step stone for releasing ERC20x, due to a breaking change to the SuperToken upgrade process.

## TODO

- [x] Update changelog.
- [x] Publishing new package.
- [ ] Upgrade All SuperToken logic contracts to 1.5.2.
  - We should do fork testing using foundry this time.

**Comment by hellwolf** [comment]
^-- Update, all networks except CELO now is 1.5.2!

**Comment by d10r** [comment]
new gov action for CELO ready

**Comment by hellwolf** [comment]
![image.png](https://images.zenhubusercontent.com/5b03f80a4b5806bc2bd41e43/454781a5-5088-4297-863b-f80fe49de23b)

CELO done
