### ISSUE TITLE
[Deployer Whitelisting Request] 

### ISSUE THREAD

**Issue by phydy** [superfluid-finance/protocol-monorepo#1294]
**Describe the SuperApp:**

_A clear and concise description of the SuperApp_

**Network will be deployed?:**
Gnosis
**Deployer address:**
0xaC18157FFFdc96C9724eB1CF42eb05F8f70e645B
**Factory address:**

**Link of repo of the contract to be deployed:**
https://github.com/phydy/SalaryBonds
**Contact info for developer:**
mphidel@gmail.com
**Notes:**
Deploying for WavePool#6

**Comment by philipandersson** [comment]
@phydy Is this still requested?

**Comment by hellwolf** [comment]
Closing for now until further notice.
