### ISSUE TITLE
[ETHEREUM-CONTRACTS] balanceOf inactiveAgreements optimization

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1321]
First brought up publicly in: https://github.com/superfluid-finance/protocol-monorepo/discussions/1284

## Context

`_inactiveAgreementBitmap` variable is used by `getAccountActiveAgreements` which is used by `realtimeBalanceOf`. This would be useful for reducing the gas costs of `realtimeBalanceOf` by reducing the number of agreements that are iterated over in the function.

## Possible Next Steps

1.  See _inactiveAgreementBitmap: https://github.com/superfluid-finance/protocol-monorepo/blob/6220f660cbf9e053aee6b49b5f3c9161ac2351be/packages/ethereum-contracts/contracts/superfluid/SuperfluidToken.sol#L31
2.  We may introduce a agreementActivenessMask to control meaning of the `_inactiveAgreementBitmap
3.  This can be quite complex for managing backward compatibility.

**Comment by hellwolf** [comment]
not worth it.
