### ISSUE TITLE
[ETHEREUM-CONTRACTS] Deploy FlowNFTs to all networks

### ISSUE THREAD

**Issue by vmichalik** [superfluid-finance/protocol-monorepo#1339]
All mainnets and all testnets.

**Comment by philipandersson** [comment]
Currently we have only deployed to one testnet, Mumbai. We are missing the following ones:

- Avalanche Fuji
- Optimism Goerli
- Arbitrum Goerli

**Comment by 0xdavinchee** [comment]
NOTE: when we deploy this to testnets or production, we MUST pass this env variable: `https://nft.superfluid.finance/cfa/v2/getmeta` for `NFT_BASE_URI`,
e.g. `NFT_BASE_URI=https://nft.superfluid.finance/cfa/v2/getmeta`

**Comment by vmichalik** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Protocol-Team-6405e4d5014c0d0036e14f49/issues/superfluid-finance/protocol-monorepo/1339?planning-poker) with Zenhub @0xdavinchee @d10r @ngmachado @philipandersson

**Comment by 0xdavinchee** [comment]
We are ready to go live on mainnets. The FlowNFTs have been deployed on all testnets already and both the contracts and deployment scripts are ready to go now.
The deployment process:
1. Execute dry run on forked testnet
  - Run deploy-framework script to deploy new NFT contracts and upgrade existing contracts
  - Run the verification script to verify that deployment worked as expected
  - Upgrade all super token contracts
  - Run the verification script to verify that deployment worked as expected
2. Execute actual deployment on live mainnets

**Comment by vmichalik** [comment]
Need to make the necessary adjustments for Ethereum Mainnet & communicate the feature matrix by network to DevX for better developer documentation

**Comment by d10r** [comment]
Deployment and verification done on all mainnet except Ethereum (need to modify deploy script to skip NFTs).
Pending gov approval.

Also created a release specific fork testsuite in https://github.com/d10r/sf-test-gov-actions/blob/master/test/Upgrade_1_7.t.sol - not yet run on all networks.

[deployment_log.txt](https://github.com/superfluid-finance/protocol-monorepo/files/11733331/deployment_log.txt)

**Comment by d10r** [comment]
fork test successfully run on all networks. Ready for gov signing.
