### ISSUE TITLE
[ETHEREUM-CONTRACTS] Ensure good OpenSea support

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1349]
Brought up by @vmichalik 

Places to look at:
- https://support.opensea.io/hc/en-us/articles/4403934341907-How-do-I-import-my-contract-automatically-
- https://docs.opensea.io/docs/1-structuring-your-smart-contract
- https://support.opensea.io/hc/en-us/articles/5095272825235-What-NFTs-are-in-the-hidden-tab-in-my-profile-

**Comment by vmichalik** [comment]
Stale
