### ISSUE TITLE
[Deployer Whitelisting Request] Degen Dogs Racing

### ISSUE THREAD

**Issue by abstractpoint** [superfluid-finance/protocol-monorepo#1353]
**Describe the SuperApp:**

Superapp for Degen Dogs Racing game (codename Arena)

**Network will be deployed?:**

Polygon

**Deployer address:**

0x104D64F611aaA3F06F417F8D44F85A76FB44FbE9

**Factory address:**

**Link of repo of the contract to be deployed:**
https://github.com/abstractpoint/degen-dogs-club-racing/blob/main/contracts/contracts/Arena.sol

**Contact info for developer:**

Discord: `georgety#4563`
Twitter: `@georgety`

**Notes:**

Contract for streaming BSCT tokens into the Degen Dogs Racing game. Streamed tokens flow rate provides a boost to player ability, and contract distributes out winning over IDA on a set schedule (Via external call)

**Comment by d10r** [comment]
The registration key for the provided deployer account is "k1".
It will be valid for 10 years (multiple deployments possible).
WOOF!

**Comment by abstractpoint** [comment]
@d10r could you please double check it's on the correct address and Polygon Mainnet, as this contract fails to deploy:
https://github.com/abstractpoint/degen-dogs-club-racing/blob/main/contracts/contracts/base/StreamInDistributeOut.sol#L73

Also another contract failed to deploy using this deployer and keyword. Thank you

**Comment by d10r** [comment]
sorry, forgot that this needs gov confirmation

**Comment by hellwolf** [comment]
![image](https://user-images.githubusercontent.com/186660/233011185-70ba1460-a3f1-47bd-a2e7-fb4976213b1f.png)

sorry for the delay!
