### ISSUE TITLE
[ETHEREUM-CONTRACTS] Consider how to delete/destroy/hide old FlowNFTs

### ISSUE THREAD

**Issue by vmichalik** [superfluid-finance/protocol-monorepo#1359]

**Comment by d10r** [comment]
uh, this on me?

**Comment by d10r** [comment]
Options:
* modify the visual such that it's clearly recognizable as deprecated
* create an off-chain hook which burns tokens when streams are closed (would require us subsidizing the operation)

@vmichalik does that help?

**Comment by vmichalik** [comment]
yes, ultimately I don't think its wise for us to leave "hanging" deprecated NFTs in peoples wallets as spam, so we should aim to remove them
if we don't return anything on our API, do we know if OpenSea stops rendering them? or they don't appear in peoples portfolios at all @d10r

**Comment by vmichalik** [comment]
it seems that OpenSea is flagging our account as spamming or something, so we should pay this special attention
our entire account has been banned

**Comment by vmichalik** [comment]
@d10r @philipandersson 
what would it entail to build this offchain hook for deleting expired original flowNFTs?

**Comment by philipandersson** [comment]
@d10r Do we have permission to delete/burn expired original NFTs?
