### ISSUE TITLE
Add metadata to monorepo and make it an npm package

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#1366]

**Comment by kasparkallas** [comment]
Is monorepo a good idea? Adds overhead.

**Comment by hellwolf** [comment]
https://github.com/superfluid-finance/protocol-monorepo/pull/1498

This can make metadata auto release easy, workflow will be:

- make changes to metadata,
- bump metadata version,
- pull request,
- merge to dev,
- auto release metadata upon detecting the version difference.
