### ISSUE TITLE
[ETHEREUM-CONTRACTS] Include actionlint in `lint:github-workflows` instead

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#1376]
## Notes

Currently it is part of https://github.com/superfluid-finance/protocol-monorepo/blob/dev/.github/workflows/ci.lint-workflow-files.yml

We could make it part of the root package.json lint:github-workflows  step.

Applying a similar status as tasks/shellcheck-all-tasks.sh where installing of the actionlint is optional in your local developoment environment, but CI will tell you if you are behaving bad.

It's available in nixpkgs https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=actionlint

**Comment by 0xdavinchee** [comment]
done, addressed here: https://github.com/superfluid-finance/protocol-monorepo/issues/1390
