### ISSUE TITLE
[SUBGRAPH] Add a new entity aggregating ERC-20 Allowance and Superfluid ACL for Super Tokens

### ISSUE THREAD

**Issue by kasparkallas** [superfluid-finance/protocol-monorepo#1382]
# Improve Readability of Super Tokens Access Settings

## Background
Currently, on-chain security access for Super Tokens is managed using [ERC-20 Allowance](https://academy.bit2me.com/en/what-is-token-allowance/) and [Superfluid ACL](https://docs.superfluid.finance/superfluid/developers/constant-flow-agreement-cfa/cfa-access-control-list-acl).

## Problem
Efficiently inspecting the latest state of access settings for Super Tokens is challenging, as it involves making multiple RPC calls to different endpoints and aggregating the latest state based on numerous events. This process is cumbersome and impractical when displaying a list in the UI. Potentially for multiple networks at the same time.

## Proposed Solution
To simplify and streamline this process, we suggest implementing Subgraph indexing, which will make querying the necessary data much more efficient.

### Example Schema
```graphql
query AccountAccessSettings {
    flowOperators(where: { sender: "0x..." }) {
        token
        operator
        allowance
        flowRateAllowanceRemaining
        permissions
    }
}
```
NOTE: This returns an array of entities.

### Events Involved
* Approve (ERC-20)  <-- Might create the entity.
* ~~Transfer (ERC-20)~~ <-- Transfer event does not need special handling because ` transferFrom` always fires Approve event as well.
* FlowOperatorUpdated (CFA) <-- Might create the entity.
* FlowUpdated (CFA)

### Entity ID
{token}-{account}-{operator}

## Other Information
* For ERC-20 allowance, [Revoke.cash](https://revoke.cash/) is commonly used.
* Subgraph already has `FlowOperator` entity which we can use.
* Might consider renaming "FlowOperator" to something else to clarify that it's not just ACL Flow Operator related entity anymore.

**Comment by vmichalik** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Protocol-Team-6405e4d5014c0d0036e14f49/issues/superfluid-finance/protocol-monorepo/1382?planning-poker) with Zenhub @msoni89

**Comment by msoni89** [comment]
As discussed, we do not need to create a new separate entity. Instead, we can reuse the existing entity **FlowOperator** by adding one more field, "**allowance**."

Additionally, a new event called "**Approval**" needs to be added. Upon reviewing the code, it was found that **_transferFrom**, **approve**, **increaseAllowance**, and **decreaseAllowance** all emit an event with the settled amount.

**Comment by msoni89** [comment]
![image](https://user-images.githubusercontent.com/65469737/236767224-40ae1f35-b50a-4755-8f8e-52d37ea6f837.png)

![image](https://user-images.githubusercontent.com/65469737/236767257-09c913a3-6d41-4f4c-9b48-d0e75ff80059.png)


Polygon showing similar results with revoke cash.

**Comment by vmichalik** [comment]
@msoni89 is this complete?

**Comment by msoni89** [comment]
@vmichalik 

Yes, the deployment (v1 and dev) was completed, and we can close this ticket.
