### ISSUE TITLE
[BUG] Repo is deprecated...

### ISSUE THREAD

**Issue by fulldecent** [superfluid-finance/protocol-monorepo#1383]
If protocol-monorepo is deprecated, please archive it.

Maybe what is meant is that this package is deprecated, if so please say that.

<img width="1531" alt="Screenshot 2023-04-30 at 21 40 34" src="https://user-images.githubusercontent.com/382183/235388844-3f1efd9a-8663-4c80-b9b3-17a8cae094dd.png">

**Comment by hellwolf** [comment]
Yes, thanks for the feedback, will be fixed. You may also submit such README change directly too via github interface.
