### ISSUE TITLE
[DOCS] Show deployment addresses

### ISSUE THREAD

**Issue by fulldecent** [superfluid-finance/protocol-monorepo#1384]
In README, and maybe the GitHub Releases, and the project homepage, please document which are the official deployed Superfluid smart contracts.

**Comment by fulldecent** [comment]
Actually none of the documentation anywhere seems to have it.

(But even if it was buried somewhere it should be in ALL of the places mentioned above.)

**Comment by hellwolf** [comment]
They are documented here: https://docs.superfluid.finance/superfluid/developers/networks

Apparently it wasn't easy for you to find from github alone, I will see what can be done. Generally speaking, this repo is a open source implementation published for super token, so it should not concern with the actual deployment. But a reference to the actual deployments of course can be mentioned at least.
