### ISSUE TITLE
[BUG] Undisclosed admin accounts?

### ISSUE THREAD

**Issue by fulldecent** [superfluid-finance/protocol-monorepo#1385]
It seems like there are three [administrator accounts](https://etherscan.io/address/0x5F374f5f5E1EDD5401BdA5D2EBfDbf8e1fBf71f6#readContract) in the system:

0xd15D5d0f5b1b56A4daEF75CfE108Cb825E97d015
0x568658Dd13A880fF8418Efe194004019A675955F
0x5eb449B88Ff8f03cD0C736A72ac70B76258E4B10

At a quick glance it looks like they have full access to [replace the implementation](https://etherscan.io/address/0xe2E14e2C4518cB06c32Cd0818B4C01f53E1Ba653#readProxyContract) of the governance contract, then update [application code](https://goerli.etherscan.io/address/0x7024ae6f8482610aa5ce97c94ff364a26b7be456#readContract).

Could this please be explained further? If these accounts can update the application code, can they take all the underlying unwrapped tokens (e.g. everybody's Ether)?

**Comment by hellwolf** [comment]
You may find some explanation at: https://github.com/superfluid-finance/protocol-monorepo/wiki/Governance-Overview

I will review them to see what can be done to make it more visible.

**Comment by hellwolf** [comment]
May I ask are you looking for anything specific, or building anything? We have a support team that can help what you need.

**Comment by fulldecent** [comment]
Thank you, I see these are the "caretakers".

Could you please say if there is some path possible where these caretakers are able to take other people's tokens?

---

I am studying up on this and a few project in advance of ETH Tallinn.

**Comment by hellwolf** [comment]
> I am studying up on this and a few project in advance of ETH Tallinn.

Cool, talk to you in person soon then. I realized eventually it was you reporting the issue :)

**Comment by vmichalik** [comment]
Closing as the question has been addressed
