### ISSUE TITLE
Sentinel Community Communication

### ISSUE THREAD

**Issue by ngmachado** [superfluid-finance/protocol-monorepo#1388]

**Comment by ngmachado** [comment]
Once [PR #214](https://github.com/superfluid-finance/superfluid-sentinel/pull/214) is merged, we should take the opportunity to engage with the Sentinel community and provide a clear explanation of our vision and the new features related to Dust Streams.

The following points should be addressed:

- Define and explain the concept of Dust Streams and their insignificance to solvency as a whole.
- Provide a clear explanation of insolvency and its implications. This will help users better understand the data displayed on our dashboard, TOGA, Solvency, and other related aspects, as well as comprehend why some streams continue to run when they should be closed.

**Comment by vmichalik** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Protocol-Team-6405e4d5014c0d0036e14f49/issues/superfluid-finance/protocol-monorepo/1388?planning-poker) with Zenhub @0xdavinchee @d10r @ngmachado @philipandersson

**Comment by hellwolf** [comment]
send this ticket to limbo
