### ISSUE TITLE
[SUBGRAPH BUG] Querying flowOperator senders throws non-null field errors

### ISSUE THREAD

**Issue by elvijsTDL** [superfluid-finance/protocol-monorepo#1397]
**Describe the bug:**
Unable to query flowOperator senders

**Subgraph endpoint:** [protocol-v1-goerli](https://thegraph.com/hosted-service/subgraph/superfluid-finance/protocol-v1-goerli)

**Query:**
```
{
  flowOperators {
    sender {
      id
    }
  }
}
```

**Expected data:**
Was expecting to see the senders 

**Actual data:**
Null errors are thrown, very sad
```
{
  "errors": [
    {
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "message": "Null value resolved for non-null field `sender`"
    },
```

**Additional context:**
Also happens in the latest dev deployment where allowance field was added
![image](https://github.com/superfluid-finance/protocol-monorepo/assets/77115130/ce8c38b8-ef3c-4e51-8ff1-2ac2fd0fe298)

**Comment by msoni89** [comment]
same behaviour for accountTokenSnapshot field

**Comment by msoni89** [comment]
![image](https://github.com/superfluid-finance/protocol-monorepo/assets/65469737/6aa86d6b-7e69-4a53-b8b1-2077a91e1c45)


@elvijsTDL Its working for Goerli, but another network still syncing
