### ISSUE TITLE
release sdk-core 0.6.5

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1405]

**Comment by raymondfeng** [comment]
Please publish 0.6.5 to npm ASAP. It broke our system as the `@superfluid-finance/sdk-core` fails to load. Thanks!

**Comment by raymondfeng** [comment]
The hard dependency at https://github.com/superfluid-finance/protocol-monorepo/blob/dev/packages/sdk-core/package.json#L60 cannot be overridden by `npm`. There is no workaround for the issue.
