### ISSUE TITLE
GDA coverage @ 100%

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1408]
Currently at ~80%

**Comment by philipandersson** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Protocol-Team-6405e4d5014c0d0036e14f49/issues/superfluid-finance/protocol-monorepo/1408?planning-poker) with Zenhub @0xdavinchee

**Comment by philipandersson** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Protocol-Team-6405e4d5014c0d0036e14f49/issues/superfluid-finance/protocol-monorepo/1408?planning-poker) with Zenhub @philipandersson @kasparkallas @elvijsTDL @Mikkoun

**Comment by hellwolf** [comment]
https://app.codecov.io/gh/superfluid-finance/protocol-monorepo/tree/gda/packages%2Fethereum-contracts%2Fcontracts%2Fsuperfluid

![image.png](https://images.zenhubusercontent.com/5b03f80a4b5806bc2bd41e43/7f31f414-a9cd-4809-8eec-552e5fd34d21)

yes
