### ISSUE TITLE
[BUG] Missing SuperTokenFactory Error Code

### ISSUE THREAD

**Issue by tomasp1189** [superfluid-finance/protocol-monorepo#1411]
**Describe the bug:**
While interacting with the SuperTokenFactory deployed in Polygon I noticed that I got an Error code that wasn't documented in the ISuperTokenFactory file.
CODE: `0xc4901a43`
I also noticed that the error code for `SUPER_TOKEN_FACTORY_ONLY_HOST` and `SUPER_TOKEN_FACTORY_NON_UPGRADEABLE_IS_DEPRECATED` is the same: `0x478b8e83`

**Environment:**

- **Desktop (please complete the following information):**
  - Device:  Macbook Pro M1
  - OS: iOS
  - Hardhat Project
  - Hardhat Version: ^2.12.3

**Steps To Reproduce:**
1. Call `createERC20Wrapper(address,uint8,string,string)` on SuperTokenFactory with the following arguments `[ '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174', 0, "Super USDC", "USDCb"]`

**Expected behavior:**
I would expect to have a SuperToken created or getting a valid ErrorCode.

**Actual behavior:**
I got a ErrorCode that wasn't present in the Superfluid codebase: `0xc4901a43`.

**Screenshots:**
<img width="865" alt="image" src="https://github.com/superfluid-finance/protocol-monorepo/assets/22004408/ee3ac15b-c081-4597-a08f-752877bb7ca7">

![image](https://github.com/superfluid-finance/protocol-monorepo/assets/22004408/6fa62913-151a-4878-8252-9b1254209414)

**Additional context:**
I'm running integration tests and need to create an ERC20Wrapper.
- Network: Polygon 
- SuperTokenFactory address: 0x2C90719f25B10Fc5646c82DA3240C76Fa5BcCF34
- Fork Block Number: 42770914

**Comment by hellwolf** [comment]
Thanks for reporting,  a fix is on the way!
