### ISSUE TITLE
[INFRA] zkEVM testnet deployment

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#1425]
A protocol deployment was done, RESOLVER_ADDRESS=0x642332562BC60a4Bd9681E7bb1588f7456A497aC (check if test or v1, not sure)

context: https://www.notion.so/superfluidhq/Protocol-Sprint-Planning-f452c17ca8934dcf8b9ae6c6734bc3e1?pvs=4#ff86b9ee45df48acadcdd3d52966c4b4

# Acceptance criteria
- [x] Investigate running our own RPC
- [x] Find out which suppliers we want to select RPC services (e.g. Alchemy)
- [x] Investigate deploying a subgraph Polygon zkEVM testnet
- [x] Add zkEVM testnet to metadata
- [x] Add SDK-Core Support for zkEVM testnet
- [x] Setup sentinels on zkEVM testnet

**Comment by vmichalik** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Protocol-Team-6405e4d5014c0d0036e14f49/issues/superfluid-finance/protocol-monorepo/1425?planning-poker) with Zenhub @0xdavinchee @d10r @ngmachado @philipandersson

**Comment by d10r** [comment]
fallback RPC available at Alchemy.

subgraph available at canonical endpoint https://zkevm-testnet.subgraph.x.superfluid.dev, self-hosted (TBD: include in workflows for auto-update).

not 100% sure it's auto-added to sdk-core through metadata dependecy update in the protocol-monorepo, but I think so.
