### ISSUE TITLE
[SPIKE] L1->L2 catapult with Safes for 1inch

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#1426]
context: https://www.notion.so/superfluidhq/SnapSafe-Reality-eth-Superfluid-683219e34d3141859e1fe84ae36a9d30

Challenges:
1. Contract: Specify and implement the custom contract needed on L2
2. Encoding: Figure out the encoded calldata to be provided in the L1 transaction
3. Testing: Find out how to test this

**Comment by d10r** [comment]
Valuable feedback from a Gnosis Guild guy (Discord, private channel with SF):

![image.png](https://images.zenhubusercontent.com/63527374822bb7b58064e166/d6a3acec-18f1-4ed1-b337-dc583f697e48)

**Comment by d10r** [comment]
They have a Safe on both sides. The [Zodiac Modules](https://github.com/gnosis/zodiac) get in handy.
On L1, it listens to gov decisions via [Zodiac Reality Module](https://github.com/gnosis/zodiac-module-reality/) (former [SafeSnap](https://docs.snapshot.org/user-guides/plugins/safesnap-reality) afaik). This module consumes EIP-712 messages.
On L2, the Safe owns tokens. This Safe could receive bridge messages - [AMB](https://docs.tokenbridge.net/amb-bridge/about-amb-bridge) msgs through the [Zodiac Bridge Module](https://github.com/gnosis/zodiac-module-bridge) or [Connext xApps](https://docs.connext.network/developers/intro) msgs through the [Zodiac Connext Module](https://github.com/gnosis/zodiac-module-connext).
In both cases, arbitrary calldata to be executed on the receiving chain is supported.

How this task could be broken down:
* create contract implementing the operations to be done on L2. Provide a function `execute()` which takes the needed parameters and executes the operations.
* call this `execute()` via xcall from another chain
* encode the operations as a batch call to be executed by the L2 Safe and test it
* provide the same via xcall from another chain
* send the same via L1 Safe
* encode that L1 call as EIP-712 message for SafeSnap

**Comment by d10r** [comment]
code to do upgrade and create or update flow in 1 tx:
```
        ISuperfluid.Operation[] memory ops = new ISuperfluid.Operation[](2);

        ops[0] = ISuperfluid.Operation({
            operationType: BatchOperation.OPERATION_TYPE_SUPERTOKEN_UPGRADE,
            target: address(superToken),
            data: abi.encode(amount)
        });

        ops[1] = ISuperfluid.Operation({
            operationType: BatchOperation.OPERATION_TYPE_SUPERFLUID_CALL_AGREEMENT,
            target: address(cfa),
            data: abi.encode(
                abi.encodeCall(
                    oldFlowRate > 0 ? cfa.createFlow : cfa.createFlow,
                    (
                        superToken,
                        receiver,
                        flowRate,
                        new bytes(0) // placeholder
                    )
                ),
                "0x" // userData
            )
        });

        host.batchCall(ops);
```

Unfortunately we have no createOrUpdate flow, so I think there's no safe way to batch this - safe in the sense that we know for sure the call will succeed.
So we probably indeed need to use [multicall](https://github.com/mds1/multicall) as suggested. Would have the advantage that it can include the ERC20 approval. And I think we could give it both createFlow and updateFlow, accepting that one of them will fail.

**Comment by d10r** [comment]
Works with multicall:
```
    // Get the calldata to be sent as delegatecall to the Multicall contract
    function getMulticall3Calldata(address multicallAddr, address cfaFwd, IERC20 erc20, ISuperToken superToken, uint256 amount, address receiver, int96 flowRate) 
        public pure returns(bytes memory)
    {
        IMulticall3 mc3 = IMulticall3(multicallAddr);
        IMulticall3.Call3[] memory calls = new IMulticall3.Call3[](3);
        calls[0] = IMulticall3.Call3(address(erc20), false, abi.encodeWithSignature("approve(address,uint256)", address(superToken), amount));
        calls[1] = IMulticall3.Call3(address(superToken), false, abi.encodeWithSignature("upgrade(uint256)", amount));
        calls[2] = IMulticall3.Call3(
            address(cfaFwd), 
            false, 
            abi.encodeWithSignature("setFlowrate(address,address,int96)", address(superToken), receiver, flowRate)
        );

        return abi.encodeCall(mc3.aggregate3, calls);
    }

    // To be executed by the contract holding the funds - doesn't have to be the same having the calldata getter
    function executeDelegateMulticall(address target, bytes memory data) public returns(bool, bytes memory) {
        return target.delegatecall(data);
    }
```
(The `false` argument set per sub-call flags the operation as not allowed to fail.)

That way we can include the erc20 approval and use the cfa forwarder to have the semantics of createOrUpdateFlow.

Next: bridging

**Comment by philipandersson** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Protocol-Team-6405e4d5014c0d0036e14f49/issues/superfluid-finance/protocol-monorepo/1426?planning-poker) with Zenhub @d10r

**Comment by d10r** [comment]
Deployed a zodiac connext module on goerli:
```
didi@P1G4:~/src/sf/zodiac-module-connext$ ANY_PROVIDER_URL=https://eth-goerli.... npx hardhat --network any setup --avatar 0x18A6dBAA09317C352CAd15F03A13F1f38862d124 --connext 0xFCa08024A6D4bCc87275b1E4A1E22B71fAD7f649 --origin 9991 --owner 0x30B125d5Fc58c1b8E3cCB2F1C71a1Cc847f024eE --sender 0x30B125d5Fc58c1b8E3cCB2F1C71a1Cc847f024eE --target 0x18A6dBAA09317C352CAd15F03A13F1f38862d124
Deploying Connext Module
Connext Module deployed to: 0x777EB1f42f933Bd3887A5C440634e01a37D0649F
```

A simluated tx works:
```
        bytes memory data = catapultL2.getMulticall3Calldata(MULTICALL, address(cfaFwd), erc20, superToken, amount, receiver, flowRate);

        bytes memory dataForSafe = abi.encode(
            MULTICALL, 
            0, 
            data, // new bytes(0), //data, 
            Enum.Operation.DelegateCall
        );

        vm.startPrank(CONNEXT);
        // bytes32 _transferId, uint256 _amount, address _asset, address _originSender, uint32 _origin, bytes memory _callData) external returns (bytes memory);
        bytes memory ret = xr.xReceive(
            keccak256("randomid"),
            0,
            address(erc20),
            ORIGINSENDER,
            ORIGIN,
            dataForSafe //new bytes(0)
        );
        vm.stopPrank();
```

Next: trigger a real bridging tx from mumbai

**Comment by d10r** [comment]
Several bridging txs attempted now. Last one: https://testnet.connextscan.io/tx/0x9008b983f11fabfe178d3a1ab3559e92a036cba7a882052020b39efd787f3b8c

Lessons learned along the way:
* takes quite long for the receiving tx to be executed (in the order of 1h) - this is when no "boost liquidity" is available
* bridging from mumbai to goerli is quite "expensive", costs in the order of 50 MATIC
* not many chain pairs available where we have both Connext and Safe
* on the receiving end, we need either a contract target in order to use multicall, or use the SF batching facility for EOA

To be done: figure out good values for relayer fee and handling of fee too low, see
see https://docs.connext.network/developers/guides/estimating-fees#bumping-relayer-fees

Next: simple Dapp which does such bridge txs.
May require a simple backend acting as relayer, e.g for deploying a module contract.

**Comment by d10r** [comment]
bridging a stable between mainnets should be faster due to "boost liquidity".
Next: send from Polygon to Gnosis chain.

* set up Safe on Gnosis: 0x8b72430DEBD7994B269eB401230799eC9A1F24bc
* set up Zodiac module on Gnosis: 0xee07D9fce4Cf2a891BC979E9d365929506C2982f
* test bridging action from Polygon to Gnosis: https://connextscan.io/tx/0x311eaa8b0d9ba3feb9f679496e8b2959038a54c56efcf1d364e8681de3d4a9e1

next: 
* dapp for deploying the zodiac module
* dapp for doing the L1 tx

**Comment by philipandersson** [comment]
@d10r this seems like an epic. Could we create new issues for the the two dapps?

**Comment by d10r** [comment]
Dapps added to https://github.com/d10r/catapult

Bridging operation done form Polygon to Gnosis:
* https://connextscan.io/tx/0xd3acda431414aa8b986893019acd16dc9384640c0576d6c9bfc0355bfdc19550
* target tx: https://gnosisscan.io/tx/0xf37a025d305230b2cc661b056ddb9068bd40eaea7cce4ab4ebeec31fdb6d9291
* stream created: https://console.superfluid.finance/xdai/streams/0x8b72430debd7994b269eb401230799ec9a1f24bc-0x209b6ff4616152187d752eca6efafdc6e873c48a-0x1234756ccf0660e866305289267211823ae86eec-0.0

**Comment by d10r** [comment]
conclusions after conversation with Fran:
* the process as described in the [Readme](https://github.com/d10r/catapult#readme) is intimidating
* priority now: explain to Amin & Mike how this works, so they understand whom it can be useful for
* for initial users, we can provide live support with the setup e.g. via screen sharing instead of providing a good-enough self-service solution

Ways we can simplify a self-service solution:
* Split into 2 processes: initial setup, doing a catapult tx
* Further reduce form fields, e.g. addresses of the L2 ERC20 and SuperToken could be auto-determined, [relayer fee could be queried via connext sdk](https://docs.connext.network/developers/guides/estimating-fees)
* abstract away module deployment by using something like a meta-tx happening in the background
* avoid reliance on the Safe Zodiac UI for enabling a module by letting our Dapp create the tx (or even meta-tx) for that

Ways we can reduce potential for user error:
* make it a less barebone UI with the related improvements like basic form field validation
* do all the correctness checks we can do upfront, e.g. make sure the flowrate provided is suitable for the amount being bridged, probe all addresses provided (e.g. is there a Safe at a provided Safe address?)
* provide a status UI for past catapult txs, showing the status of the bridge tx (as it can take several hours to complete) and of the stream once created
* provide notifications for stream status, e.g. getting close to liquidation

update:
[Connext Chain Abstraction](https://docs.connext.network/developers/guides/chain-abstraction) may be useful for a next iteration focusing on UX
