### ISSUE TITLE
SuperfluidFrameworkDeployer ergonomic problems

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1430]
## Purpose
1. Reduce as much friction as possible to get from 0 to Superfluid deployed in a local test environment (including local blockchains such as anvil, hardhat node and ganache).
2. Add some more customization via configuration.
3. Make the deployer more modular by explicitly splitting different parts of the deployment based on category.

See [here](https://hackmd.io/@0xdavinchee/B1v5TZfLn) for a more in-depth spike based on Axe's comments below.

**Comment by ngmachado** [comment]
I think this can be useful to define by stages. Here is my take

#1 :
- Define the deployment stages (core, peripherals, super tokens) clearly.
- Identify dependencies between these phases and set the order of deployment (don't forget EIP-1820)
- Identify the required configuration parameters for the Deployer. (DevX should be part of this discussion)
- Design and develop the methods to pass configurations via environment variables or constructors.
- Test these methods in isolated environments.

#2:
- Refactor the Deployer to implement this configuration passing method.
- Test the Deployer in a development environment.
- Review scope after dev environment.

#3:
- Expand tests to multi blockchain environment: Foundry, Anvil, Fork Networks.

#4:
- Collect feedback internally and externally if possible and implement or deploy fixes as necessary.

**Comment by d10r** [comment]
would be nice to have a visualization of contracts and their dependencies, that would likely help to identify possible deployment "sizes" scenarios.
E.g. the smallest one could be only core contracts, no TOGA, forwarder etc., the largest one could include test tokens, toga, batcher, automation contracts, ...

The mental model could be that of a core + possible extensions, where extensions may have dependencies between each other or even be extensions to another extension. Lego.

Can AI do this?
(just to trigger Miao in case he's reading)

**Comment by 0xdavinchee** [comment]
@d10r this is a manually done visualization of the different contracts and its dependencies: https://whimsical.com/deploy-framework-T2fnBquVLFDJrts8TR1rqf

There are other tools such as https://github.com/NomicFoundation/ignition which create this dependency graph once you write out the deployments.

**Comment by philipandersson** [comment]
@saflamini @sunnyjaycer Would love your feedback here. Please let us know what you think.

**Comment by vmichalik** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Protocol-Team-6405e4d5014c0d0036e14f49/issues/superfluid-finance/protocol-monorepo/1430?planning-poker) with Zenhub @0xdavinchee @d10r @ngmachado @philipandersson

**Comment by 0xdavinchee** [comment]
A spike: https://hackmd.io/@0xdavinchee/B1v5TZfLn

**Comment by 0xdavinchee** [comment]
this can be closed given https://github.com/superfluid-finance/protocol-monorepo/pull/1447 and 1.7.0 release
