### ISSUE TITLE
[INFRA] BASE testnet deployment

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#1431]
Get a minimum deployment ready:
* protocol v1 deployed with test tokens
* faucet (?) - verified ERC20s may be enough
* subgraph available

**Comment by d10r** [comment]
stumbling block:
ERC-1820 isn't yet deployed. Can't deploy with the public RPC bcs it doesn't allow non-ERC-155 txs.
Had this before on other networks. Usually eventually it gets done, bcs other protocols need it to.

2 options forward:
1  deploy our own node and configure it to allow non-ERC155 txs
2  get in touch with somebody technical enough at Base to do the deployment themselves

@philipandersson is 2 an option?

**Comment by d10r** [comment]
have a node syncing on buck-2 in the meantime. Could be set up in ~10 mins. But syncing will take a few hours or days.

**Comment by philipandersson** [comment]
Let's try the first option if it is not more effort than 10 min. Option 2 is not yet on the table, we are still searching for a connection there. Thanks @d10r !

**Comment by philipandersson** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Protocol-Team-6405e4d5014c0d0036e14f49/issues/superfluid-finance/protocol-monorepo/1431?planning-poker) with Zenhub @d10r

**Comment by d10r** [comment]
node synced, but even when running it with `--rpc.allow-unprotected-txs=true`, it won't allow non-EIP-155 txs, likely a sequencer level restriction.
Created an issue: https://github.com/base-org/node/issues/53

**Comment by philipandersson** [comment]
@d10r Please add the addresses to the contracts here.

**Comment by d10r** [comment]
addresses in https://github.com/superfluid-finance/metadata/pull/46

**Comment by d10r** [comment]
PR for adding to monorepo: https://github.com/superfluid-finance/protocol-monorepo/pull/1449
