### ISSUE TITLE
[PROTOCOL-OPS] How to improve deployment scripts

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#1432]
Goal: figure out what changes would be most useful and are most feasible given our resources.

**Comment by d10r** [comment]
My braindump:

* get rid of excess RPC requests (this could I think also be done with a pretty simple hack of overriding web3.currentProvider.send with a custom function - see [example](https://github.com/superfluid-finance/solvency-helpers/blob/master/solvency-checker.js#L123))
* make it resumable (a mechanism similar to how the resolver works, but persisting to a local file instead of on-chain) - needs some reasoning about how to identify runs which belong to each other, e.g. via fingerprinting of the artifacts
* simplify the code (and/or make it types such that it becomes easier to read & navigate with the help of IDEs)
* use metadata in order to simplify adding networks

**Comment by 0xdavinchee** [comment]
> get rid of excess RPC requests (this could I think also be done with a pretty simple hack of overriding web3.currentProvider.send with a custom function - see [example](https://github.com/superfluid-finance/solvency-helpers/blob/master/solvency-checker.js#L123))

We can utilize newer tools and libraries for this.

> make it resumable (a mechanism similar to how the resolver works, but persisting to a local file instead of on-chain) - needs some reasoning about how to identify runs which belong to each other, e.g. via fingerprinting of the artifacts

It is best to use existing tooling which supports this, see https://www.npmjs.com/package/hardhat-deploy#1-hardhat-deploy 

> simplify the code (and/or make it types such that it becomes easier to read & navigate with the help of IDEs)

YES!

> use metadata in order to simplify adding networks

💯  instead of getConfig.

**Comment by 0xdavinchee** [comment]
In addition to this, we should also have some deployment tests that run against forked networks for our workflows. This will provide extra confidence that things are working each time we push.
These tests could be used when we do a dry run locally and prior to a real deployment.
