### ISSUE TITLE
[SPIKE] connext bridgeable SuperToken

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#1436]
Had a meeting with Fran and Markus about updating FRACTION and MIVA to a SuperToken logic which allows mint&burn by the Connext bridge.
Conclusion: we build such a variant in https://github.com/superfluid-finance/custom-supertokens, deploy a copy of it and upgrade the mentioned SuperTokens to that logic.
Also think about how this tokens can be safely excluded from future SuperToken upgrade runs.

context:
* https://docs.connext.network/developers/intro
* https://github.com/connext/xapp-starter
* https://github.com/connext/monorepo/blob/main/packages/deployments/contracts/contracts/core/connext/interfaces/IBridgeToken.sol

**Comment by hellwolf** [comment]
@d10r please post the "secession fork testing"  related work here.

After that, the owner of token that wish to secede should create an issue in this repo to request such governance action.


Technical challenges:

- "flag changes"
- "nullifcation" process
- etc.

**Comment by d10r** [comment]
fork test: https://github.com/superfluid-finance/custom-supertokens/blob/bridged-supertoken/test/foundry/BridgedSuperToken.t.sol#L80

Technical challenge with a seceding token:
There's no explicit role assigned to the upgrade privilege, the way it is in e.g. [Ownable](https://docs.openzeppelin.com/contracts/4.x/api/access#Ownable). Instead, the role is implicitly defined by the _implementation_ contract through the logic of `updateCode`.  
In case of the canonical SuperToken contract, the restriction is that [only the host](https://github.com/superfluid-finance/protocol-monorepo/blob/dev/packages/ethereum-contracts/contracts/superfluid/SuperToken.sol#L150) can trigger the update. The host contract can trigger this through [updateSuperTokenLogic](https://github.com/superfluid-finance/protocol-monorepo/blob/dev/packages/ethereum-contracts/contracts/superfluid/Superfluid.sol#L295C14-L295C35) which can be called by gov only.  
So through this indirections, SF gov has exclusive permission to update SuperTokens, but that's not something which can trivially be queried. The best way to check this may be to verify if the logic a SuperToken points to is the canonical one (as defined by `SuperTokenFactory.getSuperTokenLogic()`) - caveat being that one would have to keep track of all previous versions of canonical logics, or rely on the assumption that all tokens are always updated to the latest one.  
In order to facilitate that, we could add a `mapping(address => bool) canonicalSuperTokenLogicContracts` which returns `true` for all contracts which ever were (or currently are) the canonical SuperToken implementation.  
Alternatively we could rely on off-chain reconstruction, e.g. based on the event `SuperTokenFactory.SuperTokenLogicCreated`.

An alternative approach for distinguishing SuperTokens using the canonical logic could be to use `UUPSProxiable.proxiableUUID` - assuming only the canonical deployments return `keccak256("org.superfluid-finance.contracts.SuperToken.implementation")`.  
This assumption is however already invalidated by existing non-canonical deployments, [e.g. by G$](https://github.com/GoodDollar/GoodProtocol/blob/master/contracts/token/superfluid/SuperToken.sol#L114).

**Comment by hellwolf** [comment]
> In case of the canonical SuperToken contract, the restriction is that [only the host](https://github.com/superfluid-finance/protocol-monorepo/blob/dev/packages/ethereum-contracts/contracts/superfluid/SuperToken.sol#L150) can trigger the update. The host contract can trigger this through [updateSuperTokenLogic](https://github.com/superfluid-finance/protocol-monorepo/blob/dev/packages/ethereum-contracts/contracts/superfluid/Superfluid.sol#L295C14-L295C35) which can be called by gov only.

Indeed.

But at the same time, `ISuperfluid immutable internal _host;` does not imply it has to be our host. A custom super token logic may simply set it to a different when during its construction. Would this work?

**Comment by d10r** [comment]
Yeah, but that would create all kinds of additional implications, imo coming down to requiring a redundant deployment of the protocol. Much simpler to decouple the update privilege from the host in that custom logic.

**Comment by hellwolf** [comment]
We can do a SuperToken revision around this rule.

**Comment by d10r** [comment]
Added a deployment script.
Waiting for the FRACTION deployer to deploy (important contract params are hardcoded in the logic, so we can't deploy a generic version as is) and request an update.

We can exclude such SuperTokens with custom logic by modifying the upgrade script to compare SuperToken logic addresses against a list of all canonical implementations there existed, can be done by querying the protocol subgraph for 
```
  superTokenLogicCreatedEvents {
    tokenLogic
  }
```
