### ISSUE TITLE
[ETHEREUM-CONTRACTS] deploy-framework.js code change check is not reliable

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#1448]
**update**

the original issue was solved, but a deeper issue discovered -> scroll down

original issue:

```
$ RESOLVER_ADDRESS=0xF12b5dd4EAD5F743C6BaA640B0216200e89B60Da RELEASE_VERSION=v1 DISABLE_NATIVE_TRUFFLE=1 npx truffle exec ops-scripts/deploy-framework.js 
Using network 'development'.

truffle detected true
use truffle native environment (isTruffle) false
protocol release version: v1
======== Deploying superfluid framework ========
reset superfluid framework:  false
network Type:  private
network ID:  4447
chain ID:  1337
truffle detected false
use truffle native environment (isTruffle) false
protocol release version: v1
Checking ERC1820 deployment at 0x1820a4B7618BdE71Dce8cdc73aAB6C95905faD24
ERC1820 is already deployed.
Using @superfluid-finance/js-sdk in a non-native Truffle environment.
                Peer dependency @truffle/contract is required.
Set default from address to the first account 0x627306090abaB3A6e1400e9345bC60c78a8BEf57
Resolver address 0xF12b5dd4EAD5F743C6BaA640B0216200e89B60Da
TestGovernance.v1 address 0x345cA3e014Aaf5dcA488057592ee47305D9B3e10
TestGovernance does not need new deployment.
SuperfluidLoader-v1 address 0x8f0483125FCb9aaAEFA9209D8E9d7b9C8B9Fb90F
SuperfluidLoader does not need new deployment.
Superfluid.v1 address 0x30753E4A8aad7F8597332E813735Def5dD395028
Superfluid does not need new deployment.
superfluidConstructorParam: 00000000000000000000000030753e4a8aad7f8597332e813735def5dd395028
Superfluid has the same logic code, no deployment needed.
ConstantFlowAgreementV1 has the same logic code, no deployment needed.
InstantDistributionAgreementV1 has the same logic code, no deployment needed.
checking if SuperTokenFactory needs to be redeployed...
   factory.getSuperTokenLogic.call()
   superTokenLogic.CONSTANT_OUTFLOW_NFT()
   superTokenLogic.CONSTANT_INFLOW_NFT()
cofAddr 0x4E72770760c011647D4873f60A3CF6cDeA896CD8
cifAddr 0xbaAA2a3237035A2c7fA2A33c76B44a8C6Fe18e87
constantOutflowNFTLogicChanged: true
constantInflowNFTLogicChanged: true
superTokenFactoryCodeChanged: false
superTokenLogicCodeChanged: false
```

[binary](https://app.zenhub.com/files/246007977/2cca29e9-24c1-479b-b1a6-5c9e03d2fb9a/download)
[code](https://app.zenhub.com/files/246007977/152766c1-9598-4d85-a9ec-d1762b0f7dba/download)

**Comment by 0xdavinchee** [comment]
## Findings
After @d10r and I investigated this issue, we have found the issue here was that we were not passing the CFA contract in the replacements array of the `codeChanged` function in our deploy scripts. The deployed bytecode has immutable variables set, but the compiled binary does not.

In addition, we noticed that the `SuperTokenFactory` contract's `codeChanged` check was also not taking replacements, but it never detected changes. We discovered that the `lastIndexOf` the creation code: `6080604052` was not the second occurrence in the case of the `SuperTokenFactory` which led to too much of the bytecode being removed.

**Comment by d10r** [comment]
Example for what happens:
30753e... is the host address, to be replaced bcs it's an immutable in the factory logic code.
In the untrimmed code, it appears several times:
![image.png](https://images.zenhubusercontent.com/63527374822bb7b58064e166/5df7decb-23ea-49f7-b78a-b1af947be384)
after trimming, there's no occurance left:
![image.png](https://images.zenhubusercontent.com/63527374822bb7b58064e166/485a3b34-3f7e-4418-b1de-99f33e3c51f5)

As a result, the check will not recognize the code as changed if the host address mismatches. Can that be correct behaviour here?

This is the relevant code:
```
    // SEE: https://github.com/ConsenSys/bytecode-verifier/blob/master/src/verifier.js
    // find the second occurance of the init code
    let codeTrimed = code.slice(code.lastIndexOf("6080604052")).toLowerCase();
    const binaryTrimed = binaryFromCompiler
        .slice(binaryFromCompiler.lastIndexOf("6080604052"))
        .toLowerCase();
```

Looking at the code comments in the verifier.js file, this seems to be a hack in order to extract the actual bytecode.
etherscan doesn't seem to agree with the code being that short, see e.g. https://goerli.etherscan.io/address/0xe31965ceb83ffa498a0a3ef68b841a279022a395#code

@hellwolf can you comment?

**Comment by d10r** [comment]
This requires a focused investigation, ideally leading to an updated algorithm provided as module to the wider ecosystem.

**Comment by hellwolf** [comment]
https://github.com/superfluid-finance/protocol-monorepo/wiki/Smart-Contracts-Incremental-Deployment-Technique

**Comment by d10r** [comment]
more findings:
our current `codeChanged()` does
```
let codeTrimed = code.slice(code.lastIndexOf("6080604052")).toLowerCase();
```
on the code loaded from chain. This doesn't make sense because it already is the runtime code.
In many cases it will do nothing, but if the contract contains code for deploying contracts, it will jump to the start of the embedded contract, wrongly discarding the rest of the outer contract code which comes before.
This is likely the reason why the check won't fail for Superfluid despite missing immutable replacements, because it contains a nested UUPSProxy and will compare its bytecode.

A possibly correct implementation could be
```
async function codeChanged(
    web3,
    contract,
    address,
    replacements = [],
    debug = false
) {
    // Use .binary instead of .bytecode to include linked library addresses
    let binaryFromCompiler = contract.binary.toLowerCase();
    // Trim `binaryFromCompiler` to start from the first occurrence of "6080604052"
    const firstIndex = binaryFromCompiler.indexOf("6080604052");
    if (firstIndex !== -1) {
        binaryFromCompiler = binaryFromCompiler.slice(firstIndex);
    }

    let code = (await web3.eth.getCode(address)).toLowerCase().replace(/^0x/, "");;

    // No code at the address indicates a change
    if (code.length <= 3) return true;

    // Apply replacements only to the on-chain code for dynamic values (e.g., constructor parameters)
    console.log("applying replacements", replacements);
    replacements.forEach((r) => {
        const replacement = "0".repeat(r.length);
        code = code.replace(new RegExp(r, "g"), replacement);
    });

    // Check if the on-chain code (with replacements) is a subset of the binary from the compiler
    const isSubset = binaryFromCompiler.includes(code);

    if (debug) {
        console.log("  binaryFromCompiler", binaryFromCompiler);
        console.log("  codeReplaced", code);
    }

    if (isSubset) {
        // Find where `code` ends within `binaryFromCompiler`
        const endIndex = binaryFromCompiler.indexOf(code) + code.length;

        // Verify that either `binaryFromCompiler` ends there or has "6080604052" following
        const isMatch = endIndex === binaryFromCompiler.length ||
                        binaryFromCompiler.slice(endIndex).startsWith("6080604052");

        if (debug) {
            console.debug("On-Chain Code (Processed):", code);
            console.debug("Compiled Code (With Replacements):", binaryFromCompiler);
            console.debug("End Index in Compiled Code:", endIndex);
            console.debug("Is Match:", isMatch);
        }

        return !isMatch; // Return true if there's no match, indicating a change
    }

    // If not a subset, it's a mismatch
    return true;
}
```

Problem: once it actually works, we'll have to deal with all immutables.
E.g.Superfluid.sol has bools and a rather small int too. So the strategy to simply replace all occurances, like for addresses, isn't sound.
