### ISSUE TITLE
[ETHEREUM-CONTRACTS] -  SuperApp test Framework

### ISSUE THREAD

**Issue by ngmachado** [superfluid-finance/protocol-monorepo#1451]

**Comment by ngmachado** [comment]
"Have 3 of our top 5 TVS live super apps “stamped” with our quality seal"

@philipandersson @vmichalik What apps are we talking about?

If I understood correctly, we want to have a set of smart contract tests that can be applied to CFA SuperApp. Can this be confirmed?

**Comment by philipandersson** [comment]
https://www.notion.so/superfluidhq/Super-App-Testing-Framework-a2bfd33944154ba8b1203021d98784f8?pvs=4
