### ISSUE TITLE
[ETHEREUM-CONTRACTS] - Increase stress (fuzzing) test suite coverage

### ISSUE THREAD

**Issue by ngmachado** [superfluid-finance/protocol-monorepo#1452]

**Comment by vmichalik** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Protocol-Team-6405e4d5014c0d0036e14f49/issues/superfluid-finance/protocol-monorepo/1452?planning-poker) with Zenhub @0xdavinchee @d10r @ngmachado @philipandersson

**Comment by hellwolf** [comment]
superceded by #1570
