### ISSUE TITLE
Mixing error formats

### ISSUE THREAD

**Issue by ngmachado** [superfluid-finance/protocol-monorepo#1453]
Is there any reason why this line is using a string and not the custom error?

https://github.com/superfluid-finance/protocol-monorepo/blob/fffa17974abd0a80e74247babdb1d79911678ab4/packages/ethereum-contracts/contracts/superfluid/Superfluid.sol#L1037

**Comment by 0xdavinchee** [comment]
yeah, when I was doing the refactor a while ago, I ran into an issue with one of the tests: https://github.com/superfluid-finance/protocol-monorepo/blob/dev/packages/ethereum-contracts/test/contracts/superfluid/Superfluid.test.ts#L1511-L1512

**Comment by 0xdavinchee** [comment]
update: I am currently trying with a custom error and it seems fine with a slight change, not sure if things changed or I was in a rush when I did this previously.
