### ISSUE TITLE
[INFRA] Set up BASE Testnet Sentinels

### ISSUE THREAD

**Issue by vmichalik** [superfluid-finance/protocol-monorepo#1458]

**Comment by vmichalik** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Protocol-Team-6405e4d5014c0d0036e14f49/issues/superfluid-finance/protocol-monorepo/1458?planning-poker) with Zenhub @0xdavinchee @d10r @ngmachado @philipandersson

**Comment by d10r** [comment]
sentinel running
