### ISSUE TITLE
[INFRA] Set up Polygon zkEVM Testnet Peripherals

### ISSUE THREAD

**Issue by vmichalik** [superfluid-finance/protocol-monorepo#1459]
- [x] Metadata
- [x] Sentinels
- [x] Subgraphs
- [x] SDKs

**Comment by vmichalik** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Protocol-Team-6405e4d5014c0d0036e14f49/issues/superfluid-finance/protocol-monorepo/1459?planning-poker) with Zenhub @0xdavinchee @d10r @ngmachado @philipandersson

**Comment by d10r** [comment]
done in https://github.com/superfluid-finance/protocol-monorepo/issues/1425, but needs a review after changing the canonical name

**Comment by d10r** [comment]
to be checked: subgraph showing an empty token list

**Comment by d10r** [comment]
need to re-sync subgraph after merging https://github.com/superfluid-finance/protocol-monorepo/pull/1546

**Comment by d10r** [comment]
need to bump metadata version and sdk-core version

**Comment by d10r** [comment]
subgraph re-synced, [sdk released](https://github.com/superfluid-finance/protocol-monorepo/releases/tag/sdk-core%40v0.6.8)
