### ISSUE TITLE
GDA breakdown

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1467]
Purpose: To break down the different functions in order to reason about more clearly what is exactly happening, that is, what we expect to be happening-this will be used to further flesh out some of the helper functions in our tests.
See: https://hackmd.io/@0xdavinchee/HJy65vxwh

**Comment by hellwolf** [comment]
What does "break down" mean here?

**Comment by 0xdavinchee** [comment]
break down here means having an explicit understanding of what the new expected state is after each interaction given:
- existing state
- inputs
I would say this can be marked as completed, the spike part of it.

**Comment by 0xdavinchee** [comment]
having an explicit understanding of what the new expected state is after each interaction given:
- existing state
- inputs
I would say this can be marked as completed, the spike part of it.
