### ISSUE TITLE
Switch to template for provider url in workflows

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#1468]
We currently require a dedicated env var in the form "<NETWORK_NAME>_PROVIDER_URL" for every supported network.
This was adequate initially with just 4 networks and a few places where the variable is needed, but is becoming a significant overhead with a growing number of networks and scripts consuming this variable.

In order to reduce this overhead, we should switch to using a template provider url.
This can be easily done thanks to our endpoints using canonical network names.

Using a template in conjunction with metadata also allows to extend support to more networks without touching a piece of code.

#### Steps
* Add `TEMPLATE_PROVIDER_URL` as org secret
* Change ethereum-contracts/truffle-config.js to use it (keep support for network specific ones, can be used for manual override)
* change workflows to use it

**Comment by hellwolf** [comment]
I think we have. Closing.
