### ISSUE TITLE
[INFRA] Base Testnet Completion

### ISSUE THREAD

**Issue by vmichalik** [superfluid-finance/protocol-monorepo#1476]
## Protocol

- [x]  [Deploy Framework](https://github.com/superfluid-finance/protocol-monorepo/wiki/Framework-Deployment-Guide)
- [x]  Verify Contracts
    - [ ]  Contract + Proxy verification (etherscan-like: manually verify the Proxies and mark them as such in the UI)
- [x]  Create `NativeAssetSuperToken`

## Peripheries

- [ ]  RPC Endpoint
- [ ]  SDK-Core Support
    - [ ]  Update `@superfluid-finance/metadata` package
        - [ ]  Reinstall metadata in SDK-Core
    - [ ]  Bump SDK-core version
        - [ ]  Update `CHANGELOG.md`
    - [ ]  Create Release Draft + Release package
- [ ]  Subgraph Support
    - [ ]  Create new endpoint (*Protocol V1/Dev XXX YYY*) : https://thegraph.com/hosted-service/subgraph/create?account=superfluid-finance
    - [ ]  Add new network to `networks.json`
    - [ ]  Add contract addresses to `config/<NETWORK>.json`
    - [ ]  Create new subgraph endpoints via the Graph dashboard (requires admin permissions)
        - [ ]  `/superfluid-finance/protocol-<dev|v1>-<NETWORK>`
        - NOTE: the `"network"` field in `<NETWORK>.json` is based on [The Graph's network naming convention](https://thegraph.com/docs/en/developer/create-subgraph-hosted/#supported-networks)
        - `<NETWORK>` is based on Superfluid’s canonical naming (per truffle.config.js)
    - [ ]  Deploy dev + v1 subgraphs
- [ ]  SDK-Redux Support
    - [ ]  Update `package.json` to use new SDK-Core version with new network support
    - [ ]  Bump SDK-Redux version
        - [ ]  Update `CHANGELOG.md`
    - [ ]  Create Release Draft + Release package (OPTIONAL)
- [ ]  Monitoring
    - [ ]  Tenderly monitoring system
- [ ]  Sentinel Support [prerequisite for framework deployment
    - [ ]  Funds required for liquidation
- [ ]  Docs
    - [ ]  Add new contract addresses to the docs
- [ ]  Faucet (TESTNET ONLY)
    - [ ]  Set up faucet for testnet users

## Products

- [ ]  Console Support
- [ ]  Platform Service Support
- [ ]  Dashboard Support
- [ ]  TOGA Dashboard Support

## Marketing

- [ ]  Announcement tweet (w/ partners?)
- [ ]  Medium article

## Internal

- [ ]  Add new network subgraph deployment info to portal-dev

**Comment by vmichalik** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Protocol-Team-6405e4d5014c0d0036e14f49/issues/superfluid-finance/protocol-monorepo/1476?planning-poker) with Zenhub @0xdavinchee @d10r @ngmachado @philipandersson

**Comment by d10r** [comment]
verification on polygonscan fails for unknown reason. Sent a message to our shared TG channel.
