### ISSUE TITLE
Add GDA support to SDK-Core

### ISSUE THREAD

**Issue by philipandersson** [superfluid-finance/protocol-monorepo#1485]

**Comment by philipandersson** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Protocol-Team-6405e4d5014c0d0036e14f49/issues/superfluid-finance/protocol-monorepo/1485?planning-poker) with Zenhub @0xdavinchee @hellwolf @d10r @ngmachado

**Comment by vmichalik** [comment]
Duplicate of #263
