### ISSUE TITLE
[SUBGRAPH] Add `totalNumberOfHolders` counter to `TokenStatistic`

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1487]

**Comment by kasparkallas** [comment]
Let's call it `totalNumberOfAccounts` to be more accurate.

What I mean is that the account might not be "holding" anymore, technically they've just interacted with the token.

**Comment by vmichalik** [comment]
@kasparkallas @msoni89 the use case is that a team who have deployed a token would like to know how many people currently hold that token

so that part is actually core to it, total number of accounts interacted with is only of secondary interest
