### ISSUE TITLE
[ETHEREUM-CONTRACTS] Test GDA + Pool "Invariants" in helper functions

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1491]
This involves:
- [x] some refactoring of the existing GDA test code
  - [x] Move helper functions out to FoundrySuperfluidTester
  - [x] Split GDA tests from SuperfluidPool tests where applicable
- [x] A thorough accounting of all the different state changes in the different functions being transcribed into the tests (done, but needs revision): https://hackmd.io/5h-u_t4dSduKQA924xB_6w

**Comment by hellwolf** [comment]
As a subtask of the epic https://app.zenhub.com/workspaces/protocol-team-6405e4d5014c0d0036e14f49/issues/gh/superfluid-finance/superfluid-stories/244, it is considered done and included in the gda branch.
