### ISSUE TITLE
[GDA] - Update BatchLiquidation Contract

### ISSUE THREAD

**Issue by ngmachado** [superfluid-finance/protocol-monorepo#1493]
Extend the functionality of our [BatchLiquidator](https://github.com/superfluid-finance/protocol-monorepo/blob/gda/packages/ethereum-contracts/contracts/utils/BatchLiquidator.sol). 

The current implementation requires support for GDA liquidation using the [distributeFlow](https://github.com/superfluid-finance/protocol-monorepo/blob/262bd19fab035100ce275175b31209bc246e8ae8/packages/ethereum-contracts/contracts/agreements/GeneralDistributionAgreementV1.sol#L420) method.

Modifications need to consider that liquidations are to be conducted on a per-token basis.

**Comment by ngmachado** [comment]
I think the solution will be something around this:

## Struct to encapsulate the operation
```solidity
 struct FlowData {
        bool agreementOperation; // 0 - CFA, 1 - GDA. Assuming CFA will be the most common. 0 is cheaper.
        address sender;
        address receiver;
    }
```

## Function signature
```solidity
   function deleteFlows(address superToken, FlowData[] calldata data) external;
```

This way we can continue to use Sentinel liquidation pipeline without breaking into two different operations.

**Comment by hellwolf** [comment]
as a subtask of https://app.zenhub.com/workspaces/protocol-team-6405e4d5014c0d0036e14f49/issues/gh/superfluid-finance/superfluid-stories/262, it is considered done.
