### ISSUE TITLE
[ETHEREUM-CONTRACTS] add support for non-EOA gov owner to deploy script

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#1496]
Currently testnet upgrades (using deploy-framework.js) will fail if governance isn't owned by the EOA signer.
With base-goerli being switched to a Safe owner, `currentGovernance.replaceGovernance` needs to be executed using `sendGovernanceAction`.  
As dependency of that, auto-detection of Safe should be added to `sendGovernanceAction`.

**Comment by hellwolf** [comment]
What is the status now?

**Comment by hellwolf** [comment]
I believe this is resolved
