### ISSUE TITLE
[BUG] Unverified Proxy Implementation for CFA Breaks Dune 

### ISSUE THREAD

**Issue by mikeghen** [superfluid-finance/protocol-monorepo#1499]
**Describe the bug:**
The unverified implementation of CFAV1 that was deployed on Polygon seems to cause Dune Analytics Queries to break. Below you can see the query I have here for Ricochet V3 USDC>>ETH Leaderboard: https://dune.com/queries/2394212/3927730. The table this reads from is no longer available because Dune isn't able to decode the unverified contract. I guess this is the reason because OP and GNO work fine and there the contract is verified.

<img width="1121" alt="Screen Shot 2023-07-10 at 7 00 20 PM" src="https://github.com/superfluid-finance/protocol-monorepo/assets/5077880/5d28de7e-b8b3-4cc1-b0b8-d8b40ae00466">

This is what things look like when the contract is properly decoded, which is the case on Gnosis chain:

<img width="388" alt="Screen Shot 2023-07-10 at 7 00 55 PM" src="https://github.com/superfluid-finance/protocol-monorepo/assets/5077880/52104ab8-055b-4dde-8be8-2e93b29df898">

**Comment by mikeghen** [comment]
This is also the case for the IDA contract on Polygon:
<img width="393" alt="Screen Shot 2023-07-10 at 7 08 51 PM" src="https://github.com/superfluid-finance/protocol-monorepo/assets/5077880/842ba410-5d63-416c-a8e2-4882b766431a">

**Comment by d10r** [comment]
thx for the report @mikeghen and sorry for the inconvenience.
The contracts you mentioned are now verified, after this incident we'll look into making this more robust.
I'm not yet closing the issue bcs I still can't run the query you linked too. But I guess that's just a delay.

**Comment by mikeghen** [comment]
Thanks @d10r 👏  I think it takes Dune some time because it only broke 7 days ago, yet I saw the contracts were deployed like 25 days ago. So queries did work for a while even with the unverified contracts. I'll keep an eye on it, I'm sure now it'll come back after a few days.

**Comment by mikeghen** [comment]
@d10r, I resubmitted the contract on Dune hoping to get it fixed faster

**Comment by mikeghen** [comment]
@d10r, I resubmitted but dune rejected my submission 😿 I'm not sure why they don't give a reason

**Comment by d10r** [comment]
> @d10r, I resubmitted but dune rejected my submission crying_cat_face I'm not sure why they don't give a reason

Sorry to hear that.
I'll close the issue bcs the verification is done.
Please let me know if there's anything else you think I can do to help to solve the problem with Dune.

**Comment by mikeghen** [comment]
@d10r, they fixed it 🎉  
<img width="417" alt="Screen Shot 2023-07-31 at 3 58 00 PM" src="https://github.com/superfluid-finance/protocol-monorepo/assets/5077880/09a0677e-0df2-4569-b2eb-957def1514e4">
