### ISSUE TITLE
[METADATA] CI should double check if addresses match what's stored in resolver

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1509]
https://github.com/superfluid-finance/metadata/issues/10

**Comment by hellwolf** [comment]
This effort is being abandoned, in favor of keeping resolvers only for:

1. current superfluid token curation system
2. deployment tagging.

**Comment by hellwolf** [comment]
If there is a stronger reason why we should do this step, please add more context.
