### ISSUE TITLE
[ETHEREUM-CONTRACTS] - Deprecated Register Method in SuperAppBaseFlow

### ISSUE THREAD

**Issue by ngmachado** [superfluid-finance/protocol-monorepo#1515]
The SuperAppBaseFlow currently employs a deprecated registration method which is becoming an obstacle for production deployments of new SuperApps.

Please refer to this line of code in the SuperAppBaseFlow file :
https://github.com/superfluid-finance/protocol-monorepo/blob/952e2867ac079e9bf1fa5331242fed1d3d0039a3/packages/ethereum-contracts/contracts/apps/SuperAppBaseFlow.sol#L52

Also, note this comment in the ISuperfluidinterface :
 https://github.com/superfluid-finance/protocol-monorepo/blob/952e2867ac079e9bf1fa5331242fed1d3d0039a3/packages/ethereum-contracts/contracts/interfaces/superfluid/ISuperfluid.sol#L221
 
For new SuperApps, we've been informally using "k1" as the key as a standard procedure. 
While this can help to maintain the constructor signature, it's important to extend support to Factory deployments as well.

**Comment by hellwolf** [comment]
Fixed in https://github.com/superfluid-finance/protocol-monorepo/pull/1554
