### ISSUE TITLE
[ETHEREUM-CONTRACTS] Include TOGA and BatchLiquidator in Deployer

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1524]
This enables discovery of the two peripheral contracts for downstream dependencies

**Comment by hellwolf** [comment]
As a subtask of https://app.zenhub.com/workspaces/protocol-team-6405e4d5014c0d0036e14f49/issues/gh/superfluid-finance/superfluid-stories/262, it is considered done.
