### ISSUE TITLE
[ETHEREUM-CONTRACTS] deployment.test.js should cover aux contracts

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#1535]
`deployment.test.js` currently misses a few aux contracts in coverage resulting fixes in https://github.com/superfluid-finance/protocol-monorepo/pull/1532/files discovered later.

**Comment by d10r** [comment]
done in https://github.com/superfluid-finance/protocol-monorepo/pull/1532/commits/dc2188401222753cc458f511a2639c3d376a5b15
