### ISSUE TITLE
[ETHEREUM-CONTRACTS] Review callback gas limit issue

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#154]
# Synopsis

Currently callbacks have a CALLBACK_GAS_LIMIT of 3M gas, and _callCallback should detect the genuine out of gas callback issue vs. out of gas grievance attacks.

Co-reviewer: Hadrien

- Adding a section to https://github.com/superfluid-finance/protocol-monorepo/wiki/About-Call-Proxies

# References

- the 63/64 gas limit trick: https://ronan.eth.link/blog/ethereum-gas-dangers/

**Comment by vmichalik** [comment]
@hellwolf is it possible to add more details here do you think and put into tech debt? or better to close

**Comment by hellwolf** [comment]
Moving to technical debt, waiting for adding a section to https://github.com/superfluid-finance/protocol-monorepo/wiki/About-Call-Proxies

**Comment by hellwolf** [comment]
Concluded with CallbackUtils https://github.com/superfluid-finance/protocol-monorepo/pull/1979
