### ISSUE TITLE
[ETHEREUM-CONTRACTS] Address slither report for the GDA branch

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#1545]
(related to #1357)

- [x] Git rev: 0b9793cacf527aac004bf2c8d89751b759c042e2 (gda-slither branch)
  [gda-slither.output.zip](https://github.com/superfluid-finance/protocol-monorepo/files/12146664/gda-slither.output.zip) / https://raw.githack.com/wiki/superfluid-finance/protocol-monorepo/archives/gda-slither-20230724.output.html
- [x] Git rev: https://raw.githack.com/wiki/superfluid-finance/protocol-monorepo/archives/gda-slither-20230829.output.html

**Comment by hellwolf** [comment]
Adding slither support in https://github.com/superfluid-finance/protocol-monorepo/pull/1640

**Comment by hellwolf** [comment]
@0xdavinchee try it out for the gda branch again.

**Comment by 0xdavinchee** [comment]
https://raw.githack.com/wiki/superfluid-finance/protocol-monorepo/archives/gda-slither-20230829.output.html
