### ISSUE TITLE
[SUBGRAPH] add support for deploying to our self-hosted subgraph to workflow(s)

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#1548]
See https://github.com/superfluid-finance/protocol-monorepo/blob/dev/.github/workflows/handler.deploy-production-subgraphs.yml

Currently our workflows can deploy to the hosted endpoint (thegraph.com/) and to satsuma.

Task:
Add the capability to deploy to our self-hosted endpoint  
(this is mostly for triggering a re-sync after subgraph schema changes. ok if it requires the subgraph to have been initialized before - added to docker-compose, DB created etc.)

**Comment by mmd-afegbua** [comment]
Figured I can make changes to the name of self hosted subgraphs with this. The Graph hosted subgraphs also use the naming pattern (`protocol-v1-<netowkr>`), should rollout of the new names be extended to them? 

https://github.com/superfluid-finance/protocol-monorepo/blob/dev/packages/subgraph/tasks/deploy-to-hosted-service-network.sh

**Comment by mmd-afegbua** [comment]
```
 $GRAPH create protocol-v1 --node https://<node-address>/subgraphs
✖ HTTP error creating the subgraph: 400
/home/graph/protocol-monorepo/node_modules/@oclif/core/lib/errors/index.js:21
    throw new exit_2.ExitError(code);
    ^

ExitError: EEXIT: 1
    at Object.exit (/home/graph/protocol-monorepo/node_modules/@oclif/core/lib/errors/index.js:21:11)
    at CreateCommand.exit (/home/graph/protocol-monorepo/node_modules/@oclif/core/lib/command.js:131:23)
    at /home/graph/protocol-monorepo/node_modules/@graphprotocol/graph-cli/dist/commands/create.js:46:22
    at Client._parseResponse (/home/graph/protocol-monorepo/node_modules/jayson/lib/client/index.js:190:12)
    at /home/graph/protocol-monorepo/node_modules/jayson/lib/client/index.js:149:10
    at IncomingMessage.<anonymous> (/home/graph/protocol-monorepo/node_modules/jayson/lib/client/http.js:80:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  oclif: { exit: 1 },
  code: 'EEXIT'
}

Node.js v18.16.0
```

**Comment by mmd-afegbua** [comment]
Workflow test: https://github.com/superfluid-finance/protocol-monorepo/actions/runs/5866253563/job/15904917744

**Comment by mmd-afegbua** [comment]
Consolidated calls and handlers for subgraph deployment into single reusable workflows. 

https://github.com/superfluid-finance/protocol-monorepo/actions/runs/5927354526/job/16071159126

**Comment by mmd-afegbua** [comment]
Reopening as testing the workflow_dispatch has some edge case errors.

https://github.com/superfluid-finance/protocol-monorepo/actions/runs/5949936604/job/16137110879
