### ISSUE TITLE
[ETHEREUM-CONTRACTS] Review dust accumulated due to math rounding losses in IDA agreement

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#155]
# Synopsis

IDA distribution could accumulate dust for the protocol (loss for the distributors, but gain for the protocol).

Example: Distributing 9 tokens to 3 + 2 units resulting, `floor(9*3/5)=5` and `floor(9*2/5)=3`, totaling 8 actually distributed.

Though the dust amount should be negligible, nonetheless a topic should be reviewed and written out.

Co-reviewer: (from an auditor)

**Comment by vmichalik** [comment]
@hellwolf is it possible to add more details here do you think and put into tech debt? or better to close

**Comment by hellwolf** [comment]
This is not an issue and will be documented in "Instant Distribution Agreement" wiki area. Closing.
