### ISSUE TITLE
[Deployer Whitelisting Request] MadFi Subscriptions

### ISSUE THREAD

**Issue by imthatcarlos** [superfluid-finance/protocol-monorepo#1558]
**Describe the SuperApp:**

The superapp (`SubscriptionHandler.sol`) handles subscriptions for creators. It receives a superfluid money stream with an intended recipient, mints an NFT for the sender of the stream, and redirects the stream to the intended recipient (after taking a protocol fee).

**Network will be deployed?:**
Polygon

**Deployer address:**
`0x7F0408bc8Dfe90C09072D8ccF3a1C544737BcDB6` (madfiprotocol.eth)

**Factory address:**

**Link of repo of the contract to be deployed:**
PR in private repo: https://github.com/mad-finance/madfi-protocol/pull/19

**Contact info for developer:**
tg / discord: `imthatcarlos`

**Notes:**
wave pool winner

staging build: https://creators-staging.madfinance.xyz/creators/carlosbeltran

**Comment by d10r** [comment]
Hello @imthatcarlos , thanks for the request.
A registration key "k1" was created for that deployer, you can start using it right away.
Please reopen if you encounter any issues.
