### ISSUE TITLE
[GDA] Invariant Test the GDA with Echidna

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1570]

**Comment by hellwolf** [comment]
The first weekend-long campaign result:

http://paste.c-net.org/HolidayTucker

Use coverage-guided approach to see what is the low hanging fruit action addition we could add to improve the code coverage.

For the next campaign, we should use lcov coverageFormat instead (per https://github.com/crytic/echidna/pull/1029/files)

**Comment by 0xdavinchee** [comment]
[html.zip](https://github.com/superfluid-finance/protocol-monorepo/files/12438065/html.zip)
echidna coverage outputted by genhtml

**Comment by hellwolf** [comment]
Looks great.

One glaring first issue is that the liquidation logic is never hit in CFA :)

![image](https://github.com/superfluid-finance/protocol-monorepo/assets/186660/296f2b40-fc66-4cc1-b504-7eda7bb5276b)

**Comment by hellwolf** [comment]
Also in GDA:

![image](https://github.com/superfluid-finance/protocol-monorepo/assets/186660/78c1b0ab-346a-4a3b-8552-5f56d62a306c)

**Comment by hellwolf** [comment]
Superfluid Pool is never tested, so there must be a simple bug somewhere:

![image](https://github.com/superfluid-finance/protocol-monorepo/assets/186660/9ddd8b47-5592-4d6b-8c41-492e1823f0ce)

**Comment by hellwolf** [comment]
Overall, where we are:

![image](https://github.com/superfluid-finance/protocol-monorepo/assets/186660/1ad65e60-134d-4e0d-868a-0a31667c2cbf)
![image](https://github.com/superfluid-finance/protocol-monorepo/assets/186660/c858171d-965c-4094-be21-a7c889610571)
![image](https://github.com/superfluid-finance/protocol-monorepo/assets/186660/4d0e8125-8480-477f-bcb6-6660e7ccce32)

**Comment by 0xdavinchee** [comment]
I have attached the echidna campaign output, this includes both the lcov file and the html generated using genhtml. The results are practically the same as the previous campaign. SuperfluidPool coverage still isn't being tracked by echidna.
[gda-echidna-campaign-output.zip](https://github.com/superfluid-finance/protocol-monorepo/files/12485543/gda-echidna-campaign-output.zip)

**Comment by 0xdavinchee** [comment]
I have attached the echidna campaign output, this includes both the lcov file and the html generated using genhtml. The results are practically the same as the previous campaign. SuperfluidPool coverage still isn't being tracked by echidna.
[gda-echidna-campaign-output.zip](https://github.com/superfluid-finance/protocol-monorepo/files/12485543/gda-echidna-campaign-output.zip)
