### ISSUE TITLE
[ETHEREUM-CONTRACTS] Breaking change for 1.8 - Improve artifacts packaging

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1573]
The current packaging of the build output is not ideal, we are distributing truffle, hardhat and foundry output. The goal is to consolidate this and provide a straightforward and pragmatic approach for end-users to consume the contract build outputs (ABIs). 

This may entail creating a new package that ships the ABIs by itself (in tandem with new ethereum-contracts releases).

TODOS
- [x] Spike to see what best practices are/could be considering the different consumers of artifacts
- [x] Make the breaking change.

**Comment by hellwolf** [comment]
merged in https://github.com/superfluid-finance/protocol-monorepo/pull/1593

**Comment by hellwolf** [comment]
>  Spike to see what best practices are/could be considering the different consumers of artifacts

One example: https://www.npmjs.com/package/@uniswap/universal-router?activeTab=code

1) They also ship type chain.
2) They ship "artifacts" folder. I think our `build/{hardhat,foundry,typechain-ethers-v5}` hierarchy is more clear, and I think we should stick to it.
