### ISSUE TITLE
[SDK-CORE] Multi-frameworks support

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1575]
We want to be able to support multiple frameworks, at the most fundamental level, we are creating an interface using an existing framework for end users to interact with the ABIs generated from contract build output.

We should be as framework agnostic and lightweight as possible to:
- reduce friction for end-users
- reduce internal maintenance
- future proof

e.g. ethers v5, ethers v6, viem, wagmi and the many new frameworks which will come in the future.

TODOS
- [ ] Spike Investigation + Brainstorm for how this might be achieved
- [ ] Implement solution and package in SDK-Core as a breaking change

**Comment by 0xdavinchee** [comment]
After some more discussion, we may opt to instead create super simple "example projects" where it just contains snippets of how to execute the different actions in Superfluid as well as how to handle some more exotic things such as the `BatchCall`.

**Comment by hellwolf** [comment]
Fair enough, let's see how the examples look like then judge if we should invest more into it ourselves.

**Comment by hellwolf** [comment]
Closing to freeze SDK v1 scopes
