### ISSUE TITLE
[ETHEREUM-CONTRACTS] Coverage tests don't work when running in parallel

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1591]
## Problem
When trying to run the coverage tests with `parallel: true` in `hardhat.config.ts` under the `mocha` property, the tests break complaining about the code size being too large despite it working fine if the tests are not running in parallel.

I have notified the Hardhat team regarding the issue, [~here~](https://github.com/NomicFoundation/hardhat/issues/4310) [here](https://github.com/NomicFoundation/hardhat/issues/4492) and hopefully they may have more insight into it.

Impact: it slows down the merge queue throughput due to slow testing time.

**Comment by hellwolf** [comment]
for reference: to be resolved/followed here https://github.com/NomicFoundation/hardhat/issues/4492
