### ISSUE TITLE
[SUBGRAPH] Ensure Subgraph is in sync with GDA deployments across testnets

### ISSUE THREAD

**Issue by vmichalik** [superfluid-finance/protocol-monorepo#1595]

**Comment by philipandersson** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Protocol-Team-6405e4d5014c0d0036e14f49/issues/superfluid-finance/protocol-monorepo/1595?planning-poker) with Zenhub @0xdavinchee @d10r

**Comment by hellwolf** [comment]
Closing due to being reported in https://github.com/superfluid-finance/protocol-monorepo/issues/1601 already
