### ISSUE TITLE
[ETHEREUM-CONTRACTS] Remove typechain-types as shipped build 

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1610]
Currently the ethereum-contracts package is responsible for shipping both the ABI and other things such as the typechain (for ethers-v5) types consumed by SDK-Core, etc. 
This is breaking.
The issue with this is we are assuming that downstream packages will be using ethers-v5. With ethers-v6 released, wagmi, viem and new frameworks which will likely come out and replace these in the future, the most pragmatic thing we can do is to ship the most fundamental building block: the ABIs. This allows us to be as framework agnostic as possible.
Internally, the responsibility of handling the ABIs for outputting the required file type will be placed on the consuming package (e.g. SDK-Core, etc.)

**Comment by hellwolf** [comment]
Schedule for 1.9, mark as deprecation in 1.8 CHANGELOG
