### ISSUE TITLE
[TECHDEBT] Review `packages/subgraph/test/helpers/helpers.ts`

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1636]
The usage of graphql-request may be outdated and causing issues w/ Node 20.

**Comment by hellwolf** [comment]
We suspect that this piece of code is not using the up to date "pattern" of using subgraph request:

```
export const subgraphRequest = async <T>(
    query: string,
    variables?: { [key: string]: any }
): Promise<T> => {
    try {
        const response = await request<T & ISubgraphErrors>(
            "http://localhost:8000/subgraphs/name/superfluid-test",
            query,
            variables
        );

        if (response.errors) {
            throw new Error(
                `Failed call to subgraph with query ${query}, error thrown: ${JSON.stringify(
                    response.errors
                )}`
            );
        }

        return response;
    } catch (err) {
        throw new Error(
            `Failed call to subgraph with query ${query} and error ${err}`
        );
    }
};
```

An updated code may help to resolve the node 20 compatibility issue.

The sympton of node 20 compatibility is it closes the network socket spontaneously.

**Comment by 0xdavinchee** [comment]
After looking into the docs for the `graphql-request` package, the current pattern used to execute subgraph requests is the same and there is no new recommended way of doing it.
However, if we look [here](https://github.com/jasonkuhrt/graphql-request#node-version-support) at the supported node versions, the latest supported version is node 19, as of May 1, 2023.
The most recent version of `graphql-request` (6.1.0) was released on May 23, 2023. It seems like there isn't support for node 20.
