### ISSUE TITLE
[DEVX] [GDA] Review and update docs

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1643]
- Review high-level https://docs.superfluid.finance/superfluid/protocol-overview/in-depth-overview/super-agreements/streaming-distributions-coming-soon

**Comment by 0xdavinchee** [comment]
took a little longer than expected because I had to redo it (stuff got wiped)

**Comment by hellwolf** [comment]
Great stuff, thank you
