### ISSUE TITLE
[GDA] Add wrapper functions for pool functions

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1645]
## Problem
After reviewing the docs, I noticed that `updateMember` and `claim` are both functions that only exist on the SuperfluidPool contract which means that these two functions cannot be added to a batch call.

## Solution
- Wrap these pool functions in the GDA via callAgreement so they are batchable
  - `updateMemberUnits(ISuperfluidPool pool, address member, uint128 units, bytes calldata ctx)`
  - `claimAll(ISuperfluidPool pool, address member, bytes calldata ctx)`
- Grant GDA permission the same permissions as admin for updating member units

## TODOS
- [ ] Wrap `updateMemberUnits`
- [ ] Wrap `claimAll`
- [ ] Test happy path
  - [ ] updateMemberUnits
  - [ ] claimAll
- [ ] Test batch call

**Comment by philipandersson** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Protocol-Team-6405e4d5014c0d0036e14f49/issues/superfluid-finance/protocol-monorepo/1645?planning-poker) with Zenhub @0xdavinchee
