### ISSUE TITLE
[HOT-FUZZ] Hot Fuzz Dogfooding Integration Friction List

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1650]
This issue captures a series of friction points when trying to utilize/integrate hot fuzz for madfi.

For projects which do not have foundry yet and want to use hot-fuzz you must install foundry and hot-fuzz:
1. `forge init --force  --no-commit`
2. `forge install superfluid-protocol-monorepo=superfluid-finance/protocol-monorepo@$(git ls-remote https://github.com/superfluid-finance/protocol-monorepo.git hotfuzz-iteration-202308 | awk '{print $1}’)` - note that this installs the monorepo off the last commit in the `hotfuzz-iteration-202308` branch

Integration hiccups
- solc versions between project and our implementations and/or interfaces
- superfluid tester actions should take a token in order to enable multitoken test cases
- issues if they are using an interface from npm package in their implementation, but we reference one from submodules and this will likely happen in the other direction as well
- issues with crytic compile and node_modules 
- new hott test file to be created + yaml file to be created with the same name as the contract
- foundry.toml requires changing of out  out = 'build/foundry/out' is hardcoded
- the deployment of contracts for a super app requires either using a library or pranking especially if the deployments need to come from a specific deployer

**Comment by philipandersson** [comment]
@0xdavinchee is this still relevant?

**Comment by 0xdavinchee** [comment]
not really, will close for now-just a list of friction points w/ using hot fuzz
