### ISSUE TITLE
[PROTOCOL-OPS] deploy-framework.js: make CFA NFTs optional

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#1653]
Back when we had out-of-protocol FlowNFTs, the deploy script had the option to not set NFTs.  
We now switched to protocol-native NFTs. On contract level, they're still optional, but the deploy script doesn't yet support that optionality:

AC:
* make COF and CIF optional
* preserve status (eth-mainnet has them disabled, make sure they're not deployed when upgrading)

**Comment by hellwolf** [comment]
We are removing the NFTs all together instead.
