### ISSUE TITLE
HackDays DevX Friction Points

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1659]
A list of friction points experienced when building on Superfluid during hack days: 

- Having to use a super app for call app action (see [related](https://github.com/superfluid-finance/protocol-monorepo/issues/1038))
- ~Not supporting permit in our TestToken (https://github.com/superfluid-finance/protocol-monorepo/pull/1664)~
- ~Foundry installation instructions are overcomplicated because of previous foundry issue~
- ~SuperToken contract does not expose `_underlyingDecimals` and `_toUnderlyingAmount`, should be exposed with a getter function for `_underlyingDecimals` and an external `toUnderlyingAmount` function (https://github.com/superfluid-finance/protocol-monorepo/pull/1663)~
- ~`SuperTokenV1Library` functions must use `vm.startPrank` instead of `vm.prank`: we know this internally, but this should be mentioned to end-user devs~ (added this to the docs)

**Comment by hellwolf** [comment]
> Having to use a super app for call app action

can repoen this: https://github.com/superfluid-finance/protocol-monorepo/issues/1038

> Not supporting permit in our TestToken

Can reopen this: https://github.com/superfluid-finance/protocol-monorepo/issues


> Foundry installation instructions are overcomplicated (you can specify the tag version instead of getting the commit hash)

I guess foundry fixed this in the upstream.

**Comment by 0xdavinchee** [comment]
closing now as all of the points which can be addressed has been addressed
