### ISSUE TITLE
[Deployer Whitelisting Request] Huma Finance Stream Factoring

### ISSUE THREAD

**Issue by shan-57blocks** [superfluid-finance/protocol-monorepo#1661]
**Describe the SuperApp:**

Stream factoring for your crypto streams, up to 100% of their value. Only available to select streaming platforms.

**Network will be deployed?:**

Polygon

**Deployer address:**

NA

**Factory address:**

0xb9714068220AABAf34E490B04D5D26Cfb4400063

**Link of repo of the contract to be deployed:**

https://github.com/00labs/huma-contracts/blob/superfluid-pool/contracts/superfluid/SuperfluidSuperAppRegister.sol

**Contact info for developer:**

discord: gandalftheblue#2771

**Notes:**

NA

**Comment by d10r** [comment]
@hellwolf gov action 329 ready to be signed

**Comment by hellwolf** [comment]
![image](https://github.com/superfluid-finance/protocol-monorepo/assets/186660/2e2f88ba-0948-47dc-9404-abbe638a55b8)

Done! Enjoy!

**Comment by shan-57blocks** [comment]
Great! Thanks!
