### ISSUE TITLE
[ETHEREUM-CONTRACTS] Front-running of the liquidations of the agreements

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#167]
# Background

From convo with Didi, he thinks that liquidation could be frontrun-ed and cause some sort of grievance or even DDOS attack on the solvency infrastructure by exhausting its gas reserve by doing non-rewarding works.

Though one of the counter-argument is this type of attack does have a cost and the extent of the reward of it is not clear neither.

**Comment by d10r** [comment]
this is solved by TOGA
