### ISSUE TITLE
[DOCS] List of Issues with current docs

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1682]
**Please post any issues you see with our existing docs here.**

We capture some of the issues with the existing Superfluid documentation here, please add to it and link to the appropriate sections where the issues are occurring.
I am not going to go over a deliberate internal accounting of all the issues, but moreso carrying this out ad-hoc whenever external devs complain or if we notice something when browsing the docs.

- [ ] Non-scalable (high maintenance) [documentation of methods](https://docs.superfluid.finance/superfluid/developers/constant-flow-agreement-cfa/cfa-operations#methods) in SDK-Core CFA docs
  - Suggested fix: do not hardcode/write out the functions here, just link to where we have our reference SDK-Core docs and link to the actual .ts file
- [ ] Inconsistent docs, the [IDA docs](https://docs.superfluid.finance/superfluid/developers/instant-distribution-agreement-ida/ida-operations) don't have any references to functions
  - Suggested fix: have a consistent format for CFA/IDA and GDA.

**Comment by hellwolf** [comment]
@youssefea something to consider for the docs improvement.

**Comment by 0xdavinchee** [comment]
both these seem to be addressed by the vision Youssef outlined today
