### ISSUE TITLE
[ETHEREUM-CONTRACTS] Add support for devolution of SuperTokens

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#1685]
When deploying a SuperToken, one currently only has a choice between it being upgradable by SF gov, or not upgradable.
In order to retain the role of upgrade admin, one has to deploy a full copy of SuperToken, with `updateCode` slightly changed. (see https://github.com/superfluid-finance/protocol-monorepo/issues/1436)

We can allow new and existing SuperTokens to retain the upgrade admin role:
* add a storage slot for `ADMIN_OVERRIDE` (not sure about naming). Could also be a struct which for now has only an address field, may use the remaining 12 bytes later e.g. to add flags.
* add a modifier `onlyAdmin` which resolves to `ADMIN_OVERRIDE` if non-zero, to the host address otherwise.
* modify `SuperToken.updateCode` to be permissioned with `onlyAdmin` instead of hardcoded to the host.
* add an argument `admin` to `SuperToken.initialize()` (or override it in order not to break existing code).
This is enough to allow creation of devolved SuperTokens, e.g. by OpenDollar.

In order to additionally allow devolution of existing SuperTokens, and to allow devolved SuperTokens to change the admin, we also need something along the lines of:
* `SuperToken.changeAdmin() onlyAdmin ...`
* `Superfluid.changeSuperTokenAdmin() onlyGovernance`
* `SuperfluidGovernance.changeSuperTokenAdmin()`

With that in place, we should also add an example for how to deploy a devolved SuperToken, and maybe also mention it in the docs.

Stretch goal: Add support for devolved SuperTokens in `SuperTokenFactory`.
On that occasion we could also add a method for deploying Pure SuperTokens (to be specified in separate ticket).

**Comment by 0xdavinchee** [comment]
> With that in place, we should also add an example for how to deploy a devolved SuperToken, and maybe also mention it in the docs.

agree, we should also list a process for becoming a devolved SuperToken for existing SuperToken's in the docs (as a reference) or maybe elsewhere.
