### ISSUE TITLE
[Deployer Whitelisting Request] - Superfluid / PlanetIX

### ISSUE THREAD

**Issue by ngmachado** [superfluid-finance/protocol-monorepo#1687]
Describe the SuperApp:

Superfluid integration with PlanetIX

A clear and concise description of the SuperApp

SuperApp stream payment processor

Network will be deployed?:

Polygon

Deployer address:

0xd94E880075AFa8395Fd61Bf47595c878A84e8aDd

**Comment by hellwolf** [comment]
Closed per https://github.com/superfluid-finance/protocol-monorepo/discussions/1688
