### ISSUE TITLE
[Deployer Whitelisting Request] SuperTontine

### ISSUE THREAD

**Issue by bertux** [superfluid-finance/protocol-monorepo#1689]
**Describe the SuperApp:**

_TradeableCashflow official SuperApp to use it as a first version on Base of SuperTontine with GoodDollar users_

**Network will be deployed?:**
Base

**Deployer address:**
juglas.eth : 0x476E2651BF97dE8a26e4A05a9c8e00A6EFa1390c

**Link of repo of the contract to be deployed:**
https://github.com/superfluid-finance/super-examples/tree/main/projects/tradeable-cashflow/contracts

**Contact info for developer:**
@bertux0x on Telegram

**Notes:**

**Comment by d10r** [comment]
gov action ready to be signed: https://app.safe.global/transactions/queue?safe=base:0xD8A05F504b5Ce16183D3e1e16FD6A365a8db53da

**Comment by d10r** [comment]
tx was executed: https://app.safe.global/transactions/history?safe=base:0xD8A05F504b5Ce16183D3e1e16FD6A365a8db53da
deploy key: k1
