### ISSUE TITLE
[SUBGRAPH] Debug GDA subgraph

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1699]
Mehul/Didi reported a bug: MemberUnitsUpdated event is not visible on the subgraph.

**Comment by hellwolf** [comment]
Investigation ongoing by @0xdavinchee

**Comment by 0xdavinchee** [comment]
after a redeployment of the subgraph, the contracts and @d10r generating some new data, the issue is resolved.
