### ISSUE TITLE
[ETHEREUM-CONTRACTS] Protocol Emergency Plan Spike

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1717]

**Comment by 0xdavinchee** [comment]
Moved to notion

**Comment by philipandersson** [comment]
Ready for review! @hellwolf @ngmachado @d10r

**Comment by hellwolf** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFZCQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b128fbe70dd68afcba32b646588bce0e1768a5ab/image.png)

testing private zenhub image
