### ISSUE TITLE
[Deployer Whitelisting Request] 

### ISSUE THREAD

**Issue by markcarey** [superfluid-finance/protocol-monorepo#1724]
**Describe the SuperApp:**

Submission to this month's Wave Pool with GoodDollar on Celo.

**Network will be deployed?:**

Celo

**Deployer address:**
0xb20DBcd49AE5BAd06E350De88b30639E36e753B9

**Factory address:**
n/a

**Link of repo of the contract to be deployed:**
TBD

**Contact info for developer:**
@markcarey on Discord.

**Notes:**
Still in the idea phase, code to be written then deployed. Wanted to get this request started before the Oct 31st submission deadline...

**Comment by hellwolf** [comment]
@markcarey did you get it sorted in the end? on CELO you don't need whitelisting.

**Comment by markcarey** [comment]
@hellwolf yes, I eventually realized that whitelisting was not needed on Celo!  ....so I closed this issue. ;)
