### ISSUE TITLE
[SUBGRAPH] keep USDC.ex listed

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#1725]
See https://superfluidhq.slack.com/archives/C02K8UDDLR0/p1697453254937579?thread_ts=1697438948.782239&cid=C02K8UDDLR0

On Arbitrum, Polygon and Optimism, there's a native and a bridged USDC. Both have the symbol USDC on chain, but UIs should now show USDC.e (USDC.ex for the SuperToken) for the bridged one, just like Etherscan.

In the resolver, we set this mappings:

Arbitrum USDC.ex: https://console.superfluid.finance/arbitrum-one/supertokens/0x1dbc1809486460dcd189b8a15990bca3272ee04e
Arbitrum USDCx: https://console.superfluid.finance/arbitrum-one/supertokens/0xFc55F2854e74b4f42D01a6d3DAAC4c52D9dfdcFf

Polygon USDC.ex: https://console.superfluid.finance/matic/supertokens/0xCAa7349CEA390F89641fe306D93591f87595dc1F?tab=streams
Polygon USDCx: https://console.superfluid.finance/matic/supertokens/0x07b24BBD834c1c546EcE89fF95f71D9F13a2eBD1?tab=streams

Optimism USDC.ex: https://console.superfluid.finance/optimism-mainnet/supertokens/0x8430F084B939208E2eDEd1584889C9A66B90562f
Optimism USDCx: not yet deployed

However USDC.ex keeps to get unlisted in the subgraph.

**Task:** figure out why that happens (Vincent seems to understand) and how we can mitigate that.

**Comment by d10r** [comment]
problem: [getIsListedToken](https://github.com/superfluid-finance/protocol-monorepo/blob/dev/packages/subgraph/src/utils.ts#L132) has a "hack" to work around the old TestResolver deployed on OG networks not emitting events. (#1004)

This is "fixed" by having the getter look up the listing status and persist. In the case at hand, that has the unintended consequence of resetting the listing status because this mechanism assumes all tokens to be listed with the on-chain symbol.

If we can rely on the `Set` event of the resolver contract, this workaround can be removed, then the resetting wouldn't happen anymore.

**Comment by d10r** [comment]
to be done here:
* de-deploy Resolver contracts (https://github.com/superfluid-finance/protocol-monorepo/issues/1004)
* change subgraph [getIsListedToken](https://github.com/superfluid-finance/protocol-monorepo/blob/dev/packages/subgraph/src/utils.ts#L132) to not change the state `token.isListed`
* de-deploy and sync subgraph on networks with new Resolver

**Comment by d10r** [comment]
short term this is dealt with via a workaround in the dashboard: https://github.com/superfluid-finance/superfluid-dashboard/issues/687

**Comment by kasparkallas** [comment]
A slack thread about an issue that _probably_ is caused by an integrator relying on the subgraph for finding listed tokens: https://superfluidhq.slack.com/archives/C02K8UDDLR0/p1700812172588369

Not confirmed yet.

**Comment by d10r** [comment]
keeping in review until rolled out (subgraphs re-synced)

**Comment by d10r** [comment]
### testnets
* polygon-mumbai on vendor graph (primary and only upstream) was resynced 7 days ago (gda branch)
* eth-goerli on vendor graph (primary and only upstream) was resynced 25 days ago (gda branch).

### mainnets
* arbitrum-one 
  * on vendor superfluid (primary) is syncing for name "protocol-v1". Primary upstream is pointing to legacy name "protocol-v1-arbitrum-one". After finishing syncing, switch over the endpoint and delete the legacy subgraph (TBD: figure out and document how)
  * on vendor graph (fallback) [is syncing](https://thegraph.com/hosted-service/subgraph/superfluid-finance/protocol-v1-arbitrum-one?version=pending&selected=logs)
* polygon-mainnet
  * on vendor graph (fallback) [is syncing](https://thegraph.com/hosted-service/subgraph/superfluid-finance/protocol-v1-matic?version=pending&selected=logs)
  * on vendor satsuma (primary): [stuck](https://subgraphs.alchemy.com/subgraphs/12/versions/9877)
* xdai-mainnet
  * on vendor graph (not in use) [is syncing](https://thegraph.com/hosted-service/subgraph/superfluid-finance/protocol-v1-xdai?version=pending&selected=logs)
  * on vendor superfluid (primary) is syncing for name "protocol-v1". Primary upstream is pointing to legacy name "protocol-v1-xdai-mainnet". After finishing syncing, switch over the endpoint and delete the legacy subgraph (TBD: figure out and document how)
  * on vendor satsuma (fallback): TBD
* optimism-mainnet
  * on vendor garph (fallback) [is syncing](https://thegraph.com/hosted-service/subgraph/superfluid-finance/protocol-v1-optimism-mainnet?version=pending&selected=logs)

### Monitor progress

Query https://<network>.subgraph.x.superfluid.dev/status/graphql
```
{
  indexingStatusesForSubgraphName(subgraphName: "protocol-v1") {
    chains {
      network
      chainHeadBlock { 
        number
        hash
      }
      earliestBlock {
        number
      }
      latestBlock {
        number
      }
    }
    subgraph
    synced
    health
  }
}                                  
```

E.g. this tool: https://graphql-demo.mead.io/
Or Altair (local app)

**Comment by d10r** [comment]
On Arbitrum I now shifted the primary upstream to vendor _graph_ (after it finished syncing).
USDC.ex now remains listed, as expected.

However using the on-chain name & symbol, which makes it difficult to understand for users.

![image](https://github.com/superfluid-finance/protocol-monorepo/assets/5479136/aa149a6c-fb61-4b26-8f97-825e07a3c7d5)

**Comment by hellwolf** [comment]
@vmichalik I would appreciate a summary of this before closing it.

**Comment by d10r** [comment]
not a protocol issue anymore
