### ISSUE TITLE
[ETHEREUM-CONTRACTS] dev deployment script should test against both ethers5 and ethers6

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#1733]
Currently the dev deployment scripts are only tested against ethers5, namely `packages/ethereum-contracts/dev-scripts/deploy-test-framework.js` requires 'const {ethers} = require("hardhat");'

But some of our dependencies, such as sentinel has already switched to ethers6 in the test code. Hence we found out that they didn't work together nicely.

There is a less known package.json feature that can support "package alias", e.g.:

```
"webpack5": "npm:webpack@^5.68.0",
"webpack4": "npm:webpack@^4.46.0",
```

This could be a way for as to test ethereum-contracts dev deployment script for both ethers5 and ether6.

**Comment by 0xdavinchee** [comment]
this PR is the first step towards doing that: https://github.com/superfluid-finance/super-examples/pull/57
we should bring back the daily GH CI runs in super-examples to ensure breakage is caught earlier

**Comment by hellwolf** [comment]
we are in favor foundry approach, and no longer active maintain the hardhat deployment script approach apart from its internal legace usage in tests.
