### ISSUE TITLE
[ETHEREUM-CONTRACTS] TCI next steps

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#1735]
Context: Token Centric Interface / [ERC20x](https://github.com/superfluid-finance/protocol-monorepo/discussions/1188#discussioncomment-4632428)

Status quo: pretty close approximation of Solidity API (contract sender) with SuperTokenV1Library, somewhat close with the forwarders (EOA sender).

Goals:
* more natural API for EOA senders
* unified hooks API
* see if we can get rid of clipping issues (too much detail for devs)
* deprecate IDA (GDA covers its use cases)
* review GDA incorporation
* unify lib and forwarder API
* provide high level API (don't require CRUD)
* clear identity definition (what are the identity and lifetime of a flow or stream?)
* allow for full devolution (own all state, option to be get independent of SF gov)
* can we get rid of host?

Deliverable: elaborate one or several options, to be proposed for implementation.

**Comment by hellwolf** [comment]
no next steps until v2, closing from icebox.
