### ISSUE TITLE
[Deployer Whitelisting Request]: Aqueduct

### ISSUE THREAD

**Issue by joshkokatnur** [superfluid-finance/protocol-monorepo#1744]
**Describe the SuperApp:**
Aqueduct's TWAMM is a time-weighted automated market maker that enables users to swap with streams

**Network will be deployed?:**
Polygon Pos

**Factory/Deployer address:** (AqueductV1Factory)
0x69c9415FbD24b4E33b7EBF1D5eA74bDf8cf8c242

**Link of repo of the contract to be deployed:**
https://github.com/aqueduct-finance/aqueduct-twamm

**Contact info for developer:**
josh@aqueductfinance.com

**Comment by d10r** [comment]
@hellwolf ready for execution

**Comment by hellwolf** [comment]
![image](https://github.com/superfluid-finance/protocol-monorepo/assets/186660/22d77910-e032-433b-9a41-c0919d98dc70)

done!
