### ISSUE TITLE
[SUBGRAPH BUG] Nulls returned when querying "poolDistributor" on flowDistributionUpdatedEvents

### ISSUE THREAD

**Issue by elvijsTDL** [superfluid-finance/protocol-monorepo#1749]
**Describe the bug:**
Cannot query "poolDistributor" on flowDistributionUpdatedEvents , it will return an error - "Null value resolved for non-null field `poolDistributor`"

**Subgraph endpoint:**
All of the networks where GDA is deployed

**Query:**
```
query {
  flowDistributionUpdatedEvents {
    id
    poolDistributor {
      account {
        id
      }
    }
  }
}
```

**Expected data:**
Expecting to see all the information about the pool distributor

**Actual data:**
"Null value resolved for non-null field `poolDistributor`"

**Comment by 0xdavinchee** [comment]
I did a sweep of all the mapping functions and event creators and this issue was also in the other events, but it is fixed now for all event entities.
