### ISSUE TITLE
[BUG][WORKFLOW] Subgraph production deployment fails for 'all' option

### ISSUE THREAD

**Issue by mmd-afegbua** [superfluid-finance/protocol-monorepo#1755]
**Describe the bug:**
In deploying subgraphs with Github workflow, there are options to deploy a single subgraph or `all` subgraph to a hosted platform The workflow works for a singular deployment but fails for `all`.

**Steps To Reproduce:**
1. Go to https://github.com/superfluid-finance/protocol-monorepo/actions/workflows/handler.deploy-production-subgraphs.yml
2. Click on `Run workflow` 
3. Fill in Superfluid as platform, and `all` for the canonical name of the network you want to deploy
4. Run workflow.

**Expected behavior:**
Pipeline builds the subgraph package and deploys to all networks hosted on the platform.

**Actual behavior:**
Script does not execute properly. https://github.com/superfluid-finance/protocol-monorepo/actions/runs/7100885047

**Comment by d10r** [comment]
Is this issue about being able to deploy to all _networks_ or to all _vendors_ supported for a given network?
Both would be useful, but support for all vendors for a specific network would be more important imo.

**Comment by mmd-afegbua** [comment]
Protocol monorepo pipeline variable, **SUBGRAPH_URL_TEMPLATE** uses < networkname >.subgraph.x.superfluid.dev. It needs to be changed to < networkname >.**sfsubgraph**.x.superfluid.dev because in some cases, when the self-hosted subgraph is unavailable, it attempts to deploy to the fallback subgraph, which leads to pipeline failure.

cc: @hellwolf
