### ISSUE TITLE
[GDA] [SUBGRAPH] Connected vs. Disconnected FlowRate on AccountTokenSnapshot entity for receiver

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#1767]
The receiver flow rate should take into consideration whether they are connected to the pool or not as this impacts solvency.
We should not increment the receiver's flow rate if they are not connected to the pool.

**Comment by kasparkallas** [comment]
It's impossible to this correctly (showing GDA flow rate on receiver side) anyway because of GDA's 1-to-many scalability issues when mapping on subgraph, so probably best to drop this field altogether?

**Comment by hellwolf** [comment]
No one understands what was it for. Whoever thinks it is necessary please restate it in a clearer ticket and open again.
