### ISSUE TITLE
[Deployer Whitelisting Request] MadFi

### ISSUE THREAD

**Issue by imthatcarlos** [superfluid-finance/protocol-monorepo#1778]
**Describe the SuperApp:**:

Subscription handler contract to manage subscriptions between subscribers and creators on MadFi.
```
/**
 * @title SubscriptionHandler
 *
 * @notice This contract handles subscriptions for creators. It receives a superfluid money streams with an intended
 * recipient (a MadSBT collection creator), mints an NFT for the sender of the stream, and redirects the stream to the
 * creators (after we take a protocol fee).
 *
 * If this contract is deployed on a chain different than the MadSBT, the `madSBT` global variable will be the null
 * address, and the targetAddress/targetChainId variables are set. This contract uses the WormholeRelayer to send
 * cross-chain messages the MadSBT contract deployed on the target chain. Because flow callbacks are non-payable, we
 * sponsor the wormhole fees by holding native ETH in the contract.
 */
 ```

**Network will be deployed?:**  Polygon

**Deployer address:** `0x7F0408bc8Dfe90C09072D8ccF3a1C544737BcDB6`

**Factory address:** NA

**Link of repo of the contract to be deployed:** https://github.com/mad-finance/madfi-protocol

**Contact info for developer:** @imthatcarlos

**Notes:**: Deployed v1 on base, this is v2

**Comment by hellwolf** [comment]
![image](https://github.com/superfluid-finance/protocol-monorepo/assets/186660/7947fb83-31c2-479b-95ee-afc49e4a2e32)

Done!

**Comment by imthatcarlos** [comment]
hey @hellwolf - not sure if i'm missing something, but got this revert `0x3ca331f263350773ea2bb5b6f8241553c3841c2c8112857f54b1c894e94310a5` when deploying just now on polygon

**Comment by hellwolf** [comment]
As far as I heard from @d10r, it has been resolve off-line.

@imthatcarlos if anything persists, please ping here or open a new ticket!
