### ISSUE TITLE
[BUG][WORKFLOWS] Eliminate Red Github Actions

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#1794]
**Describe the bug:**

To filter all failed workflows lately: https://github.com/superfluid-finance/protocol-monorepo/actions?query=is%3Afailure

The events are:

- [x] [Daily protocol-monorepo slack message | dev branch](https://github.com/superfluid-finance/protocol-monorepo/actions/runs/7610155912) @elvijsTDL 
- [x] [Daily Subgraph and Query Sync Check | dev branch](https://github.com/superfluid-finance/protocol-monorepo/actions/runs/7610137206) @0xdavinchee 
- [x] [CI | Canary (Dev)](https://github.com/superfluid-finance/protocol-monorepo/actions/runs/7571022420)
  - [ ] Upload coverage reports fails: "Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue."
  - [x] #1795
- [x] [CD | Create Monorepo Packages Stable Release Draft](https://github.com/superfluid-finance/protocol-monorepo/actions/runs/7590499191)
  - [x] #1796

**Comment by d10r** [comment]
> Error: deployment superfluid-finance/protocol-v1-optimism-sepolia does not exist

For this one I think we need to remove `hostedEndpoint` for that network from the metadata. (somewhat related to https://github.com/superfluid-finance/protocol-monorepo/issues/1855)

**Comment by 0xdavinchee** [comment]
> [Daily Subgraph and Query Sync Check | dev branch](https://github.com/superfluid-finance/protocol-monorepo/actions/runs/7610137206) @0xdavinchee
https://github.com/superfluid-finance/protocol-monorepo/actions/runs/7653547762/job/20863122157

The action is throwing this error now: 
```
Error: [
  {
    "message": "deployment `superfluid-finance/protocol-dev-optimism-sepolia` does not exist"
  }
]
```

**Comment by hellwolf** [comment]
<img width="625" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3NVQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ce78d44842ef5be232a6be8d9949e85435cde74/image.png" alt="image.png" />
