### ISSUE TITLE
Error: deployment `superfluid-finance/protocol-v1-optimism-sepolia` does not exist

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#1796]

**Comment by hellwolf** [comment]
is it still broken?

**Comment by d10r** [comment]
[it now exists](https://thegraph.com/hosted-service/subgraph/superfluid-finance/protocol-v1-optimism-sepolia).
However scroll-sepolia does not exist and is removed in https://github.com/superfluid-finance/protocol-monorepo/pull/1891

**Comment by hellwolf** [comment]
I will let the PR close the issue.
