### ISSUE TITLE
Link from website goes to non-existent page

### ISSUE THREAD

**Issue by tjayrush** [superfluid-finance/protocol-monorepo#1826]
This link from your website (https://docs.superfluid.finance/superfluid/protocol-overview/in-depth-overview) points to a missing link.

The link is under the "Resources | Protocol Overview" link on this page: https://www.superfluid.finance/

**Comment by youssefea** [comment]
Thank you for opening this issue. We had just published a new version of the docs.

We are progressively setting up redirects to make sure links go to the right place.

@hellwolf this has been fixed. Issue can be closed.
