### ISSUE TITLE
[Deployer Whitelisting Request] Allo Streaming Quadratic Funding Super App Factory

### ISSUE THREAD

**Issue by codynhat** [superfluid-finance/protocol-monorepo#1833]
**Describe the SuperApp:**

Super App factory for Allo Streaming Quadratic Funding. Deploys a Super App for each recipient in an SQF round to trigger updates to the GDA.

**Network will be deployed?:** OP Mainnet

**Deployer address:** 0xfF5Be16460704eFd0263dB1444Eaa216b77477c5

**Factory address:** 0xe9e3404De3B89ed3e8781988C430767C24D37bB2

**Link of repo of the contract to be deployed:** https://github.com/allo-protocol/allo-v2/tree/main/contracts/strategies/_poc/sqf-superfluid

**Contact info for developer:** @codynhat

**Notes:**

**Comment by youssefea** [comment]
Whitelisted: https://optimistic.etherscan.io/tx/0x518e3a566e75c5b168ee36b42d85e41996d193b0a60170c2d62b8deb40d1d54a#eventlog

**Comment by d10r** [comment]
A re-deployment with a few changes (use `registerApp` instead of `registerAppWithKey`) was needed, factory now at https://optimistic.etherscan.io/address/0x235d1DeaFd6097066c75Da0147E026daA1bD6166#code and whitelisted.
