### ISSUE TITLE
[SUBGRAPH] Investigate issues with `Approval` event mapping

### ISSUE THREAD

**Issue by kasparkallas** [superfluid-finance/protocol-monorepo#1834]
### What?
The ERC-20 `Approval` event should be mapped to the subgraph. The `addresses` field should contain the relevant addresses for the user products to show the event in activity history views.

Currently, the event doesn't show up. At a quick glance, there is something off with the mapping. There seems to be two events with the same name:
* approval for ERC-20 allowance
* approval for FlowNFT

The mapping for FlowNFT approval event definitely has `addresses` missing.

I didn't find the mapping for ERC-20 approval event. I could only find it being handled for the `FlowOperator` entity: https://github.com/superfluid-finance/protocol-monorepo/blob/fa5a75dbaf85af9f60a03b224a9c29f1bf214fa7/packages/subgraph/src/mappings/superToken.ts#L454

When querying from Mumbai, this error shows up:
<img width="1896" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2R4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8c250269db53862f722a735a8e1d11e6f547a4f8/image.png" alt="image.png" />

### Why?
The ERC-20 approval event is important and should be properly mapped to the subgraph.

**Comment by 0xdavinchee** [comment]
Thoughts on the TODOS? @kasparkallas 
- [x] Add mapping for missing `addresses` property
- [x] handle SuperToken `Approval` event in `superToken.ts`
- [x] Add a new field indicating whether it is `Approval` event for ERC-721 or ERC-20

**Comment by 0xdavinchee** [comment]
resolved with #1878
