### ISSUE TITLE
[ETHEREUM-CONTRACTS] Cleanup old FlowNFTs

### ISSUE THREAD

**Issue by philipandersson** [superfluid-finance/protocol-monorepo#1851]
Once a month burn/delete (GC) NFTs that no longer has a stream associated.

**Comment by vmichalik** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Protocol-Team-6405e4d5014c0d0036e14f49/issues/superfluid-finance/superfluid-stories/316?planning-poker) with Zenhub @0xdavinchee @d10r @ngmachado @philipandersson
