### ISSUE TITLE
[ETHEREUM-CONTRACTS DEVX] Shift fUSDC to 6 decimals

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#1853]
Problem: USDC has 6 decimals while fUSDC has 18.
Applications using fUSDC with the expectation that it behaves like the mainnet counterpart may get burned by this difference.

Solution: change fUSDC to have 6 decimals:
1. change for new deployments: adjust deployment script
2. change for existing deployments: requires a one-time "hack"
  a.  add logic to SuperToken which allows the owner to change
  b.  update fUSDC to this logic
  c.  trigger the logic to make the switch to 6 digits
  d.  update to canonical logic

To be considered: effect of that change on existing fUSDCx and upgrading/downgrading.
I currently can't think of any particular side effects. But didn't think about it deeply.

**Comment by 0xdavinchee** [comment]
I would also add permit to USDC, like we did in SuperUpgrader.

**Comment by youssefea** [comment]
@d10r is this finished?

**Comment by hellwolf** [comment]
I will bundle this to the EPIC of SuperUpgrader story. When we get there, we need an upgraded super token.

**Comment by hellwolf** [comment]
let's do it in the code base first, anticipating the upgrade to new testnet when Ethereum is 90 years old.
