### ISSUE TITLE
[BUG][WORKFLOW] Subgraph unit and integration tests intermittent failure

### ISSUE THREAD

**Issue by mmd-afegbua** [superfluid-finance/protocol-monorepo#1858]
**Describe the bug:**
When deploying a subgraph, unit and integration tests run before the actual deployment. The tests fail 2 out of 3 time that it runs, and it requires having to run it repeatedly, which takes time.

**Steps To Reproduce:**
1. Go to https://github.com/superfluid-finance/protocol-monorepo/actions/workflows/handler.deploy-production-subgraphs.yml
2. Click on `Run Workflow` and fill in the necessary data in the options provided and run workflow

**Expected behavior:**
All tests run successfully

**Actual behavior:**
Intermittent failure. This particular pipeline has been triggered four times and they've all failed at different test steps. (https://github.com/superfluid-finance/protocol-monorepo/actions/runs/7187662815).

**Additional context:**
The common error happens when a test subgraph is being deployed to the test node. e.g:

```
Types generated successfully
✔ Generate types for GraphQL schema

- Creating subgraph in Graph node: http://localhost:8020/
$ graph create superfluid-test --node http://localhost:8020/
✖ HTTP error creating the subgraph: ECONNRESET
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
/home/runner/work/protocol-monorepo/protocol-monorepo/node_modules/@graphprotocol/graph-cli/node_modules/@oclif/core/lib/errors/index.js:21
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    throw new exit_2.ExitError(code);
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    ^

ExitError: EEXIT: 1
    at Object.exit (/home/runner/work/protocol-monorepo/protocol-monorepo/node_modules/@graphprotocol/graph-cli/node_modules/@oclif/core/lib/errors/index.js:21:11)
    at CreateCommand.exit (/home/runner/work/protocol-monorepo/protocol-monorepo/node_modules/@graphprotocol/graph-cli/node_modules/@oclif/core/lib/command.js:131:23)
    at /home/runner/work/protocol-monorepo/protocol-monorepo/node_modules/@graphprotocol/graph-cli/dist/commands/create.js:46:22
    at Client._parseResponse (/home/runner/work/protocol-monorepo/protocol-monorepo/node_modules/jayson/lib/client/index.js:190:12)
    at /home/runner/work/protocol-monorepo/protocol-monorepo/node_modules/jayson/lib/client/index.js:149:10
    at ClientRequest.<anonymous> (/home/runner/work/protocol-monorepo/protocol-monorepo/node_modules/jayson/lib/client/http.js:100:7)
    at ClientRequest.emit (node:events:514:28)
    at Socket.socketOnEnd (node:_http_client:525:9)
    at Socket.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1359:12) {
  oclif: { exit: 1 },
  code: 'EEXIT'
}

Node.js v18.17.0
```

**Comment by mmd-afegbua** [comment]
Workflow: https://github.com/superfluid-finance/protocol-monorepo/blob/dev/.github/workflows/call.test-subgraph-on-previous-sdk-core-versions.yml

The error emanates from the matrix strategy. One out of the four parallel jobs fail when creating a subgraph.

**Comment by hellwolf** [comment]
I believe this has been fixed:

See 

https://github.com/superfluid-finance/protocol-monorepo/actions/workflows/handler.deploy-production-subgraphs.yml
https://github.com/superfluid-finance/protocol-monorepo/actions/runs/8098553347

![image](https://github.com/superfluid-finance/protocol-monorepo/assets/186660/2a27c98d-b8e4-4059-8126-f9a45bd6dbf7)
