### ISSUE TITLE
[SDK] Split SDK-CORE into SDK-Web3 and SDK-Subgraph

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#1859]
I think it makes sense to make a breaking change for v1 of the SDK-Core after we release the next version of the SDK-Core with GDA support.

Doing this will improve the separation of concerns when it comes to developers who want to simply use the SDK for RPC read/writes vs. those who may only want to query data.

It will also reduce the maintenance of the SDK-Core immensely and will remove a lot of custom code and processes for the really nice-to-have graphql types which will be abstracted away by the graphql-client library.

**Comment by 0xdavinchee** [comment]
related:
- https://github.com/superfluid-finance/protocol-monorepo/issues/916
- https://github.com/superfluid-finance/protocol-monorepo/issues/969

**Comment by 0xdavinchee** [comment]
There seems to be no interest for this, so closing for now.
