### ISSUE TITLE
Examples Folder Cleanup

### ISSUE THREAD

**Issue by kobuta23** [superfluid-finance/protocol-monorepo#186]
- [x] Tradeable cashflow tests (fran)
- [x] ~~Add front-end for Tradeable Cashflow example~~
- [x] Make sure Setup Guide is visible on docs.superfluid.finance
- [x] [Make sure FlowLottery builds properly](https://github.com/superfluid-finance/protocol-monorepo/pull/199)
- [x] Add readmes for all examples
- [x] Make some tests that make sense for auction (fran)

**Comment by hellwolf** [comment]
@kobuta23 you need to clarify more to @pi0neerpat about what exactly needs to be done for this at this point.
