### ISSUE TITLE
[ETHEREUM-CONTRACTS] Complete the Superfluid batch operation set

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#1895]
## Why

We have not reviewed the completeness of the (Sueprfluid) batch operations. Since we are about to roll-out the macro forwarder feature, it is a good time to have it reviewed and completed. 

## What

* Complete Set of Operation Types
  - SuperToken ERC20/ERC-777 Operations (1-99)
    - [x] OPERATION_TYPE_ERC20_APPROVE
    - [x] OPERATION_TYPE_ERC20_TRANSFER_FROM
    - [x] OPERATION_TYPE_ERC777_SEND
    - [x] OPERATION_TYPE_ERC20_INCREASE_ALLOWANCE
    - [x] OPERATION_TYPE_ERC20_DECREASE_ALLOWANCE
  - SuperToken Upgrade/Downgrade Operations (101-199)
    - [x] OPERATION_TYPE_SUPERTOKEN_UPGRADE
    - [x] OPERATION_TYPE_SUPERTOKEN_DOWNGRADE
    - [x] OPERATION_TYPE_SUPERTOKEN_UPGRADE_TO # equiv. ISuperToken.upgradeTo
    - [x] OPERATION_TYPE_SUPERTOKEN_DOWNGRADE_TO # equiv. ISeperToken.downgradeTo
  - Superfluid Host Call Proxies (201-299) 
    - [x] OPERATION_TYPE_SUPERFLUID_CALL_AGREEMENT
    - [x] OPERATION_TYPE_SUPERFLUID_CALL_APP_ACTION # deprecate #1038, by not doing it.
  - Generic Call Proxies (301-399) # overlapping with multicall3
    - [x] OPERATION_TYPE_SIMPLE_FORWARD_CALL  # Using `DMZForwarder`. Must also support payable.
    - [x] OPERATION_TYPE_ERC2771_FORWARD_CALL # depreciates #478, by implementing it. Also using `DMZForwarder`. Must also support payable.

## Out of Scope

* New Feature of Batchcalls
  - Allow fail
   ```
    struct Operation2 {
        // Operation type. Defined in BatchOperation (Definitions.sol)
        uint32 operationType;
        // Operation target
        address target;
        // Allow the operation fail for unspecified reasons
        bool allowFail;
        // Data specific to the operation
        bytes data;
    }
    ```
    - batchCall2
    - forwardBatchCall2

- Out-of-scope discussion(s)
  - a multicalls3 compatible generic call proxies portion of the batch call.

**Comment by hellwolf** [comment]
Total missed so far: add permit2 to the catchable:

Adding `OPERATION_TYPE_PERMIT2`.

**Comment by hellwolf** [comment]
Adding `OPERATION_TYPE_PERMIT2`

**Comment by d10r** [comment]
permit2 becomes possible through the generic call proxies, so doesn't need explicit support.
