### ISSUE TITLE
[Deployer Whitelisting Request] 

### ISSUE THREAD

**Issue by mikeghen** [superfluid-finance/protocol-monorepo#1905]
**Describe the SuperApp:**

_Time weighted average market maker._

**Network will be deployed?:** Optimism

**Deployer address:** 0x744f96332713EFC378e334A7eccAEc8E19532100

**Factory address:** NA

**Link of repo of the contract to be deployed:** 

**Contact info for developer:** @mikeghen

**Notes:**

**Comment by hellwolf** [comment]
@d10r please help.

**Comment by d10r** [comment]
gov action 46 ready to be signed at https://gnosis-wallet.dev.superfluid.dev/#/wallet/0xb9349347fcC0318137e6143A01c6582C072Fb581

**Comment by hellwolf** [comment]
<img width="1249" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOThHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b850daf1259351a4f33afcd205f499f689fb4d5/image.png" alt="image.png" />

**Comment by mikeghen** [comment]
Thank you @hellwolf 🚀
