### ISSUE TITLE
[BUG] Ask about the scope of bug bounty

### ISSUE THREAD

**Issue by imp0wd3r** [superfluid-finance/protocol-monorepo#1924]
**Describe the bug:**
In the documentation, it is stated that IDA is deprecated and that subsequent functionality is centralized in GDA.

https://docs.superfluid.finance/docs/technical-reference/Architecture#instantdistributionagreementv1-uups-proxy
> This agreement is in the process of being deprecated in favor of the more flexible [GeneralDistributionAgreementV1](https://docs.superfluid.finance/docs/technical-reference/Architecture#generaldistributionagreementv1-uups-proxy).

But in Immunefi's scope there is only IDA not GDA, so I would like to ask what is the exact scope at the moment? Does it include IDA and GDA?
https://immunefi.com/bounty/superfluid/

**Environment:**

- **Desktop (please complete the following information):**
  - Device: [e.g. Macbook Pro Silicon, Intel]
  - Network/Connection [e.g. WiFi, Ethernet] 

- **Smartphone (please complete the following information):**
  - Network/Connection [e.g. WiFi, 5G/4G/3G]

**Steps To Reproduce:**

**Expected behavior:**

**Actual behavior:**
A clear and concise description of what actually happens.

**Screenshots:**
If applicable, attach screenshots to help explain your problem.

**Additional context:**
Add any other context or relevant information about the problem here.

**Comment by hellwolf** [comment]
Thanks for the reporting. The official scope of immunefy has been updated.
