### ISSUE TITLE
[OPS] DegenChain verification of framework and yoink related contracts

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#1931]
## What & Why

We want contracts to be verified.
DegenChain has no etherscan'ish explorer, but a blockscout based one at https://explorer.degen.tips/

Automated Blockscout verification with our existing tooling is possible via sourcify.

Elvijs did a PR: https://github.com/ethereum/sourcify/pull/1352

But it seems to not yet be live.
```
curl https://sourcify.dev/server/chains | jq '.[] | select(.chainId == 666666666)'
```
returns an empty result.

## AC

* [x] Sourcify verification working (wait for the above query to signal support)
* [x] Framework contracts verified on sourcify
* [ ] YOINK related contracts verified on sourcify
* [ ] Framework contracts verified on https://explorer.degen.tips
* [ ] YOINK related contracts verified on https://explorer.degen.tips

**Comment by d10r** [comment]
sourcify support now live, framework successfully verified.

However the blockscout based explorer didn't (yet) pick that up. E.g. Resolver: https://explorer.degen.tips/address/0x649FB24ed0B983f88500F3C37682714aB96D73c2?tab=contract

Next: figure out how the sourcify verification can be propagated to the explorer.

**Comment by hellwolf** [comment]
DId if finish?

**Comment by d10r** [comment]
Looks like Blockscout is now fetching from sourcify, contracts are verified.
Related to https://docs.blockscout.com/about/features/ethereum-bytecode-database-microservice
