### ISSUE TITLE
SQF Superapp Factory on Arbitrum

### ISSUE THREAD

**Issue by gravenp** [superfluid-finance/protocol-monorepo#1998]
**Describe the SuperApp:**
A superapp that accepts and forwards donation streams. With each stream update, units in a GDA are updated according to the quadratic matching formula.

**Network will be deployed?:**
Arbitrum One

**Deployer address:**
0xbDf0e99030Eb6Ac95F1DCCb8515c205a7c4D3441

**Factory address:**
0xBB6Ecb12a045a84DC5E43fEC0FceE53dfa11C878

**Link of repo of the contract to be deployed:**
https://github.com/flow-state-coop/allo-v2/blob/main/contracts/strategies/_poc/sqf-superfluid/RecipientSuperApp.sol
https://github.com/flow-state-coop/allo-v2/blob/main/contracts/strategies/_poc/sqf-superfluid/RecipientSuperAppFactory.sol

**Contact info for developer:**
@tnrdd

**Notes:**

**Comment by d10r** [comment]
gov action ready to be signed: https://gnosis-wallet.dev.superfluid.dev/#/wallet/0xb9349347fcC0318137e6143A01c6582C072Fb581
ID 34

**Comment by hellwolf** [comment]
![image](https://github.com/user-attachments/assets/bcfab707-e6ef-4567-96e1-eb2436e4fd75)
