### ISSUE TITLE
[Deployer Whitelisting Request] SQF on Optimism

### ISSUE THREAD

**Issue by tnrdd** [superfluid-finance/protocol-monorepo#2006]
**Describe the SuperApp:**
A superapp that accepts and forwards donation streams. With each stream update, units in a GDA are updated according to the quadratic matching formula.

**Network will be deployed?:**
Optimism

**Factory address:**
0x552942adAc3f12d078ACEc1922C9Fefc61c6EE6a

**Link of repo of the contract to be deployed:**
https://github.com/flow-state-coop/allo-v2/blob/main/contracts/strategies/_poc/sqf-superfluid/RecipientSuperApp.sol
https://github.com/flow-state-coop/allo-v2/blob/main/contracts/strategies/_poc/sqf-superfluid/RecipientSuperAppFactory.sol

**Contact info for developer:**
@tnrdd

**Comment by d10r** [comment]
gov action ready to be signed: https://gnosis-wallet.dev.superfluid.dev/#/wallet/0xb9349347fcC0318137e6143A01c6582C072Fb581
ID 54

**Comment by hellwolf** [comment]
![image](https://github.com/user-attachments/assets/6efb6ad4-9840-4d85-99b7-199a4be37a39)
