### ISSUE TITLE
[Deployer Whitelisting Request] SQF on Base

### ISSUE THREAD

**Issue by tnrdd** [superfluid-finance/protocol-monorepo#2007]
**Describe the SuperApp:**
A superapp that accepts and forwards donation streams. With each stream update, units in a GDA are updated according to the quadratic matching formula.

**Network will be deployed?:**
Base

**Factory address:**
0x552942adAc3f12d078ACEc1922C9Fefc61c6EE6a

**Link of repo of the contract to be deployed:**
https://github.com/flow-state-coop/allo-v2/blob/main/contracts/strategies/_poc/sqf-superfluid/RecipientSuperApp.sol
https://github.com/flow-state-coop/allo-v2/blob/main/contracts/strategies/_poc/sqf-superfluid/RecipientSuperAppFactory.sol

**Contact info for developer:**
@tnrdd

**Comment by d10r** [comment]
gov action ready to be signed: https://app.onchainden.com/safes/base:0xd8a05f504b5ce16183d3e1e16fd6a365a8db53da/transactions/0xd3fce3432ab55173ff47d68d77a3a0d666b5f9760dba60021ecc38d698902dbf

**Comment by hellwolf** [comment]
![image](https://github.com/user-attachments/assets/538cf9e3-2834-4e03-809f-6de3ae9edbec)
