### ISSUE TITLE
[Deployer Whitelisting Request] SQF SuperApp Factory on Base

### ISSUE THREAD

**Issue by tnrdd** [superfluid-finance/protocol-monorepo#2029]
**Describe the SuperApp:**
The SuperApp accepts and forwards donation streams. With each stream update, units in a GDA are updated according to the quadratic matching formula.

**Network will be deployed?:**
Base

**Factory address:**
0xf29933097dFC1456e8B3d934d89D90e6bbED76e5

**Link of repo of the contract to be deployed:**
https://github.com/flow-state-coop/allo-v2/blob/main/contracts/strategies/_poc/sqf-superfluid/RecipientSuperApp.sol
https://github.com/flow-state-coop/allo-v2/blob/main/contracts/strategies/_poc/sqf-superfluid/RecipientSuperAppFactory.sol

**Contact info for developer:**
@tnrdd

**Comment by d10r** [comment]
gov action pending: https://app.onchainden.com/safes/base:0xd8a05f504b5ce16183d3e1e16fd6a365a8db53da/transactions/0xd343c2cf8e9df8ef2664f4ca40115eda1d64240cafbfb2e179c738796e1a0a16

**Comment by hellwolf** [comment]
![image](https://github.com/user-attachments/assets/eb35013e-7ca7-48bc-a5e7-34554f00f4f2)


Enjoy!
