### ISSUE TITLE
Bootstrapping playground.superfluid.dev

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#259]
- [x] bootstrap
- [x] test it from an external developer's point of view (nuno)
- [x] make it available to the public

**Comment by hellwolf** [comment]
Nuno's comments:

- to clone and start a new project is easy (two commands)
- the app itself may not be very useful

**Comment by pi0neerpat** [comment]
TODO
- [ ] add a step in build to remove the @truffle/contract peerDependencies
