### ISSUE TITLE
[JS-SDK] Investigate/Remove current ethers.js support

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#263]
Known issues:

1. Currently ethers.test.js would fail
2. There is also bug report related to ethers.js usage.

Investigate these, and come up with a plan that can make js-sdk@v0.6 largely ethers.js compatible with known issues if too big to fix.

**Comment by pi0neerpat** [comment]
Likely an issue with not awaiting transactions from ethers

**Comment by elvijsTDL** [comment]
Removed in #876
