### ISSUE TITLE
[ETHEREUM-CONTRACTS] Investigate the gas implications on arbitrum

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#331]
Questions:

1. How the ~11M arbgas cost is derived from the createFlow transaction on arbitrum L2.

**Comment by hellwolf** [comment]
Nuno says it costed 0.1 ETH to deploy to kovan.

**Comment by d10r** [comment]
ad block.timstamp - on testnet v5:
```
> eth.getBlock(380500).timestamp
1623062072
> eth.getBlock(380550).timestamp
1623062376
> eth.getBlock(380600).timestamp
1623062376
> eth.getBlock(380650).timestamp
1623062376
> eth.getBlock(380700).timestamp
1623062676
> eth.getBlock(380750).timestamp
1623062676
> eth.getBlock(380800).timestamp
1623062676
> eth.getBlock(380850).timestamp
1623062676
> eth.getBlock(380900).timestamp
1623062976
> eth.getBlock(380950).timestamp
1623062976
```

Seems to be a 5 minute interval.  
So the time granularity would likely be down. It would also mean that new streams may be shown as already running for a few minutes right after opening them. Maybe an UX nuisance, but shouldn't create any fundamental issues.

**Comment by d10r** [comment]
on mainnet:
```
> eth.blockNumber
890
> eth.getBlock(890).timestamp
1623093999
> eth.getBlock(889).timestamp
1623092268                                                                                                                                                                                      
> eth.getBlock(888).timestamp
1623090471                                                                                                                                                                                      
> eth.getBlock(887).timestamp
1623090231                                                                                                                                                                                      
> eth.getBlock(1).timestamp
1622243344
```

using the RPC found in https://github.com/OffchainLabs/arb-token-bridge/blob/master/src/components/App/networks.ts#L82

**Comment by kobuta23** [comment]
But this isn't the timestamp we would be using in streams, right? By what I understood timing is coming from the inbox. The inbox gives a time to a transaction the moment it receives the transaction. So we don't depend directly on the block.timestamp, but rather on the times the inbox is giving.

**Comment by hellwolf** [comment]
Aggregator contract for kovan v5 aritrum: https://kovan.etherscan.io/address/0x55dca5e95d271f2d074a5e6cf4bf95b7db80d67d

**Comment by hellwolf** [comment]
an arb mainnet tx example: https://mainnet-arb-explorer.netlify.app/tx/0x195ccf47a7273c541ccdc449bbe7238dc7933d0b870d9dc90217bbaee7b276a1

**Comment by d10r** [comment]
mainnet contracts:
* [SequencerInbox](https://github.com/OffchainLabs/arbitrum/blob/sequencer2/packages/arb-bridge-eth/contracts/bridge/SequencerInbox.sol): https://etherscan.io/address/0x4c6f947ae67f572afa4ae0730947de7c874f95ef
* [Rollup](https://github.com/OffchainLabs/arbitrum/blob/sequencer2/packages/arb-bridge-eth/contracts/rollup/Rollup.sol): https://etherscan.io/address/0xc12ba48c781f6e392b49db2e25cd0c28cd77531a#readProxyContract (this seems to be a kind of main contract)

**Comment by hellwolf** [comment]
IMPEDIMENT: waiting for the help to run our own node

**Comment by hellwolf** [comment]
outdated
