### ISSUE TITLE
[JS-SDK] Fix SDK flowrate zero bug

### ISSUE THREAD

**Issue by kobuta23** [superfluid-finance/protocol-monorepo#341]
https://github.com/superfluid-finance/protocol-monorepo/blob/b61a962d3debe6fa5343f38428309f194e850a54/packages/js-sdk/src/User.js#L35

This part of the SDK means I can't send this:

`bob.flow({recipient, flowRate: 0});
`

because flowrate zero will return FALSE and throw an error

**Comment by hellwolf** [comment]
@0xdavinchee you might want to take this one to get familiar with existing js-sdk code base
