### ISSUE TITLE
Can't connect MetaMask in app.superfluid.finance

### ISSUE THREAD

**Issue by jpetrich** [superfluid-finance/protocol-monorepo#350]
I know this repo isn't for your dApp, but wanted to bring this to your developers' attention. When I try to connect my wallet when connected to the Matic network, I get this view with no additional prompt from MetaMask:

![image](https://user-images.githubusercontent.com/13524606/123572955-0c3a9280-d79b-11eb-8fb7-2057024b52e4.png)

and this in the logs: 

```
"Rate limit exceeded: 40 per 1 second. Check response body for more details on backoff.Sign up for a dedicated RPC plan on https://rpc.maticvigil.com/ to avoid hitting public ratelimits."
```

**Comment by hellwolf** [comment]
Hi thanks for reporting, could you please try again? And meanwhile, we will move this to a more suitable place in the superfluid github.
