### ISSUE TITLE
Require `contracts/scripts/utils` prints double input in console

### ISSUE THREAD

**Issue by Shelvak** [superfluid-finance/protocol-monorepo#358]
Importing anything from `@superfluid-finance/ethereum-contracts/scripts/utils` results in a double _print_ in the terminal. Each hit in a the keyboard prints twice whatever you type, until an enter or a backspace.

## Demo:
https://user-images.githubusercontent.com/873323/125178610-2aea5180-e1bd-11eb-9b0c-40d3fd184f98.mp4

The problem is the `readline.createInterface` function. Adding the option `terminal: false` fix the problem.
Stackoverflow e.g.
https://stackoverflow.com/questions/24661774/createinterface-prints-double-in-terminal 

## Context:
I included the file in hardhat console to test first how to interact and what is really necesary to deploy & initialize a native token.

Nothing critic anyway =)

I'm using hardhat 2.2.1 && superfluid eth-contracts 1.0.0-rc5

**Comment by hellwolf** [comment]
@Shelvak #361 should be able to fix this, if wish to test it out follow the instructions at this comment: https://github.com/superfluid-finance/protocol-monorepo/pull/361#issuecomment-882437756

**Comment by Shelvak** [comment]
> @Shelvak #361 should be able to fix this, if wish to test it out follow the instructions at this comment: [#361 (comment)](https://github.com/superfluid-finance/protocol-monorepo/pull/361#issuecomment-882437756)
> 
> Thank you for reporting this!

Just checked, now it works fine. Thanks  for the fix :+1:
