### ISSUE TITLE
[ETHEREUM-CONTRACTS] TDD speed analysis

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#402]
Running contract tests is pretty slow at the moment.  
Trying to figure out where time is lost and how to improve.

**Comment by d10r** [comment]
This is related to https://github.com/superfluid-finance/protocol-monorepo/issues/330 - if Hardhat turns out to be considerably faster and migration not too difficult, it's probably not worth to spend time optimizing the truffle based setup.

Runtimes on my notebook (i7-8550U CPU):

governance tests:
`time npx truffle test test/contracts/gov/SuperfluidOwnableGovernance.test.js`
38.7s

governance tests on already running ganache:
`time npx truffle --network ganache test test/contracts/gov/SuperfluidOwnableGovernance.test.js`
34.5 s

deploy-framework on running ganache:
`time npx truffle --network ganache exec scripts/deploy-framework.js`
14s

empty test:
`time npx truffle test test/EmptyTest.js`
10s

just loading truffle:
`truffle --version`
4.4s

The 10s are probably unavoidable without hacking on truffle itself. This is with all contracts already compiled (_> Everything is up to date, there is nothing to compile._), thus seems to be just the time to load truffle and have it check the contracts/artifacts.  

The tests itself don't take too long in this case, but that's because there's not that much of them. But even if, it's easy to cut down here by selectively activating tests / groups of tests using the `only` keyword of mocha.

Re-deploying the framework for every run adds considerable time overhead and is not necessary in many TDD scenarios.
We could introduce a flag which skips framework re-deployment if the needed contracts are detected to already be deployed to the connected chain, e.g. by looking up if there's a Resolver contract (`getCode(<address>).length > 2 ?`) at the expected address (which is deterministic if ganache is started with a predetermined seed).

**Comment by d10r** [comment]
example for how I cut down the test runner time in an external project via conditional deployment of the SF framework: https://github.com/d10r/streaming-farm/blob/master/test/test-streaming-farm.js#L53

**Comment by hellwolf** [comment]
let's work on something to fix this this week

**Comment by hellwolf** [comment]
#426 will try to improve the test speed issue as per https://www.notion.so/superfluidhq/TestEnvironment-Review-8af2cc711e8c415a896a43e404e833d0
