### ISSUE TITLE
[JS-SDK] v1 API Draft

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#425]
# Acceptance Criteria

- [x] Documenting the API Draft that covers all the goals

# Goals

## Technology

- Use typescript
- Use ethers.js
- Support wide range of web3 providers (web3.js providers, ethers.js providers, metamask window.ethereum, web3-modal, gnosis safe app, etc.)
- Versatile integration modes:
  - NPM package for server usage.
  - NPM package for dapp usage.
  - Plain HTML/Javascript application using script tag (`https://cdn.jsdelivr.net/npm/@superfluid-finance/js-sdk@latest/dist/protocol-sdk.js` as a webpack output for example)

## Data Layer

- Shipped with lower level queries (direct web3, and direct subgraph queries)
- Query abstraction supporting redundancy (subgraph, fallback to web3) and reliability (multiple sources de-dup, reorg, etc.)
- Data update subscriptions
  - Event loop using web3 logBloom filtering, or subgraph updatedAt polling, etc.
  - Account-level (user dashboard use cases) vs global-level (superfluid platform service) filtering
- Limited-feature-mode support for testing environment and exotic networks that does not have subgraph node available

## View-only Mode

- Support setup free usage that is for data reading only.

## (Stretch goal) Transaction Abstraction

- Tighter integration of batch call
-  Meta transaction with `forwardBatchCall`

## Friendly Developer Experience

- Consider some user object wrapper for one liner demo use cases.
- Parameter normalizations:
  - human readable flow rate
  - load token address from resolver by token symbol

**Comment by hellwolf** [comment]
Meeting 1:

![image](https://user-images.githubusercontent.com/186660/134029197-0f9d9fe7-0da5-43f3-a843-7f96568d9082.png)

**Comment by hellwolf** [comment]
@0xdavinchee Updated the goals

**Comment by 0xdavinchee** [comment]
@hellwolf protocol sdk v1 draft progress: https://hackmd.io/@0xdavinchee/rJCAkf8QF

**Comment by hellwolf** [comment]
Draft to be reviewed here: https://www.notion.so/superfluidhq/Protocol-SDK-Core-c9e08bb1560a473cb81200b5cbffff93

**Comment by hellwolf** [comment]
https://www.notion.so/superfluidhq/Protocol-SDK-Core-c9e08bb1560a473cb81200b5cbffff93
