### ISSUE TITLE
[SUBGRAPH] Add creationId to all event entities and HOL entities

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#453]
As a subgraph user, I'd like a solid pagination technical design so that I do not need to worry about the edge cases when query between pages.

## Problem

Currently, using block timestamp or number would mean collisions occur between pages, and it can be tricky to write solid client side app using this pagination method.

## Solution

to be elaborated more: creationId for each entities, which is obtained through a global counter.

**Comment by msoni89** [comment]
@hellwolf  is it a duplicate of https://github.com/superfluid-finance/protocol-monorepo/issues/654

We already covered event entities, do you want me to add `order` also in HOL entities?

**Comment by hellwolf** [comment]
replaced by #654
