### ISSUE TITLE
[OPS] Set Biconomy as trusted forwarder on testnets

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#456]
A user tried to use biconomy on Mumbai: https://discord.com/channels/752490247643725875/752493348169711696/898629794437152798

I guess it's not set as trusted forwarder.  
Here's the addresses: https://docs.biconomy.io/misc/contract-addresses#eip-2771-contracts

How's the process for doing governance actions on testnet deployments?

**Comment by hellwolf** [comment]
Done.
