### ISSUE TITLE
[SuperApp] Custom Polygon Bridge dApp, with Gnosis Safe Compatibility

### ISSUE THREAD

**Issue by kobuta23** [superfluid-finance/protocol-monorepo#472]
## **Synopsis**
Create a custom dApp, usable as a Gnosis Safe App, which enables users to transfer funds through the Polygon-PoS bridge **to an arbitrary receiver**. 

## **Context**
Currently, the Polygon-Pos Bridge only allows users to transfer funds to-from the same address.

In order to use it with Gnosis-Safes or other contracts, it's of fundamental importance to be able to specify a recipient address.

The function which actually performs the bridging [seems to support arbitrary receivers](https://github.com/maticnetwork/pos-portal/blob/88dbf0a88fd68fa11f7a3b9d36629930f6b93a05/contracts/root/TokenPredicates/ERC20Predicate.sol#L41) 

Any dApp can now become a custom Gnosis Safe application by using the [safe-apps-sdk] (https://github.com/gnosis/safe-apps-sdk)

## **Checklist**
- [ ] Verify bridging to custom receiver works by manually interacting with the smart contract
- [ ] Create a simple UI to allow 
  - [ ] users to bridge ERC20 tokens in both directions
  - [ ] specify a custom receiver
  - [ ] pick popular tokens from a token list (with icons) 
  - [ ] specify custom token by address from Mainnet, validating if supported (query rootToChildToken mapping)
- [ ] The UI should be usable as a custom Gnosis Safe App 

## **Acceptance Criteria**
- [ ] UX/UI is functional and not too shabby
- [ ] Code must be clear and well documented
- [ ] App must be ready to use and adequately tested
- [ ] Appropriate disclaimers must be attached to clarify it's not affiliated with Polygon
- [ ] Ownership of the repository transferred to the superfluid-finance org

## **Bounty reward**
100 DAIx if it's proven to be impossible (i.e. assumption on bridge is wrong) 
700 DAIx if completed 

Bounty payable on Polygon in Super DAI (DAIx)

All our bounty payouts require a successful light KYC screening.

**Comment by brymut** [comment]
Hi @hellwolf / @kobuta23 might this still be available to be taken on?

**Comment by kobuta23** [comment]
The Polygon team have created a specific application for gnosis safes, visible here:
https://safe-bridge.polygon.technology/

So the bounty can be considered obsolete. Closing it
