### ISSUE TITLE
[dApp] UI for TOGA 

### ISSUE THREAD

**Issue by kobuta23** [superfluid-finance/protocol-monorepo#479]
## Synopsis

Build a simple UI to view statistics around the TOGA/PIC system, as well as allow current and aspiring PICs to interact with the system. 

## Context

TOGA (Transparent OnGoing Auction) is the system by which the PIC (Patrician in Charge) is selected. The PIC is the address which receives all liquidation rewards (and who pays for all liquidation penalties). 

Anyone can become the PIC by posting a higher stake than the previous PIC. 

All rewards accumulate are part of the stake. The stake (and the rewards) can be drained by the PIC slowly, through a stream.

The system can function without an interface, but having one is very beneficial for the auditability of the system, as well as to aggregate and display current and historical data about PICs. While the system isn't live yet, it is expected to be rolled out shortly.

Toga Contract: [https://github.com/superfluid-finance/protocol-monorepo/blob/dev/packages/ethereum-contracts/contracts/utils/TOGA.sol](https://github.com/superfluid-finance/protocol-monorepo/blob/dev/packages/ethereum-contracts/contracts/utils/TOGA.sol)

## Checklist

Create a web based dApp where:

- [x]  There is an explorable list of existing superTokens, with some details for each:
    - [x]  Total Supply
        - [x]  In number of tokens
        - [x]  Dollar value (CoinGecko API, search by underlying token address)
    - [x]  Number of active streams
    - [x]  Total Value Streamed (Aggregate FlowRate)
    
    PIC DATA:
    
    - [x]  Current PIC address
    - [ ]  Current Bond amount (animated by stream)
    - [ ]  Users can expand by token, showing more solvency information
        - [x]  [Orange] Currently critical streams
        - [x]  [Red] Pirate opportunities
        - [ ]  [Green] Latest liquidations ← and who did them. Show last 20 or so
- [ ]  Users can connect with any wallet using web3modal **(not mandatory, should work without connecting)**
- [x]  If a user is connected, they should be able to send transactions to:
    - [x]  Become the PIC with custom Bond and Exit Rate.
    - [x]  Change their Exit Rate
- [ ]  PIC Profitability so far (Since last PIC change). Showing it as APY
    
    $Bond/(totalRewards - slashedAmount)/seconds$*secondsInAYear → APY
    

## Acceptance criteria

- [x]  UI not too shabby
- [x]  Data correct, and loading not too slow
- [x]  Cross-chain compatibility
- [ ]  Multi-wallet compatibility (Web3Modal)
- [ ]  [Gnosis-Safe App Compatibility](https://github.com/gnosis/safe-apps-sdk/tree/master/packages/safe-apps-web3modal)
- [ ]  Pull Request [to toga-suit repository](https://github.com/superfluid-finance/toga-suit)

## **Bounty reward**

To be discussed with bounty candidate

**Comment by hellwolf** [comment]
To be continued by https://github.com/superfluid-finance/superfluid-stories/issues/128
