### ISSUE TITLE
[SUBGRAPH] Add "CriticalAtTimestamp" entity to Subgraph v1

### ISSUE THREAD

**Issue by kobuta23** [superfluid-finance/protocol-monorepo#480]
Add a new property in the accountTokenSnapshots entity, called "criticalAtTimestamp" which should tell us the timestamp the user will run out of funds in the specific token. This can be calculated based on balance, netFlow, updatedAtTimestamp, and needs to be recalculated every time these values change.

The "criticalAtTimestamp" value can be used to construct fairly simple queries showing all critical accounts:

```{
  accountTokenSnapshots(where: {
    criticalAtTimestamp_lt:"1635258762"
  }){
    account {
      id
    }
  }
}```


While there might be some false positives (the claim function isn't currently indexed) this should still be a very good start to create any solvency related dashboard / alert system, without relying on client-side processing or web3

**Comment by hellwolf** [comment]
It won't take into account IDA distribution received, so it's more of a "optimistic" estimation of "maybeCriticalAtTimestamp".

**Comment by hellwolf** [comment]
replaced by #774
