### ISSUE TITLE
[ETHEREUM-CONTRACTS] Investigate impact of disabling 777 callback on ERC20.transfer for super tokens.

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#485]

**Comment by d10r** [comment]
conclusion:  
The only impact is that Super Tokens would not be strictly ERC-777 compliant anymore. That seems a moot point though as ERC-777 has so far got little adoption anyway. Back when the standard was drafted, there was an expectation of it becoming a/the dominant token standard, which would have resulted in protocol devs being aware of this behaviour. That did however not happen, thus we can assume that all protocol devs are aware of the possibility for ERC20.transfer() to allow reentrancy.
