### ISSUE TITLE
Automate schema.graphql generation for sdk-core

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#523]
When we make breaking changes to the `schema.graphql` file for the subgraph, we need to update this information in the sdk-core as well otherwise the sdk-core build also breaks.
We should have a way to automate the generation of this via a script in package.json.

**Comment by hellwolf** [comment]
automated through npm command `generate-graphql-types`

**Comment by 0xdavinchee** [comment]
I misspoke, this is actually done using `yarn generate-graphql-schema`. 
Reference: https://github.com/superfluid-finance/protocol-monorepo/wiki/Contributor-Modifications-Guide
