### ISSUE TITLE
[SUBGRAPH] TokenStatistic wrongly shows totalSupply 0 for some tokens

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#548]
On xdai, MIVA and FRACTION have a supply of 0 according to the TokenStatistic schema. 
May be related to them being native SuperTokens (no upgrade/downgrade events).

**Comment by hellwolf** [comment]
xDAI is not indexing!!

**Comment by 0xdavinchee** [comment]
@hellwolf xDAI is fully synced and indexed for v1 and dev now
