### ISSUE TITLE
[ETHEREUM-CONTRACTS] deploying IDA logic to Arbitrum fails without explicit gas limit set

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#564]
With gas limit explicit set (to 250M), the framework can be deployed.  
This is however just a workaround and we may hit the issue (probably gas estimation returning a too low value) again in other instances.

When deploying via npm package, the gas settings in truffle-config.js are (currently) ignored and this happens:
```
$ CREATE_NEW_RESOLVER=1 npx truffle --network arbitrum-rinkeby exec node_modules/@superfluid-finance/ethereum-contracts/scripts/deploy-framework.js
...
SlotsBitmapLibrary.new: started
SlotsBitmapLibrary.new: done, gas used 14687114, gas price 0.012655362 Gwei
SlotsBitmapLibrary.new: started
SlotsBitmapLibrary.new: done, gas used 14687146, gas price 0.012655362 Gwei
InstantDistributionAgreementV1.new: started
execution ran out of gas
Truffle v5.4.28 (core: 5.4.28)
Node v14.17.6
```

For comparison - a [successful deployment](https://github.com/superfluid-finance/protocol-monorepo/runs/4458388262?check_suite_focus=true) looked like this:
```
SlotsBitmapLibrary.new: started
SlotsBitmapLibrary.new: done, gas used 23623826, gas price 0.02008047 Gwei
SlotsBitmapLibrary.new: started
SlotsBitmapLibrary.new: done, gas used 23623838, gas price 0.02008047 Gwei
InstantDistributionAgreementV1.new: started
InstantDistributionAgreementV1.new: done, gas used 198061969, gas price 0.02008047 Gwei
New InstantDistributionAgreementV1 address 0x30a6933Ca9230361972E413a15dC8114c952414e
```
Here, the gas limit was explicitly set to 250M for all txs.

The failure may have to do with the linked library contract.

**Comment by hellwolf** [comment]
fixed by specifying build_directory directly in truffle-config.
