### ISSUE TITLE
[TOOLING] speed executing workflows via github actions

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#565]
Currently, when executing a workflow via GH actions, a lot of time is spent for building while execution itself often would take just a few seconds. Example: https://github.com/superfluid-finance/protocol-monorepo/actions/runs/1701417519
We can probably use pre-existing build artifacts in most cases in order to make this less cumbersome.

**Comment by hellwolf** [comment]
deprecated by #1854
