### ISSUE TITLE
[SuperApp] Build a generic SuperPool - Solidity bounty

### ISSUE THREAD

**Issue by kobuta23** [superfluid-finance/protocol-monorepo#569]
_To get started working on this bounty, follow these quick steps: https://docs.superfluid.finance/superfluid/resources/bounty-program_ 

## Synopsis
Create a generic SuperApp which allows users to pool funds.
Users should be able to deposit and withdraw both in traditional ways (one-off transfer/send) and in Superfluid ways, by streaming in or out of the pool. 

## Context
There are a number of integrations with other DeFi protocols that are very interesting to us. They all share the same characteristics of requiring users to deposit/withdraw with one-off transactions. By building an intermediary contract, users would be able to stream in and out of these pools, leveraging Superfluid's functionalities. 

This intermediary contract would be able to pool funds and periodically deposit/withdraw into the existing DeFi protocol. 

The contract developed in this bounty should be built in a generic way in order to become the base for a number of integrations with lending protocols, yield pools, etc. 

The Allocation Strategy should be assumed to have a variable redemption rate to the tokens put in.

## Checklist
- [ ] users are able to deposit and withdraw in one transaction (using ERC777 send) 
- [ ] users can stream deposit and stream withdraw
- [ ] the contract accounts for all deposits/withdrawals accurately
- [ ] there is a "dummy" Allocation Strategy, a pool that the SuperPool can deposit/withdraw unwrapped tokens to/from
- [ ] the SuperPool rebalances at every interaction, keeping a predefined safety margin of superTokens for outgoing streams
- [ ] the SuperPool allows anyone to trigger a rebalance
- [ ] the SuperPool is minimalist and built to be extensible
- [ ] the Allocation Strategy has a variable redemption rate, and the SuperPool handles it properly
- [ ] Code must be clear and well documented (inline + readme)
- [ ] App must be ready to use and adequately tested
- [ ] Appropriate disclaimers must be attached to clarify it's not production ready
- [ ] Ownership of the repository transferred to the superfluid-finance org

## Bounty reward
$4000 paid out in stablecoins on Polygon of choice. 

All our bounty payouts require a successful light KYC screening. See [Completion info](https://docs.superfluid.finance/superfluid/resources/bounty-program#upon-completion)

![image](https://user-images.githubusercontent.com/6445649/150397412-c0b36d10-24f1-4d69-a50b-139b1462f462.png)

**Comment by Lewington-pitsos** [comment]
Hi @hellwolf, thinking of working on this very shortly, but need more clarity. Can you give an example of an existing "SuperPool/SuperApp" or provide a link to one which exists in another service?

Cheers

**Comment by Lewington-pitsos** [comment]
Hi @hellwolf, thinking of working on this very shortly, but need more clarity. Can you give an example of an existing "SuperPool/SuperApp" or provide a link to one which exists in another service?

Cheers

**Comment by dantheman8300** [comment]
Hi @sunnyjaycer, I'm interested in taking on this bounty:
Expected Completion Date: 8/15/22

**Comment by must479** [comment]
how claim bounty

**Comment by hellwolf** [comment]
We should use IDA more here to settle the  `pendingDistributionFromPoolPerUnitOfOwnerShip`.

This can be a very common pattern.

**Comment by kobuta23** [comment]
it's not that easy. The `pendingDistributionFromPoolPerUnitOfOwnerShip` change every second as user can be streaming in/out of the pool. So IDA unit mapping to `unitOfOwnership` could be impossible

**Comment by 3scava1i3r** [comment]
Just confirming if this bounty is done?
