### ISSUE TITLE
[SUBGRAPH BUG] Faulty Token Entity added

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#605]
**Describe the bug:**
A clear and concise description of what the bug is. What is the data you are having issues with?
Token
**Subgraph endpoint:** https://thegraph.com/hosted-service/subgraph/superfluid-finance/protocol-v1-goerli

**Query:**
e.g. 
```
query getTokens {
  tokens(first: 1000) {
    id
    symbol
    name
  }
}
```

**Expected data:**
There shouldn't be any token with address `0xffff...` and no name and no symbol.

**Actual data:**
There is a token added with address `0xffff...` and no name and no symbol.

**Screenshots:**

**Additional context:**
It doesn't appear that this happens on any other endpoint.

**Comment by 0xdavinchee** [comment]
looks like this is because of the `NOTx` token on Goerli: 
```
{
        "id": "0x8809061412e896375e5e6b9fc404d1796e992bf2",
        "symbol": "NOTx",
        "name": "NotSuperToken",
        "underlyingToken": {
          "id": "0xffffffffffffffffffffffffffffffffffffffff"
        }
      },
```

**Comment by hellwolf** [comment]
not an issue, when front end is using curated list, will live with it for now
