### ISSUE TITLE
[ETHEREUM-CONTRACTS] Use proxy verification feature of truffle-plugin-verify

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#620]
See

https://github.com/rkalis/truffle-plugin-verify/issues/80

&

https://github.com/rkalis/truffle-plugin-verify/pull/166

**Comment by hellwolf** [comment]
It's being fixed in https://github.com/rkalis/truffle-plugin-verify/pull/166

**Comment by hellwolf** [comment]
https://github.com/rkalis/truffle-plugin-verify/releases/tag/v0.5.27
https://github.com/rkalis/truffle-plugin-verify/releases/tag/v0.5.28

released since.
