### ISSUE TITLE
[WORKFLOW] Optimize tasks/check-changeset.sh using MERGE_HEAD

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#640]
## Background

Due to the nature of monorepo, `tasks/check-changeset.sh` is used in several github workflows to detect what packages has code changes against the merging branch.

## Problem

But the way it is done is checking change set against `dev` branch, but often the feature branch is out of sync with the `dev` branch. It would be more resource-saving if changeset is tested against the `MERGE_HEAD`.

## Task

Your task is make `tasks/check-changeset.sh` work against some `MERGE_HEAD` instead, so that one can continue to develop in the feature branch behind the `dev` branch without triggering all the unnecessary test cases.

## Bounty reward

250 DAIx payable on Polygon in Super DAI (DAIx)

**Comment by samirsalem** [comment]
Hello there, I would like to work on this issue

**Comment by joeljesu** [comment]
As per 5/11 convo w/ @hellwolf, too specialized for a bounty. Best for external freelancer/contractor
