### ISSUE TITLE
[WORKFLOW] Optimize pull request packages build process

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#641]
## Background

To make testing of feature branch builds easy, currently all pull requests create its own PR npm packages published to the _github package registry_. More about the process can be found in https://github.com/superfluid-finance/protocol-monorepo/wiki/Branch-Policy

## Problem

Currently the workflow is not done in a very resource conscious fashion. Each commits would trigger a PR package publish, and they are never cleaned up after the pull requests are closed.

## Proposed Solution

- Use workflow_call more
- We would want to trigger the PR builds by commenting in the pull request something like "Bot, please #build-pr-packages".
- Create A github periodical job to cleanup of stale PR packages in github registry.

## Bounty reward

500 DAIx payable on Polygon in Super DAI (DAIx)

**Comment by zhyd1997** [comment]
Hi @hellwolf 

I'm glad to work on this issue, and 2 questions:
1. should a new PR trigger `Create PR Artifacts`? 
  if not, I will change `cd.feature.create-pr-artifact.yml` file instead of `handler.publish-pr-packages.yml`.
2. which role `collaborator`, `owner` can comment something like `Bot, please #build-pr-packages`?

**Comment by hellwolf** [comment]
Hi @zhyd1997, thanks for taking it!

1) The reason `handler.publish-pr-packages.yml` is separated out is because for external pull requests they cannot access repo secrets hence publish new packages using. 
  a ) I do want to note also though, `handler.publish-pr-packages.yml` currently has a race condition, since it uses `workflow_run` event, which always fetches the latest "workflow". Perhaps using `workflow_call ` from `cd.feature.create-pr-artifact.yml` is a better approach.
  b ) To your question directly, I think it would be good actually trigger a build when a ready-state PR (not in draft status) is created.  #build-pr-packages could be used as a refresher build, which always also post a new github bot comments after the build succeeds.

2 ) Both collaborators and owners.

**Comment by samirsalem** [comment]
@hellwolf As you asked me yesterday I'll review the current process and propose some improvements

**Comment by joeljesu** [comment]
No longer needed according to convo w/ @hellwolf on 5/11
