### ISSUE TITLE
[Examples] Re-Write Example Application Using the CFA Library

### ISSUE THREAD

**Issue by saflamini** [superfluid-finance/protocol-monorepo#648]
## **Synopsis**

Re-write a Superfluid example from our examples repository using the CFA Library.

For each createFlow, updateFlow, or deleteFlow operation in the example contracts within the example, you should replace the host.callAgreement(...) pattern with a call that makes use of the CFA Library.

Note: if you wish to complete this bounty, please reach out to the Superfluid team in discord by DM’ing Sam F | Superfluid #0902 or tagging Sam F | Superfluid or Fran | Superfluid in the #find-a-builder channel.

## **Context**

The Superfluid team recently pushed a new solidity library which makes creating, updating, and deleting streams much easier. 

To create, update, or delete a flow, you need to make a call to the Superfluid host contract’s callAgreement function, and pass in the CFA address, an encoded transaction object which includes the operation you’d like completed on the constant flow agreement contract, and an optional userData value. It currently looks like this:

```jsx
//creating a flow in pure solidity
_host.callAgreement(
	cfa,
	abi.encodeWithSelector(
		cfa.createFlow.selector,
		token,
		receiver,
		flowRate
		new bytes(0) // placeholder - always pass in bytes(0)
	),
	"0x" //userData
);
```

The CFA Library abstracts this logic away from developers, allowing you to work with streams using syntax that looks a lot like the Superfluid SDK Core:

```jsx
// CFA CRUD functionality
cfaV1.createFlow(receiver, token, flowRate);
cfaV1.updateFlow(receiver, token, flowRate);
cfaV1.deleteFlow(sender, receiver, token);
```

You can read more about the CFA library and get more information on using it inside of our [[docs](https://docs.superfluid.finance/superfluid/protocol-developers/solidity-examples)](https://docs.superfluid.finance/superfluid/protocol-developers/solidity-examples).

You can see an example of the CFA library in action inside of [[this version](https://github.com/superfluid-finance/protocol-monorepo/blob/dev/packages/ethereum-contracts/contracts/mocks/CFALibraryMock.sol)](https://github.com/superfluid-finance/protocol-monorepo/blob/dev/packages/ethereum-contracts/contracts/mocks/CFALibraryMock.sol) of the tradeable cashflow contract which is used for testing the library.

The updates you make to each contract should be limited to initializing the CFA library and replacing the Superfluid `host.callAgreement(...)` syntax with the CFA library syntax for each CFA operation. You do NOT need to make any changes associated with the instant distribution at this time. Your updates should pass all tests. 

To complete this bounty, create a new bounty

## **Checklist**

- [ ]  CFA Library is imported and initialized as seen in [[this example](https://github.com/superfluid-finance/protocol-monorepo/blob/dev/packages/ethereum-contracts/contracts/mocks/CFALibraryMock.sol)](https://github.com/superfluid-finance/protocol-monorepo/blob/dev/packages/ethereum-contracts/contracts/mocks/CFALibraryMock.sol)
- [ ]  All create, update, and delete flow operations have been replaced with the corresponding CFA library operation
- [ ]  All tests pass

## **Acceptance Criteria**

- [ ]  CFA Library is initialized and imported
- [ ]  All CFA operations are done using the CFA library
- [ ]  No other solidity code was changed outside of the import & initialization of the library, and swapping out of the host.callAgreement(...) pattern for the CFA library syntax where applicable. You also may remove redundant references to Superfluid contract addresses where applicable.
- [ ]  All tests pass

## **Bounty reward**

100 DAIx payable on Polygon in Super DAI (DAIx) for each example completed

All our bounty payouts require a successful light KYC screening.

**Comment by joeljesu** [comment]
Beginning work with budget NFT example :)
