### ISSUE TITLE
[WORKFLOW] ci.canary broken at NPMJS publishing step

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#649]
A pull request attempting to fix it is still failing: https://github.com/superfluid-finance/protocol-monorepo/pull/647

The context is that upgrading node to 16.x and, the need to change package.json repository syntax for monorepo doesn't seem to jive well with the current npm publishing step. Please help us to fix it.

# Bounty reward

200 DAIx payable on Polygon in Super DAI (DAIx)

**Comment by samirsalem** [comment]
As discussed i'm working on it

**Comment by samirsalem** [comment]
I’ve found a way to correct this and it is using built in GitHub actions for node publishing , to properly fix and submit a PR I would like to know what is the use case of tagging the npm packages? In witch way do you use tags? Can the tag be the short sha of the commit for example? 
For the moment the idea is to limit usage of bash scripts called from outside the runners execution context, and declare most of the variables in workflow file.
This will make debugging easier in the future
The  bash scripts should probably be substituted with workflow calls.
@hellwolf  let me know if this approach suits your needs

**Comment by hellwolf** [comment]
> to properly fix and submit a PR I would like to know what is the use case of tagging the npm packages? In witch way do you use tags? Can the tag be the short sha of the commit for example?

https://www.npmjs.com/package/@superfluid-finance/sdk-core e.g.

![image](https://user-images.githubusercontent.com/186660/155691037-7a7fda4e-b805-4317-9384-d040cedcf843.png)

they are tags to give unique names to different builds

**Comment by hellwolf** [comment]
>  For the moment the idea is to limit usage of bash scripts called from outside the runners execution context, and declare most of the variables in workflow file.
> This will make debugging easier in the future
> The bash scripts should probably be substituted with workflow calls.

I would actually propose we put "set -ex" to all bash scripts if not yet, that should still make things easy to debug where each command is visible, while keeping the scripts reusable.

**Comment by samirsalem** [comment]
Ok, thanks, got it !

**Comment by hellwolf** [comment]
Fixed https://github.com/superfluid-finance/protocol-monorepo/actions/runs/1921757371
