### ISSUE TITLE
[SUBGRAPH] Add ´buffer´ property to streams

### ISSUE THREAD

**Issue by kasparkallas** [superfluid-finance/protocol-monorepo#652]
"Buffer" is another word for "deposit".

**Why?**

The buffer is an essential part of the constant flow agreements so the data should be available on the Subgraph.

It's not correct to calculate the buffer amount on the client-side because the buffer amount is configurable in the protocol [1] and can differ in time and on different networks.

[1] See `_LIQUIDATION_PERIOD_CONFIG_KEY` & `_SUPERTOKEN_MINIMUM_DEPOSIT_KEY`

**How?**

Make changes to the Subgraph mapping logic in `/packages/subgraph`.

Ask @hellwolf for optimal way to find the necessary data.

**Other**

* Are there any other entities besides `Stream` to include the `buffer`?

**Comment by msoni89** [comment]
@kasparkallas It's already addressed by @0xdavinchee and it's in a pending version of the subgraph.

field name deposit, not a buffer.
