### ISSUE TITLE
[SUBGRAPH] Add a property to order events chronologically

### ISSUE THREAD

**Issue by kasparkallas** [superfluid-finance/protocol-monorepo#654]
**Why?**

I'd like to do a simple query and retrieve events in chronologically correct order. Currently ordering events by block number or timestamp does not give perfect results because many events can be included in the same block. Log index is used to create ordering inside the block but just adding `logIndex` to events won't suffice because Subgraph doesn't support ordering by more than 1 field.

**How?**

Add a string field to events that combines both block number and log index. Should be pretty simple change to common mapping logic of events in `/packages/subgraph`. For example: `“${blocknumber}-${logIndex}”`.

**Notes**

* The log index needs to be zero padded in the front to avoid "${blocknumber}-12" being ordered before "${blocknumber}-2". So it should be "${blocknumber}-012" and "${blocknumber}-002" respectively.
* How much zero padding? https://ethereum.stackexchange.com/questions/99910/whats-the-maximum-number-of-logs-per-transaction

**Comment by msoni89** [comment]
@kasparkallas that will not be going to work for order because we are only padding log-Index not thinking about blocknumber.

See the below example: 
```
["28152388-03" , "28152388-01", "28152388-00"]

sorted : ["28152388-00", "28152388-01", "28152388-03"]

what if  ["128152388-03" ,"28152388-03" , "28152388-01", "28152388-00"]

sorted:  ["128152388-03", "28152388-00", "28152388-01", "28152388-03"]
```

If you only need this for ordering then we could do one thing sum block number with log index `(blocknumber + logIndex)`  and save it as order, then we don't need to do padding and unnecessary space.

**Comment by kasparkallas** [comment]
> @kasparkallas that will not be going to work for order because we are only padding log-Index not thinking about blocknumber.
> 
> See the below example:
> 
> ```
> ["28152388-03" , "28152388-01", "28152388-00"]
> 
> sorted : ["28152388-00", "28152388-01", "28152388-03"]
> 
> what if  ["128152388-03" ,"28152388-03" , "28152388-01", "28152388-00"]
> 
> sorted:  ["128152388-03", "28152388-00", "28152388-01", "28152388-03"]
> ```
> 
> If you only need this for ordering then we could do one thing sum block number with log index `(blocknumber + logIndex)` and save it as order, then we don't need to do padding and unnecessary space.

Nice realization! Yep, love the summing approach. EDIT: Wait, this wouldn't work...

**Comment by msoni89** [comment]
> > @kasparkallas that will not be going to work for order because we are only padding log-Index not thinking about blocknumber.
> > See the below example:
> > ```
> > ["28152388-03" , "28152388-01", "28152388-00"]
> > 
> > sorted : ["28152388-00", "28152388-01", "28152388-03"]
> > 
> > what if  ["128152388-03" ,"28152388-03" , "28152388-01", "28152388-00"]
> > 
> > sorted:  ["128152388-03", "28152388-00", "28152388-01", "28152388-03"]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If you only need this for ordering then we could do one thing sum block number with log index `(blocknumber + logIndex)` and save it as order, then we don't need to do padding and unnecessary space.
> 
> Nice realization! Yep, love the summing approach.

this one also not going to work, lets pad block number as well till 12 left shift. Thanks @hellwolf

**Comment by msoni89** [comment]
128184007 * 1000 + 813 = 128184007813
(block number) * (multiplier) + (logIndex)

**Comment by hellwolf** [comment]
713 was the limit per the link in the description

but maybe using 10000 just to be a bit paranoid

**Comment by msoni89** [comment]
@hellwolf @kasparkallas as per https://github.com/superfluid-finance/protocol-monorepo/issues/453

We already covered event entities, do you want me to add order also in HOL entities?
