### ISSUE TITLE
[SUBGRAPH] Add a canonical symbol property to tokens (currently search by token symbol is case-sensitive)

### ISSUE THREAD

**Issue by kasparkallas** [superfluid-finance/protocol-monorepo#655]
**Why?**

To make searching for tokens by symbol in front-end applications simple. Currently search by token symbol of http://console.superfluid.finance/ is case-sensitive but it's better UX for it to not be.

**How?**

Add a lower-cased token symbol to token entity. Should be pretty simple change to common mapping logic of events in `/packages/subgraph`.

**Notes**

* Maybe full-text search field (https://thegraph.com/docs/en/developer/create-subgraph-hosted/#defining-fulltext-search-fields) could cover this use-case and more at the same time?

**Comment by msoni89** [comment]
@kasparkallas How full-text search field will make it a case insensitive?

**Comment by kasparkallas** [comment]
I'll close this because Subgraph now automatically generates `_nocase` indexes/filters.

For example: `Token.symbol_contains_nocase`
