### ISSUE TITLE
New Super App Deployment - [KEY NEEDED]

### ISSUE THREAD

**Issue by saflamini** [superfluid-finance/protocol-monorepo#660]
# Link to repo of the contract to be deployed
https://github.com/billyjitsu/brightstream

# Contact info for developer who wants to deploy
billy@billycampana.com

# Chain to be deployed on
gnosis chain

# Basic description of the Super App being deployed
An NFT that will given away to a few participants that will have a fluid stream of $Bright token to it.  Changeable uri with the super app callbacks.  Just a fun way to test out ideas in real time and promote superfluid usage

cc @hellwolf

**Comment by hellwolf** [comment]
@saflamini, @ngmachado is taking on this

Btw, I forgot to mention that as part of the process, deployer address should also be mentioned here. @ngmachado will explain here.

**Comment by hellwolf** [comment]
inactive ticket, close for now
