### ISSUE TITLE
[ETHEREUM-CONTRACTS] Review contracts verification pipeline

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#667]
Let's review how the current contracts verification pipeline work, and what can be done differently and improved.

## Current problems

- https://github.com/superfluid-finance/protocol-monorepo/issues/319
- https://github.com/superfluid-finance/protocol-monorepo/issues/620
- arbitrum verificaiton of SuperToken logic contract.

## Questions

- Blockscout support? To support open source tooling. And xdai support as a bonus.
- Avascan? Group hug, they could integrate the streaming balance view natively.
- hardhat contracts verification? Reducing truffle dependency, or at least leverage its sourcify verification ability.

## TODOs

- [x] Create a technical notes on the subject based on the review

**Comment by d10r** [comment]
check if the task could be made repeatable in GH actions in order to be able to manually retry in order to fix a failing pipeline.

Example failure: https://github.com/superfluid-finance/protocol-monorepo/runs/5391474452?check_suite_focus=true

**Comment by hellwolf** [comment]
https://github.com/superfluid-finance/protocol-monorepo/wiki/About-Contracts-Verification

@d10r have a look, if good, let's close this

**Comment by d10r** [comment]
Here's a test run for arbitrum-rinkeby for a from-scratch framework deployment:
```
$ source tasks/etherscan-verify-framework.sh arbitrum-rinkeby
++ TRUFFLE_NETWORK=arbitrum-rinkeby
++ echo TRUFFLE_NETWORK=arbitrum-rinkeby
TRUFFLE_NETWORK=arbitrum-rinkeby
++ echo NETWORK_ID=421611
NETWORK_ID=421611
++ case $TRUFFLE_NETWORK in
++ echo 'arbitrum-rinkeby is testnet'
arbitrum-rinkeby is testnet
++ IS_TESTNET=1
++ echo SUPERFLUID_HOST
SUPERFLUID_HOST
++ npx truffle --network arbitrum-rinkeby run verify Superfluid@0x307d5871f63FF1b1756864f7B8CA3F67e0571641
Verifying Superfluid@0x307d5871f63FF1b1756864f7B8CA3F67e0571641
Verifying proxy implementation at 0x18d372663b9c080988e9fcb2a0f58c5c772d11e7
Fail - Unable to verify
Failed to verify 1 contract(s): Superfluid@0x307d5871f63FF1b1756864f7B8CA3F67e0571641
++ echo SUPERFLUID_GOVERNANCE
SUPERFLUID_GOVERNANCE
++ '[' '!' -z 1 ']'
++ npx truffle --network arbitrum-rinkeby run verify TestGovernance@0xc0c8b94a05e0FeB2ee23Ed05081b9930CC436478
Verifying TestGovernance@0xc0c8b94a05e0FeB2ee23Ed05081b9930CC436478
Pass - Verified: https://testnet.arbiscan.io/address/0xc0c8b94a05e0FeB2ee23Ed05081b9930CC436478#code
Successfully verified 1 contract(s).
++ echo SUPERFLUID_SUPER_TOKEN_FACTORY
SUPERFLUID_SUPER_TOKEN_FACTORY
++ npx truffle --network arbitrum-rinkeby run verify SuperTokenFactory@0x5893AE98662b828FEB69a5950C59A12c3C974a94
Verifying SuperTokenFactory@0x5893AE98662b828FEB69a5950C59A12c3C974a94
Verifying proxy implementation at 0x33ff6cfa1ce97afd52d77cf93302d8610ce49db9
Pass - Verified: https://testnet.arbiscan.io/address/0x5893AE98662b828FEB69a5950C59A12c3C974a94#code
Successfully verified 1 contract(s).
++ echo SUPERFLUID_SUPER_TOKEN_LOGIC
SUPERFLUID_SUPER_TOKEN_LOGIC
++ '[' -z '' ']'
+++ node -e 'console.log("0x307d5871f63FF1b1756864f7B8CA3F67e0571641".toLowerCase().slice(2).padStart(64, "0"))'
++ SUPERFLUID_SUPER_TOKEN_LOGIC_CONSTRUCTOR_ARGS=000000000000000000000000307d5871f63ff1b1756864f7b8ca3f67e0571641
++ npx truffle --network arbitrum-rinkeby run verify SuperToken@0xDd91EBf2c9A5093D51140F4DDe90AfD4BEB529EA --forceConstructorArgs string:000000000000000000000000307d5871f63ff1b1756864f7b8ca3f67e0571641
Verifying SuperToken@0xDd91EBf2c9A5093D51140F4DDe90AfD4BEB529EA
Unable to locate ContractCode at 0xDd91EBf2c9A5093D51140F4DDe90AfD4BEB529EA
Failed to verify 1 contract(s): SuperToken@0xDd91EBf2c9A5093D51140F4DDe90AfD4BEB529EA
++ echo CFA
CFA
++ npx truffle --network arbitrum-rinkeby run verify ConstantFlowAgreementV1@0x51395Ef84b192f929F665153ac578577db008A8B
Verifying ConstantFlowAgreementV1@0x51395Ef84b192f929F665153ac578577db008A8B
Verifying proxy implementation at 0xc8aa287591c4ee226060f65224ef9304e92be901
Pass - Verified: https://testnet.arbiscan.io/address/0x51395Ef84b192f929F665153ac578577db008A8B#code
Successfully verified 1 contract(s).
++ echo SlotsBitmapLibrary
SlotsBitmapLibrary
++ npx truffle --network arbitrum-rinkeby run verify SlotsBitmapLibrary@0xb3d5522da454d804bcaffb1177686c8cbb2094b2
Verifying SlotsBitmapLibrary@0xb3d5522da454d804bcaffb1177686c8cbb2094b2
Pass - Verified: https://testnet.arbiscan.io/address/0xb3d5522da454d804bcaffb1177686c8cbb2094b2#code
Successfully verified 1 contract(s).
++ echo IDA
IDA
++ cp -f build/contracts/InstantDistributionAgreementV1.json build/contracts/InstantDistributionAgreementV1.json.bak
++ jq -s '.[0] * .[1]' build/contracts/InstantDistributionAgreementV1.json.bak /dev/fd/63
+++ cat
++ npx truffle --network arbitrum-rinkeby run verify InstantDistributionAgreementV1@0x1cf4E822645AEF7AF6204Af80fbba3B216bE73dF
Verifying InstantDistributionAgreementV1@0x1cf4E822645AEF7AF6204Af80fbba3B216bE73dF
Pass - Verified: https://testnet.arbiscan.io/address/0x1cf4E822645AEF7AF6204Af80fbba3B216bE73dF#code
Successfully verified 1 contract(s).
++ mv -f build/contracts/InstantDistributionAgreementV1.json.bak build/contracts/InstantDistributionAgreementV1.json
++ set +x
```

Failed contracts: Superfluid logic and SuperToken logic.

Note that I've removed the `-e` flag from `set -xe` in order to not let the script exit on first command failing.  
That's a change we could push, because giving up is not really helpful here as it just leads to less contracts being verified. 
Caveat: that wouldn't flag the job as failed. If we think that's important, we could still internally keep track of failures and return an error code at the end.

**Comment by d10r** [comment]
What I think we should do:
* ([DONE](https://www.notion.so/superfluidhq/New-Network-Deployment-Template-40e63b76b2f14c0d8b8d91bfb5a971f0)) amend the "new network deployment" process to include the manual verification of the proxy contracts. Even if the plugin gets fixed, afaik we still need to manually mark the contract as proxy via the explorer UI ("More options" -> "Is this a proxy?")
* create a spike for sourcify verification with hardhat-deploy plugin. This could solve/improve several issues:
  * have contracts verified on blockscout-based explorers (currently: Gnosis Chain, in the future maybe Celo)
  * have contracts verified on avascan for the C-chain
  * data availability in a non-centralized repository. This would be more web3 compliant and imo also be an acceptable mitigation of issues on etherscan-like explorers like arbiscan

**Comment by hellwolf** [comment]
created tickets for the spike https://github.com/superfluid-finance/protocol-monorepo/issues/898

**Comment by hellwolf** [comment]
@d10r https://github.com/superfluid-finance/protocol-monorepo/pull/900

**Comment by hellwolf** [comment]
All comments are addressed in new spikes or ongoing RPs, closing this one so we can close this milestone.
