### ISSUE TITLE
App whitelisting by trusted deployer

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#672]
We should be able to trust a deploy for up to a period of time, this way we could lightening our overhead of app whitelisting process without bigger compromise in its setup.

## TODOs

- [ ] Make utils/SuperAppFactoryDelegate.sol part of the full flow (deploy-framework.js).
  - Register register resolver key "SuperAppFactoryDelegate-v1"
  - Piggyback: register resolver key "BatchLiquidator-v1"
  - Design point: should we allow registerAppDelegate to be called outside of app's constructor
- [ ] Update test code and documentations to use the new paradigm
- [ ] ...?

--

## Deprecated Notes

- Extend `Superfluid.registerApp` with new logic that it will check if the tx.origin(the deployer) is whitelisted and within its expiration date.
- Extend `SuperfluidBaseGoverance` with deployer whitelisting with expiration date logic.

**Comment by d10r** [comment]
Observation: allowing the registration action to be done in a tx different from the actual SuperAll deployment tx is potentially problematic as somebody may frontrun the registration and start a stream to the SuperApp before callbacks are invoked.  
It's not clear if this could pose issues, may at least lead to unexpected state (e.g. net incomfing flowrate > 0 when SuperApp-internal accounting doesn't expect that). This may however happen independently of this atomicity, e.g. if the SuperApp address is known before deployment and somebody starts a stream to that address before deployment.
To be taken in mind however, should probably also be mentioned somewhere in the docs.

Currently, `registerAppByFactory` doesn't enforce atomic registration. Could however be enforced by whitelisting only contracts which do deployment and registration in the same tx.  
Once we transition to permissionless SuperApp registration, atomicity is enforced (assuming the current implementation remains) by `registerApp`.

**Comment by d10r** [comment]
done something else instead: https://github.com/superfluid-finance/protocol-monorepo/pull/769
