### ISSUE TITLE
[WORKFLOW] Timing glitch in code coverages publishing sequence

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#676]
BUG: When sdk-core code coverage is pushed, temporarily ethereum-contracts code coverage is 0% until it is also pushed.

The fix: Aggregate the code coverage artifacts and publish them in the end.

Workflow file: .github/workflows/ci.canary.yml

## Bounty reward

100 DAIx payable on Polygon in Super DAI (DAIx)

**Comment by 3scava1i3r** [comment]
I'd like to work on this

**Comment by hellwolf** [comment]
@3scava1i3r sounds great! can you briefly state your understanding of the problem and planned fix? Then I will assign this to you!
