### ISSUE TITLE
[ETHEREUM-CONTRACTS] ERC-712 type signature based meta tx support

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#68]
# Rationale

With typed signature specified in ERC-712, batch operations could be signed in a human readable way in supported wallet interface.

It provides a great UX improvement, as an alternative to the radspec approach.

Target release: v0.2

# Spec

- TODO

# ACs

- TODO

# Notes

- function selector could be part of the typed signature, looking like "foobar(address,uint256)". The function name part is the human readable part, however the parameter list unfortunately cannot be ommitted.
- the signed signature could be relayed as a meta tx, and be broadcasted by the user directly.
- should review delegatable framework for composable 712 signatures.

**Comment by 0xdavinchee** [comment]
https://delegatable.org/

**Comment by hellwolf** [comment]
Closing in favor of https://github.com/superfluid-finance/protocol-monorepo/issues/1782
