### ISSUE TITLE
Ricochet Exchange v2 Markets

### ISSUE THREAD

**Issue by mikeghen** [superfluid-finance/protocol-monorepo#700]
**Describe the SuperApp:**

Ricochet Exchange

**Network will be deployed?:**
Polygon

**Deployer address:**
0x3226C9EaC0379F04Ba2b1E1e1fcD52ac26309aeA

**Factory address:**
NA

**Link of repo of the contract to be deployed:**
https://github.com/Ricochet-Exchange/ricochet-protocol

**Contact info for developer:**
@mikeghen

**Notes:**
Please give me a batch of 10 keys

**Comment by hellwolf** [comment]
```
ricochet-700-1
...
ricochet-700-10
```

@mikeghen here you go.

Please be aware that we will start to whitelisting on a deployer address with an expiration date basis soon. Please prepare a deployer address you'd like to be whitelisted.

**Comment by mikeghen** [comment]
Thank you @hellwolf 🙌
