### ISSUE TITLE
Return params naming doesn't match

### ISSUE THREAD

**Issue by ngmachado** [superfluid-finance/protocol-monorepo#701]
Different naming between interface and implementation.

https://github.com/superfluid-finance/protocol-monorepo/blob/ccef7b7e274697f33ea2a8b81ae873f9fb68b797/packages/ethereum-contracts/contracts/interfaces/agreements/IConstantFlowAgreementV1.sol#L57

https://github.com/superfluid-finance/protocol-monorepo/blob/590735474c141004b75a3b0bea9de5bc2b115932/packages/ethereum-contracts/contracts/agreements/ConstantFlowAgreementV1.sol#L128

**Comment by 0xdavinchee** [comment]
https://github.com/superfluid-finance/protocol-monorepo/pull/747
