### ISSUE TITLE
[ETHEREUM-CONTRACTS]  CFA ACL Support

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#702]
CFA ACL (access control list) allows other operators to change flows other than the standard semantics of flow sender/receiver/liquidator.

## Checklist

- [ ] Technical note to be created: "About CFA ACL"
- [x] Implement the CFA ACL per spec of protocol-forum-4
- [x] Implement test cases

## Spec protocol-forum-4

**ABI**

* `CFA.authorizeFlowOperator(token, sender, flowOperator, permission, maxFlowRate)`
* `CFA.authorizeFlowOperatorWithFullControl`  -> `CFA.authorizeFlowOperator(token, sender, ALL, MAX_INT96)`
* `CFA.revokeFlowOperatorWithFullControl` ->  `CFA.authorizeFlowOperator(token, sender, NONE, 0)`

**Event**

* `FlowOperatorUpdated(token indexed, sender indexed, flowOperator indexed, permissions, maxFlowRate, usedMaxFlowRate)`

**Storage Layout**

AgreementData/AgreementContractData of CFA

- FlowData  (256 bits)
   - Id: flowId - `keccak256(abi.encode(sender, receiver))`
   - encoding: ...
- FlowOperatorData (256 bits)
   - Id: flowOperatorId - `keccak256(abi.encode("flowOperator", sender, flowOperator))`
   - encoding: `(permissions: octal bitmask, maxFlowRate: Int96)`
   - trivial case/backward compatibility: data == 0, no permission

**Comment by 0xdavinchee** [comment]
I believe we should have events for the different actions too:
- `event CreateOrUpdateFlowByAuthorized(ISuperfluidToken indexed token, address indexed sender, address indexed flowOperator, int96 maxFlowRate)`
- `event CreateOrUpdateFlowByRevoked(ISuperfluidToken indexed token, address indexed sender, address indexed flowOperator)`
- `event DeleteFlowByAuthorized(ISuperfluidToken indexed token, address indexed sender, address indexed flowOperator)`
- `event DeleteFlowByRevoked(ISuperfluidToken indexed token, address indexed sender, address indexed flowOperator)`

**Comment by hellwolf** [comment]
should be

```
Event

    FlowOperatorUpdated(token indexed, sender indexed, flowOperator indexed, permissions, maxFlowRate)

```

Instead

**Comment by 0xdavinchee** [comment]
I believe something that we didn't specify in the different ABI functions is that they all need to take ctx as an argument - I am assuming that the user must call these different functions via the host contract otherwise anyone can just set themselves as flowOperator for any sender - unless we remove the sender parameter and use msg.sender instead, this may lead to less flexibility
