### ISSUE TITLE
[ETHEREUM-CONTRACTS] fix token listing script

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#704]
`scripts/resolver-list-super-token.js` is now failing with 
```
TypeError: ac.getRoleMemberCount is not a function
    at setResolver (/home/runner/work/protocol-monorepo/protocol-monorepo/packages/ethereum-contracts/scripts
```
It's not yet clear why that happens. Works locally. May be related to the upgrade to Solidity 0.8.

**Comment by hellwolf** [comment]
It's related to OZ 4

AccessControl in OZ3 should be now AccessControlEnumerable https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/access/AccessControlEnumerable.sol

**Comment by hellwolf** [comment]
let's fix it

**Comment by hellwolf** [comment]
Fixed a while ago in Resolver.sol
