### ISSUE TITLE
[ETHEREUM-CONTRACTS] failed when  install @superfluid-finance/ethereum-contracts v1.1.0

### ISSUE THREAD

**Issue by yuliyu123** [superfluid-finance/protocol-monorepo#714]
when install superfluid-finance by
`yarn add @superfluid-finance/ethereum-contract` failed, seems ethereum-contracts v1.1.0 conflict with solidity-stringutils.

Details:
➜  ~ yarn add @superfluid-finance/ethereum-contracts
yarn add v1.22.17
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
warning @superfluid-finance/ethereum-contracts > ethereumjs-tx@2.1.2: New package name format for new versions: @ethereumjs/tx. Please update.
warning @superfluid-finance/ethereum-contracts > @truffle/contract > @ensdomains/ensjs > @ensdomains/ens@0.4.5: Please use @ensdomains/ens-contracts
warning @superfluid-finance/ethereum-contracts > @truffle/contract > @ensdomains/ensjs > @ensdomains/resolver@0.2.4: Please use @ensdomains/ens-contracts
warning @superfluid-finance/ethereum-contracts > @truffle/contract > ethers > uuid@2.0.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @superfluid-finance/ethereum-contracts > @truffle/contract > @ensdomains/ensjs > @ensdomains/ens > testrpc@0.0.1: testrpc has been renamed to ganache-cli, please use this package from now on.
error An unexpected error occurred: "https://raw.githubusercontent.com/Arachnid/solidity-stringutils/46983c6d9462a80229cf0d5bab8ea3b3ee31066c/package.json: connect ECONNREFUSED 0.0.0.0:443".
info If you think this is a bug, please open a bug report with the information provided in "/Users/looperX/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by hellwolf** [comment]
To be fixed by https://github.com/superfluid-finance/protocol-monorepo/pull/715

And to be released as v1.1.1.
