### ISSUE TITLE
[INTEGRATION] Add Super Token price adapter to Gnosis Safe Transaction Service

### ISSUE THREAD

**Issue by vmichalik** [superfluid-finance/protocol-monorepo#732]
_More technical oversight needed for path to completion and Acceptance Criteria_

Display eligible Super Tokens with the price data of their underlying tokens. e.g. USDCx = USDC price, MATICx = MATIC price, as they are 1:1 exchangeable.

**Background**

- Currently, many Superfluid Super Tokens display as 0 balances, but they are 1:1 wrappers around existing tokens with known prices. Super Tokens exist on Gnosis Chain, Polygon, Arbitrum and Optimism mainnets.
- Several Super Token prices have been hardcoded per https://github.com/gnosis/safe-transaction-service/issues/772 but an adapter would allow for accurate prices for all Super Tokens with an underlying token.
- An example adapter exists here:  https://github.com/gnosis/gnosis-py/blob/master/gnosis/eth/oracles/oracles.py

**Checklist**

- [ ] Users are able to view the prices of any Super Token on Gnosis Safe beyond the ones that are currently hardcoded

A good indicator for success would be to look at the [Ricochet DAO Gnosis Safe](https://gnosis-safe.io/app/matic:0x9C6B5FdC145912dfe6eE13A667aF3C5Eb07CbB89/balances) and see if these non-hardcoded tokens (SUSHI, IDLE, MKR) have their expected prices
       
![image](https://user-images.githubusercontent.com/62968241/169838843-3a09a953-2769-499b-960e-f2f1788a73b8.png)

**Acceptance criteria**

- Prices for all tokens listed in the resolver (isListed in the Token List on [Superfluid Console](https://console.superfluid.finance)) are correctly displayed in Gnosis Safe
- Prices should be available on all mainnets supported by both Superfluid and Gnosis Safe

**Bounty Reward**

$500 payable on Polygon in Super DAI (DAIx)

All our bounty payouts require a successful light KYC screening.

**Comment by 3scava1i3r** [comment]
Would you mind adding on the acceptance criteria and the major milestones for the same task?

**Comment by bfqu** [comment]
cool
