### ISSUE TITLE
[ETHEREUM-CONTRACTS] Address Deposit Clipping and OwedDeposit Usability Issue

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#735]
There is a general discontent towards how deposit and clipping owed deposit logic collab together, a thorough review, code-modifications and write-up of this topic is something much needed now.

**Comment by d10r** [comment]
Possible mitigations: see https://github.com/superfluid-finance/protocol-monorepo/wiki/About-Real-Time-Balance (search for _Possible fix _)

**Comment by hellwolf** [comment]
replaced by #899
