### ISSUE TITLE
[SUBGRAPH] Map governance parameters and contract addresses to an entity

### ISSUE THREAD

**Issue by kasparkallas** [superfluid-finance/protocol-monorepo#744]
**Why?**
Right now it's not straightforward enough to query the governance parameters and contract addresses. It would be great if there was an entity on Subgraph which contained all the up-to-date information.

**How?**
Governance parameters are a result of projecting `cfav1LiquidationPeriodChangedEvent` & `pppconfigurationChangedEvent` data. NOTE: There seems to be an issue that test networks haven't had a `pppconfigurationChangedEvent` emitted, at least on Subgraph.

Contract addresses can be queried from the resolver.

**Comment by 0xdavinchee** [comment]
after discussions w/ @kasparkallas this will be handled via the SDK-core as doing the calls for the governance parameters via web3 calls is simple enough.
