### ISSUE TITLE
Ricochet Exchange V2.1 Deployment Key Request

### ISSUE THREAD

**Issue by mikeghen** [superfluid-finance/protocol-monorepo#764]
Describe the SuperApp:

Ricochet Exchange

Network will be deployed?:
Polygon

Deployer address:
0x3226C9EaC0379F04Ba2b1E1e1fcD52ac26309aeA

Factory address:
NA

Link of repo of the contract to be deployed:
https://github.com/Ricochet-Exchange/ricochet-protocol

Contact info for developer:
@mikeghen

Notes:
Please give me a batch of 10 keys

**Comment by hellwolf** [comment]
generated 10 keys, DM in discord
