### ISSUE TITLE
Update L2 + xdai contracts to 1.2.1 and hand over to multisig(s)

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#767]
multisig addrs: https://www.notion.so/superfluidhq/3b568d0fe62b4c63a418c7335136968b?v=26159ef195224294a6b4a3cbad11e99a

* update contracts from handover acc
* hand over resolver to CCP multisig
* hand over gov to PLA multisig
* increase PLA multisig threshold
* batch update SuperTokens

**Comment by d10r** [comment]
## Arbitrum One

* [x] update contracts from handover acc: [arbone_1.2.1.txt](https://github.com/superfluid-finance/protocol-monorepo/files/8604342/arbone_1.2.1.txt)
  * [x] pending contract verification
* [x] hand over resolver to CCP multisig: https://arbiscan.io/tx/0x3540fbbc73f9e7bfe4bfa151f47295a8d24ccf1e4539407daa5f975d3ded86fc, https://arbiscan.io/tx/0x65dc8b27cfeb0e4a1d84d935aece0e695da4fab9acce59504c31b7dbd0348205
* [x] hand over gov to PLA multisig: https://arbiscan.io/tx/0x940b5b84b8df2434ae88d40f5fc7eb3f01785abe6ed4172b1dcf75d6ec443070
* [x] add github-agent to PLA
* [x] batch update SuperTokens: 
* [x] remove  protocol handover account
* [x] increase PLA multisig threshold

**observations**:
* The multisig wallet will set Ethereum gas prices, leading to way too high cost estimations. The actual tx cost depends on the gasPrice at the moment of execution, thus no overpaying. 
* Since the gas limit is hardcoded to the max. for script executions, the sender account needs to have a min balance of ~0.2 ETH
* TODO: CALLBACK_GAS_LIMIT in Superfluid.sol is hardcoded to 3M. On Arbitrum this may translate to something like ~100k compared to other EVMs, probably not even enough to open/close a stream in the callback

**Comment by d10r** [comment]
## Optimism

* [x] update contracts from handover acc: [opmainnet_1.2.1.txt](https://github.com/superfluid-finance/protocol-monorepo/files/8609062/opmainnet_1.2.1.txt)
  * [x] pending contract verification
* [x] hand over resolver to CCP multisig: https://optimistic.etherscan.io/tx/0x3cd1c792ab959eb88661519ec62a0888d5bd67d62723d89dbd918c2bafc5f096, https://optimistic.etherscan.io/tx/0x288a7608fafb96b639669e78e028877968608b2859423f1c861f3e9ed87831a0
* [x] hand over gov to PLA multisig: https://optimistic.etherscan.io/tx/0xd8019fd713ce5a37e0b18befbe67ce53ee8b7dc015484de68089c7b6bead6674
* [x] increase PLA multisig threshold
* [x] batch update SuperTokens: https://github.com/superfluid-finance/protocol-monorepo/runs/6271143386?check_suite_focus=true
* [x]  remove  protocol handover account

**observations**
* when initiating a tx via multisig, the gas price should be changed to 0.001 gwei. Otherwise we dramatically overpay for the L2 gas

**Comment by hellwolf** [comment]
** TODO test

**Comment by hellwolf** [comment]
xdai done too!

🥳
