### ISSUE TITLE
[SUBGRAPH] Create AccountTokenSnapshotLog for each AccountTokenSnapshot update

### ISSUE THREAD

**Issue by vmichalik** [superfluid-finance/protocol-monorepo#775]
Add `AccountTokenSnapshotLog` entity every time we update `AccountTokenSnapshot` entity.
This allows us to easily query historical changes of an account-token pair.
Can choose to add other changing values to the entity, not just the balance. 
I would omit reverse lookups (except AccountTokenSnapshot)

## Note

This is a workaround for that we cannot access time machines of AccountTokenSnapshot as queries. https://github.com/graphprotocol/graph-node/issues/3480

**Comment by kasparkallas** [comment]
The practical reason for this story is to do visualizations of various data on AccountTokenSnapshots.

The technical reason for this story is that we can't query entity time-travel versions as a list. There's an issue for that in The Graph's repo: https://github.com/graphprotocol/graph-node/issues/3480
