### ISSUE TITLE
[SUBGRAPH] Add a counter property for subscribers on an Index

### ISSUE THREAD

**Issue by vmichalik** [superfluid-finance/protocol-monorepo#776]

**Comment by msoni89** [comment]
@kasparkallas 

Please add more detail here.

Do you want me to increase and decrease the counter based on subscribe, or unsubscribe?

Is subscriber_count okay for the name?

**Comment by msoni89** [comment]
As per the discussion, we don't need to address it because it's already available as totalSubscriptionsWithUnits

**Comment by kasparkallas** [comment]
Thank you, @msoni89

`totalSubscriptionsWithUnits` actually makes more sense than just `totalSubscriptions`. We should also display this number in the Console. I'll make a story for that and edit this comments.

Story here: https://github.com/superfluid-finance/superfluid-console/issues/81
