### ISSUE TITLE
[ETHEREUM-CONTRACTS] Support Hardhat in `deployFramework`

### ISSUE THREAD

**Issue by mikeghen** [superfluid-finance/protocol-monorepo#785]
https://github.com/superfluid-finance/protocol-monorepo/blob/a86bfd102b83d9c41e1b51b5ae3cdd159f60d890/packages/ethereum-contracts/scripts/libs/truffleScriptRunnerFactory.js#L21

It would be nice to be able to use these methods with hardhat so the SF `deployFramework` function would be usable in hardhat.

**Comment by joeljesu** [comment]
Hi Mike, I've been able to use `deployFramework` in a Hardhat project which you can view it here: https://github.com/sunnyjaycer/rex-bank/blob/08aecd76309c941f1c0bc6957a3d5a283229b7f7/test/bank.ts#L94. Is this the kind of implementation you were looking for?

**Comment by hellwolf** [comment]
Concur with @sunnyjaycer 

Linking #792 for more about what we will do next.
