### ISSUE TITLE
[GOV-PROC] Review TrustedForwarderSettings

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#793]
- Remove or use the new biconomy contract.

**Comment by d10r** [comment]
Addresses: https://docs.biconomy.io/misc/contract-addresses

kovan: removed 0xe8df44bcaedd41586ce73eb85e409bcaa834497b, added 0xF82986F574803dfFd9609BE8b9c7B92f63a1410E
goerli: removed 0x3075b4dc7085c48a14a5a39bba68f58b19545971, added 0xE041608922d06a4F26C0d4c27d8bCD01daf1f792
mumbai: removed 0x2B99251eC9650e507936fa9530D11dE4d6C9C05c, added 0x9399BB24DBB5C4b782C70c2969F58716Ebbd6a3b


polygon: unchanged: 0x86C80a8aa58e0A4fa09A69624c31Ab2a6CAD56b8
xdai: unchanged: 0x86C80a8aa58e0A4fa09A69624c31Ab2a6CAD56b8

Optimism (both testnet and mainnet) missing in the list

Usage on other networks very low, thus not added.

**Comment by d10r** [comment]
added script for enabling/disabling forwarders in https://github.com/superfluid-finance/protocol-monorepo/pull/905/commits/984d8f40d5d08c52cad2b8339c7be90022e9d174 and fixed info-show-protocol.js to not show disabled forwards.
Related: found a bug in subgraph: doesn't switch to new governance contract if replaced in host.

**Comment by d10r** [comment]
gov is now dynamic in subgraph: https://github.com/superfluid-finance/protocol-monorepo/pull/909
