### ISSUE TITLE
[SUBGRAPH] Add test case which queries all Events/HOLs for ILightEntity

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#796]
* A bug was recently discovered in the Subgraph after pushing 1.3.1 where the `Account` property was not being properly added
   * The expectation was that the subgraph would not be able to index to completion when attempting to create an entity without a link, but it's possible to create an entity pointing to an address, but if the entity doesn't exist on the other side, it breaks

Proposal: Add a single test case which queries all event/HOL/aggregate entities and try to get the ILightEntity of each just to ensure nothing is null.

e.g.

```
query GetFlowUpdatedEvents {
    flowUpdatedEvents {
        stream {
             id
        } 
    }
}
```

**Comment by hellwolf** [comment]
It's done
