### ISSUE TITLE
[ETHEREUM-CONRACTS] Use abi.encodeCall

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#797]
Starting from [solidity v0.8.11](https://forum.soliditylang.org/t/solidity-v0-8-11-is-here-first-implementation-of-language-server-and-abi-encodecall/723), `abi.encodeCall` is available as an type-safe alternative to abi.encodeWithSelector when you have the access to the function pointer.

We should use it as much as possible.

**Comment by d10r** [comment]
be aware of https://blog.soliditylang.org/2022/05/17/calldata-reencode-size-check-bug/
