### ISSUE TITLE
[SUBGRAPH] Make it possible to filter for "native asset super tokens"

### ISSUE THREAD

**Issue by kasparkallas** [superfluid-finance/protocol-monorepo#807]
**Problem**
Right now, the client has to figure out which _wrapper super tokens_ are for native assets and also which _pure super tokens_ are for native assets.

**Solution**
Add a boolean flag `isNativeAssetSuperToken` property to `Token` to make these types of tokens distinguishable.

**Technical**
Unfortunately in the Subgraph mapper, there's no concrete way to infer from the contracts (i.e. a RPC call) which type a token is. So we need to figure out something here.

**Comment by 0xdavinchee** [comment]
#968 addresses this issue by hardcoding the native asset super token symbol for each network
