### ISSUE TITLE
[ETHEREUM-CONTRACTS] governance deployment on mainnets

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#817]
If a network defined in `libs/getConfig.js` has `disableTestGovernance` set to `true` (which is expected on mainnets), initial deployment with `scripts/deploy-framework.sh` will fail.  
For the recent deployments (Optimism, Arbitrum) this wasn't an issue, bcs the flags where not set (unintentially).  
For avalanche-C it was set, thus blocked deployment.

* Check how this was handled for the OG deployments (xdai, matic)
* Check resolver entries (probably not existing for the L2s)
* Decide how we want to handle going forward - also consider the handling of updates

**Comment by d10r** [comment]
Initial deployment with TestResolver is intended behaviour.  
Still unclear: when do we need to add the flag `disableTestGovernance` to `scripts/libs/getConfig.js`? Probably needed for when deploy-framework is run for updating. Check if/how we can simplify this.
Also: prod governance is not registered in the resolver.

**Comment by hellwolf** [comment]
To be continued in PR in https://github.com/superfluid-finance/protocol-monorepo/pull/821

**Comment by hellwolf** [comment]
further being worked on in https://github.com/superfluid-finance/protocol-monorepo/pull/1076

**Comment by d10r** [comment]
* `disableTestGovernance` flag: knowing that initial deployment of TestGovernance is ok, I suggest we leave as is and just don't set the flag for new mainnet entries until after the protocol was deployed. Can then be set in the process of the usual metadata update (resolver address etc.).
* Resolver: I don't think we should register prod governance in the Resolver. It's trivial to look it up from the host contract. Duplicating that information in the resolver adds the risk of inconsistency (the host is the source of truth anyway) without adding any obvious benefit. The Resolver is useful for looking up addresses not trivial to discover via host contract.
