### ISSUE TITLE
[Deployer Whitelisting Request] 

### ISSUE THREAD

**Issue by Aeroxander** [superfluid-finance/protocol-monorepo#844]
**Describe the SuperApp:**

Creaton is a Web3 Patreon, we have a factory contract which mints superapps for each creator, to receive subscriptions and put every subscriber in a subscriber mapping in order to get decryption access of the creators content

**Network will be deployed?:**

Polygon

**Deployer address:**

**Factory address:**

https://polygonscan.com/address/0xb1Af6f8d1747C3F3C3bD7077F12D9e5AD880f7e9

**Link of repo of the contract to be deployed:**

https://github.com/creaton-io/creaton/blob/web3storage/contracts/src/creaton/CreatonAdminV1.sol

**Contact info for developer:**

alexander@creaton.io

**Notes:**

**Comment by hellwolf** [comment]
@d10r will take a look of this today

**Comment by d10r** [comment]
governance action 269 initiated: https://polygonscan.com/tx/0x0806f8187bb8503b796b73f9f924df269846ceec9bab24793b005b733051fd31
waiting for enough signatures.

**Comment by hellwolf** [comment]
@Aeroxander 0xb1Af6f8d1747C3F3C3bD7077F12D9e5AD880f7e9 is now a whitelist super app factory on polygon!

**Comment by d10r** [comment]
governance action executed in https://polygonscan.com/tx/0xd2ed89d9e0e96f279a64439484521ad2f167b3821cd03de47492dcc69122347c
