### ISSUE TITLE
[SUBGRAPH] Allow for querying of previous block ATS Log in agreementLiquidatedV2Event

### ISSUE THREAD

**Issue by leopk-code-sf** [superfluid-finance/protocol-monorepo#864]
For the solvency response time monitoring we need the balanceUntilUpdatedAt and totalNetFlowRate of an Account token on the block *before* a liquidation event occurs. 

Right now there is no efficient way of doing this - we have to make an individual query for each ATC logs we want to retrieve. 

The most efficient way would be to link the most recent account token snapshot log to the liquidation event, so that it can be queried like this 

```
query MyQuery {
  agreementLiquidatedV2Events {
    id
    targetAccount
    token
    accountTokenSnapshotLog {
      balance
      blockNumber
      id
    }
  }
}
```

**Comment by kasparkallas** [comment]
There is still the issue of intermediate index distributions not getting included in the logs. That means there could be anomalies in the response time measurements. 

Example:
1. Account has a log entry an is going critical in 1 hour.
2. Account gets a distribution for that token but a new log is not created. Account is going critical in 1 hour and 10 minutes.
3. Account gets liquidated in 1 hour and 11 minutes (as supposed to).
4. The solvency response time monitoring would show a response time of 11 minutes but actually it was 1 minute.

**Comment by kasparkallas** [comment]
@leopk-code-sf For the time being, you can try out this query:
```graphql
query SolvencyResponseTimeMonitoring {
  accountTokenSnapshotLogs(
    where: {triggeredByEventName_in: ["AgreementLiquidatedV2", "AgreementLiquidatedBy"], balance: "0"}
  ) {
    blockNumber
    timestamp
    totalNetFlowRate # Might not be zero.
    totalDeposit # Deposit might not be zero when there's more streams to liquidate.
    outerOrder: order # Use this to filter out newer inner logs.
    accountTokenSnapshot {
      previousLogs: accountTokenSnapshotLogs(
        orderBy: order
        orderDirection: desc
        first: 1000
        where: {balance_not: "0", totalNetFlowRate_lt: "0"}
      ) {
        blockNumber
        timestamp
        totalNetFlowRate # The "previous log" from the liquidation one will definitely have this negative.
        innerOrder: order
      }
    }
  }
}
```

Usually the last log is the first one in `previousLogs` but it might not be the case when the account has been liquidated more than once for that token. So you sometimes have to do some simple client-side filtering from that collection to get the last one -- just filter out all the inner log entries that have higher order than the `outerOrder`.

**Comment by 0xdavinchee** [comment]
@leopk-code-sf is this issue still relevant?

**Comment by 0xdavinchee** [comment]
closing this issue
