### ISSUE TITLE
Ricochet Exchange V2.1 Deployment Key Request

### ISSUE THREAD

**Issue by mikeghen** [superfluid-finance/protocol-monorepo#865]
**Describe the SuperApp:**

Ricochet Exchange

**Network will be deployed?:**
Polygon

**Deployer address:**
0x3226C9EaC0379F04Ba2b1E1e1fcD52ac26309aeA

**Factory address:**
NA

**Link of repo of the contract to be deployed:**
https://github.com/Ricochet-Exchange/ricochet-protocol

**Contact info for developer:**
@mikeghen

**Notes:**
Please give me a batch of 10 keys

**Comment by hellwolf** [comment]
@d10r will look into if we can use a expiration-dated deployer whitelisting this time for you @mikeghen !

**Comment by mikeghen** [comment]
Thanks @hellwolf

**Comment by d10r** [comment]
unfortunately not yet deployed to mainnet :-/

**Comment by d10r** [comment]
```
0x514d81163bca283e69fd6745a6ca4d3e0f78bd6dff4a631992f8e8458f0ce2d7
0xb347077ada80c24bdd0761bab942112b863d4c19afa21db1876330ce373fa3ce
0x156a95ced8bb5b083586b46de904cdb82a6a6e87554c34ea619397d45ad914da
0xf74d01b744d02ad5262be64abf6c81cd869e5122c8c4b5c8c1048b48c4397261
0x8d63aec89c75e51e439462a5fe319780c745e25486f24dc6c25a87f3c8dfb227
0xe6bf0dbfe520a725a1d38dbc7544961bec1eac242628e553a8c1abc8553cbd1d
0xa1d6e343aa31399b7e1fb1d0452b421be863d4f4236ed0585bef53136dbcd7cd
0xa9ceb3ff63bc5c8aed316ea598a714a35012827c61084baadafb887d46f2ba5b
0xa8b4d1a3c6d92f1407a8a503b7f7a11fd86434df6609937d9e8258d37ba06968
0x845968586b097c22262d5669ada65c381a8d09db970fca42406819dfc6a9ae65
```

@hellwolf please sign in multisig wallet. (Note that one of the keys is duplicated 4 times (actions 272-275) due to the gas issues.)

**Comment by mikeghen** [comment]
> unfortunately not yet deployed to mainnet :-/

No problem

**Comment by hellwolf** [comment]
@mikeghen you have them!

**Comment by mikeghen** [comment]
@hellwolf I think I need them I didn't get them yet in discord, Im not in the SF discord
