### ISSUE TITLE
[SUBGRAPH] Investigate a technical solution re trivial deprecating fields

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#875]
# Problem

We want to do trivial deprecating fields exercise with the intent of removing them soon without having to a major breaking versioning release.

This issue occurred when using ListEvents, arguably it has some tech debt/design issues:
    1. maintainability issue wrt deprecating fields
    2. optimization issue wrt querying all fields of all events

# Potential Things to Look Into

A. removing deprecating fields from codegen stage
  - this is to make newer packages ready for removing of deprecating fields in the future
  - this seems too daunting tasks to address it ourselves
  - we should reach to either subgraph or @graphql-codegen project to see what they have to say to this engineering problem.
  - (SPIKE) investigate if @deprecated can be of any help: http://spec.graphql.org/October2021/#sec--deprecated

B. run-time solution using runtime introspection:
  - filtering out deprecating fields in queries in run-time (CONS: complicated solution, and change existing deployment behaviour is usually not a good idea)
  - print big-arse warnings in console (Preferred solution)
  - overall this might be a difficult task.

## Other Notes

We may also want to consider deprecate listEvents, and use new sdk-core apis in console such that there is no run-time compatibility issue and potentially also more optimized (not querying all unnecessary fields)

**Comment by 0xdavinchee** [comment]
can be closed:
- we are never going to introduce any breaking changes to the subgraph
- other issues address the underlying problem that we are trying to solve better: https://github.com/superfluid-finance/protocol-monorepo/issues/969 and https://github.com/superfluid-finance/protocol-monorepo/issues/916
