### ISSUE TITLE
Investigate sourcify verification with hardhat-deploy plugin

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/protocol-monorepo#898]

**Comment by d10r** [comment]
issue: the combination of deployment by factory and immutable variables is currently not supported by sourcify, see https://docs.sourcify.dev/docs/immutables/.  
At the moment that means the SuperToken logic can't be verified, meaning Super Tokens remain unverified.  
We can either manually hack the bytecode before sending or not use immutable in that contract.

**Comment by hellwolf** [comment]
Now that we have gnosisscan, we will rethink our open-source support of blockscout for now.
