### ISSUE TITLE
[INTEGRATION] Superfluid x Instadapp Connector

### ISSUE THREAD

**Issue by saflamini** [superfluid-finance/protocol-monorepo#902]
## What is an Instadapp Connector?

Instadapp is a platform for building web3 native products that allow developers to take full advantage of decentralized finance with a single API.

The Instadapp protocol is built around what's known as the DeFi Smart Layer (DSL for short). Users and developers interact with the DSL via 'Smart Accounts.' The DSL includes a layer for interoperability that supports 'Account Extensions.' These extensions enable the platform to form a DeFi hub through which new use cases and extensions can be created. Some examples of possible use cases include: Flash Loan Modules, Authority extensions, L2 extensions, and more (like Superfluid extensions 😁).

## Here's an outline of how developers interact with Instadapp account extensions (also referred to as Connectors):

> "Interacting with Connectors works like this under the hood:
> 
> While calling a function, users interact with their Smart Account.
> The smart account contract uses a fallback function to fetch the address of the Extension Module to call via Implementation - contract using (`msg.sig`) of the function called by the user.
> Once the address is fetched, our smart account uses it to obtain the implementation code and runs it."

<img width="680" alt="How Smart Accounts Operate - From the Instadapp Docs" src="https://user-images.githubusercontent.com/43142465/174247764-2ed1db56-e9b8-47f6-88b0-f8641dc7c51e.png">

> "The mapping of Function sigs to extensions will be added by the INST governance. Instadapp team is focused on building and excited for community collaboration on extending the smart account capabilities. In the meantime, developers can begin playing with Extension Module 1 today!
> 
> To simulate a transaction in Module 1, the user interacts with their smart account using the `cast()` function. This is the core function that allows smart accounts to interact with DeFi protocols and complete composable transactions.
> 
> However, the` cast()` function does not reside in the smart account contract of the user, hence the fallback function is called to get the implementation contract using `msg.sig`.
> 
> After getting the extension contract, a delegate call is made to the respective extension which contains the cast function to run all the spells.
> 
> Inside the spell function, delegate call(s) is done to execute the function called by the user."

<img width="682" alt="Instadapp account extensions" src="https://user-images.githubusercontent.com/43142465/174249056-88ab91d4-7574-4917-9cca-c53615eeb4bf.png">

### See the Maker, Uni, and Compound logos in the above image? We want Superfluid to be on that list 🌊

We want Instadapp developers to be able to leverage Superfluid as a part of their account extensions as they build on top of Instadapp. To do this, we'll need to build an Instadapp Connector.

### We've written a spec for how this Connector should be architected that you can find here:
[Superluid x Instadapp Connector Spec](https://www.notion.so/superfluidhq/InstaDapp-Superfluid-Connector-Spec-650fa0393066493f9cf39f8da13369b0)

## Getting Started
If you're interested in working on this bounty, here are the steps you'll take to get involved:

1. Please contact us in the #bounties channel of the [Superfluid Discord ](https://discord.gg/ESDbTg3J)and tag Sunny | Superfluid. Be sure to specify that you're interested in Building a Superfluid Instadapp Connector.
2. If we determine that you might be a good fit, we will schedule a call to review your background and discuss next steps
3. Provided that step 2 goes well, we will work together with the Instadapp team to ensure that you have the resources necessary to complete the work on this bounty.
4. Start work on bounty - you'll have full access to the Superfluid team as a resource as you build
5. If the completed work is up to the Superfluid + Instadapp teams' standards, we will pay out the bounty.

**Links that will be helpful:**
- [Guide on Creating Instadapp Connectors](https://docs.instadapp.io/guides/create-connectors) ✨
- [Instadapp Docs](https://docs.instadapp.io/)
- [Superfluid Docs](https://docs.superfluid.finance)
- [PR For a Previous Connector in the Instadapp Repo](https://github.com/Instadapp/dsa-connectors/pull/44)

**Expected time commitment: 30 hours**

**Skills Required:** Intermediate to advanced solidity skills

**Bounty Reward:** ~$1300 at time of writing: 750 USDC on Polygon + 750 $INST

**Comment by SmartDev84** [comment]
Hello. @saflamini , @sunnyjaycer 
I want to do this issue.

**Comment by 0xdavinchee** [comment]
@saflamini just curious if this is still in progress or naw?

**Comment by joeljesu** [comment]
@0xdavinchee nobody is currently working on this

**Comment by joeljesu** [comment]
This bounty has gone stale. Will be closing for now!
