### ISSUE TITLE
[Deployer Whitelisting Request] 

### ISSUE THREAD

**Issue by rashtrakoff** [superfluid-finance/protocol-monorepo#908]
**Describe the SuperApp:**

dHEDGE is a one-stop location for managing investment activities on-chain where you can put your capital to work in different strategies based on a transparent track record.

**A clear and concise description of the SuperApp**

A user just has to start a stream. Tokens are deposited into the dHEDGE pool regularly (in approx 24 hour periods) using keepers (Gelato network keepers for the time being). DHPT (dHEDGE Pool Tokens) are minted after each deposit and these are then available for withdrawal after approx 24 hours for the user.

**Network will be deployed?:**

Polygon

**Deployer address:**

0x452181dAe31Cf9f42189df71eC64298993BEe6d3

**Factory address:**

0x17213A065e5E67bFebA4624b9aa0D39bff377FB4

**Link of repo of the contract to be deployed:**

https://github.com/DAM-Protocol/SIP-Contracts.git

**Contact info for developer:**

Discord: 
rashtrakoff#2547

**Notes:**
This is a factory clone deployer.

**Comment by d10r** [comment]
@hellwolf please sign

**Comment by hellwolf** [comment]
DONE: https://polygonscan.com/tx/0xc82e76c90396d119cbb5e8df6dd6a9fe340a77eb7546e991e7c8aef1343022f2

```
authorizeAppFactory
 host: 0x3E14dC1b...
 factory: 0x17213A06...
```
