### ISSUE TITLE
[Deployer Whitelisting Request] 

### ISSUE THREAD

**Issue by shreyaspapi** [superfluid-finance/protocol-monorepo#914]
Describe the SuperApp:

Stream Leverage super app, we are creating a DCA stream into leverage positions using AAVE.

A clear and concise description of the SuperApp

A user just has to start a stream. Tokens are swapped using uniswap periodically. The swapped tokens are then deposited to AAVE and used as collateral to borrow 30% more.

Network will be deployed?:

Polygon

Deployer address:

0x92660986CD0313448A68558B13984a02D80fC762

Factory address:

0x92660986CD0313448A68558B13984a02D80fC762

Link of repo of the contract to be deployed:

https://github.com/shreyaspapi/ethnyc

Contact info for developer:

Discord:
shreyaspapi#7523

Notes:
We are at ETHNYC.

**Comment by d10r** [comment]
0x2C90719f25B10Fc5646c82DA3240C76Fa5BcCF34 is the SuperTokenFactory contract of the Superfluid framework.  
_Factory_ in the context of a SuperApp registration would be a project-specific contract which creates SuperApp contracts and registers them with the framework.  

I assume what you want is to deploy and register a SuperApp with the EOA 0x92660986CD0313448A68558B13984a02D80fC762.
A transaction for giving that account allowance with the registration key 0x216ea95e19fbcd674e49425bc744ddf13f9f10dad57d426f65882d7a22ec58e9 was created. This issue will be updated once it's signed by gov and ready to be used.

**Comment by hellwolf** [comment]
They were approved!
