### ISSUE TITLE
[SDK-CORE] Forward Batch Call

### ISSUE THREAD

**Issue by jtriley2p** [superfluid-finance/protocol-monorepo#961]
**Description:**
The `execForward` function does not work. The function signs a `forwardBatchCall` as if it was a transaction coming from an EOA. An EOA should _never_ have forward permission, therefore this should never work.

**Environment:**
All environments.

**Steps To Reproduce:**
1. Initialize framework
2. Create any signer
3. Create any operation(s)
4. Call `execForward` with signer

**Expected behavior:**
The SDK indicates the `execForward` may work with a signer.

**Actual behavior:**
The transaction always fails.

**Additional context:**
Forward batch call would ideally enable meta-transactions, however, meta transactions are currently handled by external dependencies such as Biconomy. We would need to create a solution for the Biconomy forwarder specifically or remove the `forwardBatchCall` function altogether.

**Comment by 0xdavinchee** [comment]
hey - thanks for creating this issue, had a discussion about this with @saflamini a while back, it's a known bug and the execForward was something put off as there hasn't been **that** much questions regarding the usage

**Comment by hellwolf** [comment]
Mostly an external integration thing, but we may support in the sdk-core some helper for those integrations (through peerDependency).

But first step is to provide a helpful example to show case how to do such external integration.

@ngmachado will continue the investigation from here.
