### ISSUE TITLE
[SUBGRAPH] Add `isNativeAsset` property to SuperToken entity

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#962]
## Problem
- I would like to know whether a SuperToken is the `NativeAssetSuperToken` for a particular chain without having to do RPC calls, etc.

## Solution
- Hardcode whether the token `isNativeAsset` for each network

**Comment by kasparkallas** [comment]
Duplicate: https://github.com/superfluid-finance/protocol-monorepo/issues/807 :stuck_out_tongue_closed_eyes:

**Comment by 0xdavinchee** [comment]
lel, duplicate of #807
