### ISSUE TITLE
[SDK-CORE] Proposal to use graphprotocol/graph-client

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#969]
## Summary
The Graph awarded a $48M grant to "The Guild" in December 2021 and is committing to directly help The Graph develop core subgraph features. NOTE: The Guild is one of the top open-source developer groups in the GraphQL ecosystem.
For more [details](https://thegraph.com/blog/guild-announcement) on the grant.

## Proposal
I believe that when we extract the Query capabilities from the SDK-Core, we should change our tooling and use the [graph-client](https://github.com/graphprotocol/graph-client) which is developed and maintained by The Guild.

Using this tool means that we no longer have to maintain and worry about the implementation of the intricacies surrounding GraphQL, but instead leverages the knowledge of The Guild and uses the abstraction in this library to accomplish what we need.

This library solves a lot of problems (and has new features we don't currently have) which we are solving manually by combining a few different libs probably developed by The Guild anyways.

## Drawbacks
- Switching costs
- Reliance on 3rd party
- Less understanding of what is going on underneath the hood (especially for newer features)

**Comment by hellwolf** [comment]
Is this one still relevant?

**Comment by 0xdavinchee** [comment]
> Is this one still relevant?

I'd say so-the products team are already using this over the ad-hoc approach we have.
