### ISSUE TITLE
[SDK-CORE BUG] - CallAppAction batchCall doesn't work

### ISSUE THREAD

**Issue by jtriley2p** [superfluid-finance/protocol-monorepo#973]
## Bug Description

SDK-Core `batchCall` does not properly handle a `CALL_APP_ACTION` Operation. The batchable operation succeeds when called directly on the Superfluid host contract and when used with the JS-SDK, so the issue appears to be specific to SDK-Core.

## Relevant Environment Information

  - Project Type: node
  - Package version: 0.4.4
  - TypeScript/Javascript: Typescript
  - Blockchain interfacing library: ethers js
  - Node version: v16.6.1
  - Framework: Hardhat

## Reproduce Steps

1. Initialize framework in any environment
2. Create ethers signer
3. Create Operation with operation type "CALL_APP_ACTION"
4. Exec in a batch call
5. Transaction fails

## Expected Behavior

"CALL_APP_ACTION" with a function whose only argument is `bytes memory ctx` and that returns `bytes memory newCtx` should, when called by the SDK-Core batch call should succeed.

## Actual Behavior

The call always reverts with "Call Utils: target reverted".

## Context

It appears this may be due to the fact that the function selector is removed when the operation type is not "SUPERFLUID_CALL_AGREEMENT". This may be fixable by not removing the function selector when the operation type is "CALL_APP_ACTION".

Source: https://github.com/superfluid-finance/protocol-monorepo/blob/763ca6966046ad0f959aab86d11c5b50c9e00e70/packages/sdk-core/src/BatchCall.ts#L103

**Comment by jtriley2p** [comment]
@saflamini tagging for visibility

**Comment by 0xdavinchee** [comment]
Extra: 
## Problem
SDK-Core does not support the callAppAction function as more people are starting to request this as relayed by @saflamini 

## Todo
Create a function with an API similar to: `populateCallAgreementTxnAndReturnOperation`, e.g. `populateCallAppActionTxnAndReturnOperation`.
