### ISSUE TITLE
[SUBGRAPH] Refactor schema since we can filter queries by child entities

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#974]
## Summary
The Graph fairly recently added a new [feature](https://github.com/graphprotocol/graph-node/pull/3184) that allows you to filter queries by child entities (discovered by @kasparkallas). 
We currently have a lot of properties duplicated on the parent entity to allow easy filtering, but many entities can be remodeled to have fewer entities and be lighter.

**Comment by kasparkallas** [comment]
This is a task for V2 of Superfluid Subgraph.

**Comment by 0xdavinchee** [comment]
not going to happen in v1
