### ISSUE TITLE
[TOOLING - ETHEREUM-CONTRACTS] Use Hardhat compile as build instead of truffle compile

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#976]
We are currently using truffle compile when building contracts, although hardhat is faster.
The reason we haven't switched over yet is because of the `build:contracts-size` and `build-abi-json.sh` commands which relies on the structure of the build output to be what truffle outputs. 
We can either use a (pre-built package)[https://www.npmjs.com/package/hardhat-contract-sizer] or modifying the `print-contract-sizes.sh` and `build-abi-json.sh` scripts for hardhat (we could keep the one for truffle and create a new one for hardhat based off of it).

npx hardhat compile  25.14s user 1.13s system 94% cpu 27.886 total
yarn build:contracts  63.44s user 0.88s system 130% cpu 49.447 total

**Comment by hellwolf** [comment]
Build output is also processed by the sdk projects, check:

https://github.com/superfluid-finance/protocol-monorepo/blob/dev/packages/sdk-core/tasks/build-abi-json.sh

```
        ABI="$($JQ '.abi' ../ethereum-contracts/build/contracts/$i.json)"
```

This also needs to be rebuilt

**Comment by 0xdavinchee** [comment]
good point, will modify the description to reflect

**Comment by 0xdavinchee** [comment]
this is probably not doable currently given reliance on truffle-contract package for our scripts, payoff is not worth it imo given all the additional logic/complexities required to make it work solely with hardhat compile, we can just use both compilation methods rn
