### ISSUE TITLE
[SDK-CORE BUG]  Unable to access Operation from Framework 

### ISSUE THREAD

**Issue by saflamini** [superfluid-finance/protocol-monorepo#980]
**Describe the bug:**
When creating a new Operation directly with the SDK core , you're unable to get the Operation class from either the Framework object or from the default imports.

Additionally, when importing it like so: `const Operation = require("@superfluid-finance/sdk-core/dist/main/Operation");`
Users need to create new operations by calling `new Operation.default()` rather than just `new Operation()`

**Environment (please complete the following information):**
  - Device: [e.g. Macbook Pro - Apple Silicon]
  - OSS: OSX
  - Network/Connection: WiFi
  - Project Type: module
  - Package version: [e.g. ^0.4.4]
  - TypeScript/Javascript: Javascript
  - Blockchain interfacing library: ethers
  - Provider: Alchemy
  - Chain: Goerli, other testnets
  - If running in node:
    - Node version: v14.17.0
    - Framework: Hardhat

**Steps To Reproduce:**
1. Initialize framework with Framework.create()
2. Try creating a new `Operation` (i.e. for usage within a batch call) as depicted [here](https://docs.superfluid.finance/superfluid/developers/sdk-initialization/sdk-core/batch-calls)
3. Get `TypeError: Operation is not a constructor`

Current Workaround:
Import the Operation class directly from the SDK like so: 
`const Operation = require("@superfluid-finance/sdk-core/dist/main/Operation");` 
the operation class is accessible by calling `new Operation.default(...)`

**Expected behavior:**
Ideally, the Operation class is available directly from the Framework object, or as something that can be imported along with the Framework from the SDK Core. Ideally, users could access the Operation class in one of the following two ways:

- `const { Framework, Operation } = require("@superfluid-finance/sdk-core)`
- [after the Framework has been initialized] `new sf.Operation(...)`

**Additional context:**
I needed to use the Operation class when using `callAppAction` within a batch call

**Comment by 0xdavinchee** [comment]
Discussed w/ @saflamini, will use a factory pattern similar to `batchCall` on `Framework` to implement this.
