### ISSUE TITLE
[PROTOCOL-MONOREPO] Add actions/cache to cache package installs

### ISSUE THREAD

**Issue by 0xdavinchee** [superfluid-finance/protocol-monorepo#981]
Let's figure out a way of adding [actions/cache](https://github.com/actions/cache) in our build pipelines to speed up our workflows and burn slightly fewer trees.

**Comment by d10r** [comment]
good idea, it's hot enough already

**Comment by d10r** [comment]
I measured how long the principal steps take on a simple VPS with 2 cores and 4 GB RAM:

```
time git clone https://github.com/superfluid-finance/protocol-monorepo
...
real    0m3.013s
user    0m2.543s
sys     0m0.793s

time yarn install --frozen-lockfile
...
real    0m59.010s
user    0m59.548s
sys     0m29.750s

time yarn build
...
real    3m43.775s
user    4m48.768s
sys     0m11.544s
```

In the build step, a lot of time seems to be spent with downloading solc, it's stuck a while at
```
✓ Fetching solc version list from solc-bin. Attempt #1
✓ Downloading compiler. Attempt #1.
```
