### ISSUE TITLE
[Deployer Whitelisting Request] DiagonalFinance Factory

### ISSUE THREAD

**Issue by b-d1** [superfluid-finance/protocol-monorepo#991]
**Describe the SuperApp:**

Diagonal is a non-custodial protocol for on-chain subscriptions. Read more about it: https://diagonal-finance.gitbook.io/diagonal-finance/, https://diagonal.finance/

**Network will be deployed?:**

Registry is already deployed on: **Polygon**, **Arbitrum**, **Optimism**

**Deployer address:**

Contract that will deploy further SuperApps (Services):
- DiagonalRegistryV1: **0x0FfDE8B8b47fCC9Eb9D91fef6cF83D7ba962F997**

**Factory address:**

Contract that will deploy further SuperApps (Services):
- DiagonalRegistryV1: **0x0FfDE8B8b47fCC9Eb9D91fef6cF83D7ba962F997**

**Link of repo of the contract to be deployed:**

Repo is private, please contact for more details.

**Contact info for developer:**

Discord: tcb#8990

**Notes:**

The registry is deployed via dedicated deployer contract using CREATE2, so it has the same address on all networks.

**Comment by hellwolf** [comment]
@d10r let's help them

**Comment by d10r** [comment]
@hellwolf ready to be signed for Polygon, Optimism, Arbitrum

**Comment by hellwolf** [comment]
arbitrum:


DONE signing:

![image](https://user-images.githubusercontent.com/186660/180394459-5c787ca4-ff68-4d94-a7a7-8c1eb24aa7ac.png)

**Comment by hellwolf** [comment]
Polygon:

DONE signing:

![image](https://user-images.githubusercontent.com/186660/180401371-2313ac85-b8a8-47d5-b07f-34b811e6c153.png)

**Comment by hellwolf** [comment]
Optimism:

DONE signing after some acrobatics!

![Uploading image.png…]()

**Comment by hellwolf** [comment]
You are good to go guys 🍾
